<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\AutosaveService;use App\Services\SchemaUpdater;
Auth::requireAdmin();$pdo=Database::connection();SchemaUpdater::run($pdo);$uid=(int)Auth::user()['id'];$message='';
if($_SERVER['REQUEST_METHOD']==='POST'&&Csrf::verify($_POST['_csrf']??null)){
 $id=(int)($_POST['draft_id']??0);if($id){AutosaveService::discard($pdo,$uid,$id);$message='Draft discarded.';}
}
$drafts=AutosaveService::listActive($pdo,$uid);$csrf=Csrf::token();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recovery Center | BDC</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="<?=e(url('admin/'))?>">BDC Admin</a><a class="btn btn-warning btn-sm" href="https://bachatadancecouncil.com/">🏠 BDC Home</a></div></nav><main class="container py-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">Recovery Center</h1><p class="text-muted mb-0">Resume or discard autosaved scoring drafts.</p></div><a class="btn btn-outline-dark" href="<?=e(url('admin/'))?>">Dashboard</a></div><?php if($message):?><div class="alert alert-success"><?=e($message)?></div><?php endif;?><div class="card border-0 shadow-sm"><div class="card-body"><?php if(!$drafts):?><p class="text-muted mb-0">No active autosave drafts.</p><?php else:?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Competition</th><th>Round</th><th>Revision</th><th>Last saved</th><th></th></tr></thead><tbody><?php foreach($drafts as $d):?><tr><td><?=e($d['event_name']?:ucfirst($d['entity_type']).' #'.$d['entity_id'])?></td><td><?=e(trim(ucfirst((string)$d['division']).' '.ucfirst((string)$d['round_type'])))?></td><td>#<?=(int)$d['revision_number']?></td><td><?=e($d['last_saved_at'])?></td><td class="text-end"><?php if($d['entity_type']==='scoring_round'):?><a class="btn btn-sm btn-primary" href="<?=e(url('admin/scoring/?round_id='.(int)$d['entity_id']))?>">Restore / Open</a><?php endif;?><form method="post" class="d-inline" onsubmit="return confirm('Discard this autosave draft?')"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="draft_id" value="<?=(int)$d['id']?>"><button class="btn btn-sm btn-outline-danger">Discard</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></div></main></body></html>
