<?php
declare(strict_types=1);
namespace App\Services;
use PDO;use RuntimeException;
final class AiOperationsService{
 private const TYPES=['executive'=>'Executive Report','improvements'=>'Improvement Suggestions','optimization'=>'Operations Optimization','monitoring'=>'Monitoring Review'];
 public static function ensure(PDO $p):void{$p->exec("CREATE TABLE IF NOT EXISTS bdc_ai_operations_reports(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,data_mode ENUM('test','live') NOT NULL,report_type VARCHAR(40) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'completed',model VARCHAR(100) NULL,prompt_version VARCHAR(20) NOT NULL,snapshot_hash CHAR(64) NOT NULL,report_text LONGTEXT NOT NULL,input_tokens INT UNSIGNED NULL,output_tokens INT UNSIGNED NULL,generated_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_ai_report_mode_created(data_mode,created_at),INDEX idx_ai_report_user_created(generated_by,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
 public static function configured():bool{return trim((string)getenv('OPENAI_API_KEY'))!=='';}public static function types():array{return self::TYPES;}
 public static function snapshot(PDO $p,string $mode):array{$test=$mode==='test';$x=$test?'bdc_test_':'bdc_';$q=['events_total'=>"SELECT COUNT(*) FROM {$x}events",'events_completed'=>"SELECT COUNT(*) FROM {$x}events WHERE status='completed'",'rounds_total'=>"SELECT COUNT(*) FROM {$x}scoring_rounds",'rounds_open'=>"SELECT COUNT(*) FROM {$x}scoring_rounds WHERE status NOT IN('completed','archived','published','discarded')",'rounds_stale'=>"SELECT COUNT(*) FROM {$x}scoring_rounds WHERE status NOT IN('completed','archived','published','discarded') AND updated_at<DATE_SUB(NOW(),INTERVAL 2 HOUR)",'judges_total'=>"SELECT COUNT(*) FROM {$x}scoring_judges",'judge_sessions_incomplete'=>"SELECT COUNT(*) FROM {$x}scoring_judge_sessions WHERE status<>'submitted'",'scoring_entries'=>"SELECT COUNT(*) FROM {$x}scoring_entries"];
  if(!$test)$q+=['competitors_total'=>'SELECT COUNT(*) FROM bdc_competitors','registrations_total'=>'SELECT COUNT(*) FROM bdc_event_registrations','registrations_pending'=>"SELECT COUNT(*) FROM bdc_event_registrations WHERE registration_status IN('pending','submitted')",'publication_approvals_pending'=>"SELECT COUNT(*) FROM bdc_scoring_publications WHERE status='pending_approval'",'profile_requests_pending'=>"SELECT COUNT(*) FROM bdc_profile_requests WHERE status IN('pending','under_review','more_info')",'identity_matches_pending'=>"SELECT COUNT(*) FROM bdc_competitor_link_suggestions WHERE status='pending'",'imports_with_errors_30d'=>"SELECT COUNT(*) FROM bdc_import_batches WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) AND (status='failed' OR error_rows>0)",'deployments_failed_30d'=>"SELECT COUNT(*) FROM bdc_deployment_jobs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) AND status='failed'"];
  $m=[];foreach($q as $k=>$sql){try{$m[$k]=(int)$p->query($sql)->fetchColumn();}catch(\Throwable){$m[$k]=null;}}return ['mode'=>$test?'testing':'live','generated_at'=>date(DATE_ATOM),'metrics'=>$m,'privacy'=>'Aggregate counts only; no names, contacts, IDs, judge identities, or raw scores.'];}
 public static function findings(array $s):array{$m=$s['metrics'];$o=[];foreach([['rounds_stale','warning','Stale scoring rounds','rounds have remained open for over two hours.'],['judge_sessions_incomplete','warning','Incomplete judge sessions','judge sessions are not submitted.'],['publication_approvals_pending','attention','Publication approvals','publications await approval.'],['imports_with_errors_30d','attention','Import errors','imports reported errors in the last 30 days.'],['deployments_failed_30d','critical','Failed deployments','deployments failed in the last 30 days.'],['profile_requests_pending','info','Profile requests','profile requests need review.']] as [$k,$l,$t,$d])if(isset($m[$k])&&(int)$m[$k]>0)$o[]=['level'=>$l,'title'=>$t,'detail'=>(int)$m[$k].' '.$d];if(!$o)$o[]=['level'=>'healthy','title'=>'No immediate operational warnings','detail'=>'The aggregate health checks found no items requiring attention.'];return $o;}
 public static function recent(PDO $p,string $m,int $n=10):array{self::ensure($p);$s=$p->prepare('SELECT r.*,u.full_name generated_by_name FROM bdc_ai_operations_reports r LEFT JOIN bdc_users u ON u.id=r.generated_by WHERE r.data_mode=:m ORDER BY r.id DESC LIMIT '.max(1,min(25,$n)));$s->execute(['m'=>$m]);return $s->fetchAll();}
 public static function generate(PDO $p,string $mode,string $type,int $uid):array{self::ensure($p);if(!isset(self::TYPES[$type]))throw new RuntimeException('Choose a valid AI report.');if(!self::configured())throw new RuntimeException('OPENAI_API_KEY is not configured on this server.');$s=$p->prepare('SELECT COUNT(*) FROM bdc_ai_operations_reports WHERE generated_by=:u AND created_at>=DATE_SUB(NOW(),INTERVAL 1 MINUTE)');$s->execute(['u'=>$uid]);if((int)$s->fetchColumn())throw new RuntimeException('Please wait one minute before generating another report.');$s=$p->prepare('SELECT COUNT(*) FROM bdc_ai_operations_reports WHERE generated_by=:u AND created_at>=CURDATE()');$s->execute(['u'=>$uid]);if((int)$s->fetchColumn()>=25)throw new RuntimeException('Daily AI report limit reached.');
  $snap=self::snapshot($p,$mode);$model=trim((string)getenv('OPENAI_MODEL'))?:'gpt-5-mini';$instructions='You are the operations analyst for the Bachata Dance Council portal. Analyze only supplied anonymous aggregate metrics. Never invent facts. Give concise prioritized recommendations. Separate observations from suggestions. Never recommend altering competition results or judge scores. Use Markdown sections: Summary, Findings, Recommended Actions, Monitoring Checklist.';$input='Report type: '.self::TYPES[$type]."\nEnvironment: ".$snap['mode']."\nSnapshot:\n".json_encode($snap,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);$payload=json_encode(['model'=>$model,'instructions'=>$instructions,'input'=>$input,'max_output_tokens'=>1800],JSON_UNESCAPED_SLASHES);
  $c=curl_init('https://api.openai.com/v1/responses');curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>45,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.trim((string)getenv('OPENAI_API_KEY')),'Content-Type: application/json'],CURLOPT_POSTFIELDS=>$payload]);$raw=curl_exec($c);$http=(int)curl_getinfo($c,CURLINFO_HTTP_CODE);$ce=curl_error($c);curl_close($c);if($raw===false)throw new RuntimeException('AI connection failed: '.$ce);$d=json_decode($raw,true);if($http<200||$http>=300){$msg=is_array($d)?(string)($d['error']['message']??''):'';throw new RuntimeException('AI request failed (HTTP '.$http.').'.($msg?' '.$msg:' Check API access and billing.'));}$text=trim((string)($d['output_text']??''));if(!$text)foreach((array)($d['output']??[]) as $item)foreach((array)($item['content']??[]) as $part)if(($part['type']??'')==='output_text')$text.=(string)($part['text']??'');if(!trim($text))throw new RuntimeException('AI returned an empty report.');$s=$p->prepare('INSERT INTO bdc_ai_operations_reports(data_mode,report_type,model,prompt_version,snapshot_hash,report_text,input_tokens,output_tokens,generated_by) VALUES(:m,:t,:model,:pv,:hash,:report,:it,:ot,:u)');$s->execute(['m'=>$mode,'t'=>$type,'model'=>$model,'pv'=>'v1','hash'=>hash('sha256',json_encode($snap)),'report'=>$text,'it'=>$d['usage']['input_tokens']??null,'ot'=>$d['usage']['output_tokens']??null,'u'=>$uid]);return ['id'=>(int)$p->lastInsertId(),'report_text'=>$text,'model'=>$model];}
}
