<?php
declare(strict_types=1);

namespace App\Services;

use PDO;
use RuntimeException;

final class BdcMcpService
{
    public static function tools():array{return [
        ['name'=>'list_event_rounds','title'=>'List all BDC events and rounds','description'=>'Use this when you need Jack & Jill events and rounds in any state, including events that do not yet have a round. Filter by event state, round state or scoring mode when needed.','inputSchema'=>['type'=>'object','properties'=>['data_mode'=>['type'=>'string','enum'=>['test','live']],'name_query'=>['type'=>'string'],'event_status'=>['type'=>'string','enum'=>['all','draft','published','completed','cancelled'],'default'=>'all'],'round_status'=>['type'=>'string','maxLength'=>40],'scoring_mode'=>['type'=>'string','enum'=>['all','manual','automated'],'default'=>'all']],'required'=>['data_mode'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE]]],'annotations'=>['readOnlyHint'=>true,'destructiveHint'=>false,'openWorldHint'=>false]],
        ['name'=>'stage_event_edit','title'=>'Stage an event edit for approval','description'=>'Use this when exact Jack & Jill event metadata or one round needs editing in Test or Live. The proposal changes nothing until a Super Admin approves it; structural round fields are locked after scoring starts.','inputSchema'=>['type'=>'object','properties'=>['data_mode'=>['type'=>'string','enum'=>['test','live']],'event_id'=>['type'=>'integer','minimum'=>1],'round_id'=>['type'=>'integer','minimum'=>1],'changes'=>['type'=>'object','properties'=>['event_name'=>['type'=>'string','maxLength'=>190],'event_date'=>['type'=>['string','null']],'location'=>['type'=>['string','null'],'maxLength'=>190],'venue'=>['type'=>['string','null'],'maxLength'=>255],'event_status'=>['type'=>'string','enum'=>['draft','published','completed','cancelled']],'scheduled_at'=>['type'=>['string','null']],'dance_style'=>['type'=>'string','enum'=>['bachata','salsa']],'division'=>['type'=>'string','enum'=>['novice','intermediate','advanced','all_star','bachata_rising','bachata_open','bachata_invitational','salsa_rising','salsa_open']],'round_type'=>['type'=>'string','enum'=>['heats','semifinal','final']],'scoring_mode'=>['type'=>'string','enum'=>['manual','automated']]],'minProperties'=>1,'additionalProperties'=>false],'source_key'=>['type'=>'string','maxLength'=>191]],'required'=>['data_mode','event_id','changes'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE,McpOAuthService::STAGE_SCOPE]]],'annotations'=>['readOnlyHint'=>false,'destructiveHint'=>false,'idempotentHint'=>true,'openWorldHint'=>false]],
        ['name'=>'list_event_roster','title'=>'List an event roster','description'=>'Use this when you need the complete active competitor roster and bib assignments for one exact Jack & Jill round.','inputSchema'=>['type'=>'object','properties'=>['data_mode'=>['type'=>'string','enum'=>['test','live']],'event_id'=>['type'=>'integer','minimum'=>1],'round_id'=>['type'=>'integer','minimum'=>1]],'required'=>['data_mode','event_id','round_id'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE]]],'annotations'=>['readOnlyHint'=>true,'destructiveHint'=>false,'openWorldHint'=>false]],
        ['name'=>'stage_division_roster_sync','title'=>'Stage division roster and bib sync','description'=>'Use this when a draft Jack & Jill round must receive every newly registered division competitor and all active bibs must be reassigned sequentially. Nothing changes until Super Admin approval.','inputSchema'=>['type'=>'object','properties'=>['data_mode'=>['type'=>'string','enum'=>['test','live']],'event_id'=>['type'=>'integer','minimum'=>1],'round_id'=>['type'=>'integer','minimum'=>1],'leader_bib_start'=>['type'=>'integer','minimum'=>1],'follower_bib_start'=>['type'=>'integer','minimum'=>1],'range_size'=>['type'=>'integer','minimum'=>1,'maximum'=>500,'default'=>50],'source_key'=>['type'=>'string','maxLength'=>191]],'required'=>['data_mode','event_id','round_id','leader_bib_start','follower_bib_start'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE,McpOAuthService::STAGE_SCOPE]]],'annotations'=>['readOnlyHint'=>false,'destructiveHint'=>false,'idempotentHint'=>true,'openWorldHint'=>false]],
        ['name'=>'stage_competitor_removals','title'=>'Stage competitor removals','description'=>'Stage removal of exact active competitor entries from one draft Jack & Jill round. Nothing changes until Super Admin approval.','inputSchema'=>['type'=>'object','properties'=>['data_mode'=>['type'=>'string','enum'=>['test','live']],'event_id'=>['type'=>'integer','minimum'=>1],'round_id'=>['type'=>'integer','minimum'=>1],'entry_ids'=>['type'=>'array','minItems'=>1,'maxItems'=>250,'uniqueItems'=>true,'items'=>['type'=>'integer','minimum'=>1]],'source_key'=>['type'=>'string','maxLength'=>191]],'required'=>['data_mode','event_id','round_id','entry_ids'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE,McpOAuthService::STAGE_SCOPE]]],'annotations'=>['readOnlyHint'=>false,'destructiveHint'=>true,'idempotentHint'=>true,'openWorldHint'=>false]],
        ['name'=>'stage_competitor_bib_updates','title'=>'Stage competitor bib updates','description'=>'Stage atomic bib amendments for exact active competitor entries in one draft Jack & Jill round. Nothing changes until Super Admin approval.','inputSchema'=>['type'=>'object','properties'=>['data_mode'=>['type'=>'string','enum'=>['test','live']],'event_id'=>['type'=>'integer','minimum'=>1],'round_id'=>['type'=>'integer','minimum'=>1],'updates'=>['type'=>'array','minItems'=>1,'maxItems'=>250,'items'=>['type'=>'object','properties'=>['entry_id'=>['type'=>'integer','minimum'=>1],'bib_number'=>['type'=>'integer','minimum'=>1,'maximum'=>999999]],'required'=>['entry_id','bib_number'],'additionalProperties'=>false]],'source_key'=>['type'=>'string','maxLength'=>191]],'required'=>['data_mode','event_id','round_id','updates'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE,McpOAuthService::STAGE_SCOPE]]],'annotations'=>['readOnlyHint'=>false,'destructiveHint'=>false,'idempotentHint'=>true,'openWorldHint'=>false]],
        ['name'=>'list_division_competitors','title'=>'List eligible division competitors','description'=>'List council identities eligible for an exact Salsa or Bachata division, optionally filtered by role or name.','inputSchema'=>['type'=>'object','properties'=>['dance_style'=>['type'=>'string','enum'=>['bachata','salsa']],'division'=>['type'=>'string','enum'=>['novice','intermediate','advanced','all_star','bachata_rising','bachata_open','bachata_invitational','salsa_rising','salsa_open']],'role'=>['type'=>'string','enum'=>['leader','follower']],'query'=>['type'=>'string']],'required'=>['dance_style','division'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE]]],'annotations'=>['readOnlyHint'=>true,'destructiveHint'=>false,'openWorldHint'=>false]],
        ['name'=>'stage_competitor_additions','title'=>'Stage competitors for approval','description'=>'Stage exact competitors for an existing draft Jack & Jill round. This does not alter the roster; a Super Admin must approve the proposal in Integration Review.','inputSchema'=>['type'=>'object','properties'=>['data_mode'=>['type'=>'string','enum'=>['test','live']],'target_event_id'=>['type'=>'integer','minimum'=>1],'target_round_id'=>['type'=>'integer','minimum'=>1],'competitors'=>['type'=>'array','minItems'=>1,'maxItems'=>250,'items'=>['type'=>'object','properties'=>['identity_code'=>['type'=>'string'],'role'=>['type'=>'string','enum'=>['leader','follower']],'bib_number'=>['type'=>'integer','minimum'=>1]],'required'=>['identity_code','role','bib_number'],'additionalProperties'=>false]],'source_key'=>['type'=>'string']],'required'=>['data_mode','target_event_id','target_round_id','competitors'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE,McpOAuthService::STAGE_SCOPE]]],'annotations'=>['readOnlyHint'=>false,'destructiveHint'=>false,'idempotentHint'=>true,'openWorldHint'=>false]],
        ['name'=>'get_staged_batch_status','title'=>'Get staged batch status','description'=>'Check validation and Super Admin review status for a previously staged BDC batch.','inputSchema'=>['type'=>'object','properties'=>['batch_key'=>['type'=>'string']],'required'=>['batch_key'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE]]],'annotations'=>['readOnlyHint'=>true,'destructiveHint'=>false,'openWorldHint'=>false]],
        ['name'=>'diagnose_projection','title'=>'Diagnose a BDC projection','description'=>'Run read-only integrity diagnostics for an exact Jack & Jill or Dance Cup projection in Test or Live. Checks event and round selection, screen state, rosters, bibs, judges, countries, flags, photos, flights, pagination, results and reveal safety without changing data or exposing projector tokens.','inputSchema'=>['type'=>'object','properties'=>['event_system'=>['type'=>'string','enum'=>['jack_jill','dance_cup']],'data_mode'=>['type'=>'string','enum'=>['test','live']],'event_id'=>['type'=>'integer','minimum'=>1],'round_id'=>['type'=>'integer','minimum'=>1],'competition_id'=>['type'=>'integer','minimum'=>1]],'required'=>['event_system','data_mode','event_id'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE]]],'annotations'=>['readOnlyHint'=>true,'destructiveHint'=>false,'idempotentHint'=>true,'openWorldHint'=>false]],
        ['name'=>'stage_competitor_photo_update','title'=>'Stage competitor photo for approval','description'=>'Stage one JPG, PNG or WebP replacement photo for an exact BDC or SDC competitor identity. This changes no profile fields and does not publish the photo until a Super Admin approves it in Integration Review.','inputSchema'=>['type'=>'object','properties'=>['identity_code'=>['type'=>'string','pattern'=>'^(BDC|SDC)-[0-9]+$'],'photo_base64'=>['type'=>'string','minLength'=>1],'photo_mime'=>['type'=>'string','enum'=>['image/jpeg','image/png','image/webp']],'photo_name'=>['type'=>'string','maxLength'=>190],'source_key'=>['type'=>'string','maxLength'=>191]],'required'=>['identity_code','photo_base64','photo_mime'],'additionalProperties'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[McpOAuthService::READ_SCOPE,McpOAuthService::STAGE_SCOPE]]],'annotations'=>['readOnlyHint'=>false,'destructiveHint'=>false,'idempotentHint'=>true,'openWorldHint'=>false]],
    ];}

    public static function call(PDO $pdo,string $name,array $a):array
    {
        return match($name){'list_event_rounds'=>self::rounds($pdo,$a),'stage_event_edit'=>self::stageEventEdit($pdo,$a),'list_event_roster'=>self::eventRoster($pdo,$a),'stage_division_roster_sync'=>self::stageRosterSync($pdo,$a),'stage_competitor_removals'=>self::stageRosterChange($pdo,$a,'remove_competitors'),'stage_competitor_bib_updates'=>self::stageRosterChange($pdo,$a,'update_bibs'),'list_division_competitors'=>self::competitors($pdo,$a),'stage_competitor_additions'=>self::stage($pdo,$a),'get_staged_batch_status'=>self::status($pdo,$a),'diagnose_projection'=>ProjectionDiagnosticsService::diagnose($pdo,$a),'stage_competitor_photo_update'=>self::stagePhoto($pdo,$a),default=>throw new RuntimeException('Unknown tool.')};
    }
    private static function rounds(PDO $pdo,array $a):array
    {$mode=self::mode($a);$events=$mode==='test'?'bdc_test_events':'bdc_events';$rounds=$mode==='test'?'bdc_test_scoring_rounds':'bdc_scoring_rounds';$needle=trim((string)($a['name_query']??''));$eventStatus=strtolower(trim((string)($a['event_status']??'all')));if(!in_array($eventStatus,['all','draft','published','completed','cancelled'],true))throw new RuntimeException('event_status is invalid.');$roundStatus=strtolower(trim((string)($a['round_status']??'')));if($roundStatus==='all')$roundStatus='';if($roundStatus!==''&&!preg_match('/^[a-z][a-z0-9_]{0,39}$/',$roundStatus))throw new RuntimeException('round_status is invalid.');$scoring=strtolower(trim((string)($a['scoring_mode']??'all')));if(!in_array($scoring,['all','manual','automated'],true))throw new RuntimeException('scoring_mode is invalid.');$sql="SELECT e.id event_id,e.name event_name,e.event_date,e.location,e.venue,e.status event_status,r.id round_id,r.round_type,r.division,r.status round_status,r.scoring_mode,r.scheduled_at,COALESCE(r.dance_style,CASE WHEN r.division LIKE 'salsa_%' THEN 'salsa' ELSE 'bachata' END) dance_style FROM {$events} e LEFT JOIN {$rounds} r ON r.event_id=e.id WHERE 1=1";$params=[];if($needle!==''){$sql.=' AND e.name LIKE :name';$params['name']='%'.$needle.'%';}if($eventStatus!=='all'){$sql.=' AND e.status=:event_status';$params['event_status']=$eventStatus;}if($roundStatus!==''){$sql.=' AND r.status=:round_status';$params['round_status']=$roundStatus;}if($scoring!=='all'){$sql.=' AND r.scoring_mode=:scoring_mode';$params['scoring_mode']=$scoring;}$sql.=' ORDER BY e.event_date IS NULL,e.event_date,e.id,r.id LIMIT 500';$s=$pdo->prepare($sql);$s->execute($params);$rows=$s->fetchAll();return ['data_mode'=>$mode,'filters'=>['event_status'=>$eventStatus,'round_status'=>$roundStatus?:'all','scoring_mode'=>$scoring],'count'=>count($rows),'events_and_rounds'=>$rows];}

    private static function stageEventEdit(PDO $pdo,array $a):array
    {
        $mode=self::mode($a);$eventId=(int)($a['event_id']??0);$roundId=(int)($a['round_id']??0);$changes=$a['changes']??null;
        if($eventId<1||!is_array($changes)||$changes===[])throw new RuntimeException('event_id and at least one change are required.');
        $roundFields=['scheduled_at','dance_style','division','round_type','scoring_mode'];foreach($roundFields as $field)if(array_key_exists($field,$changes)&&$roundId<1)throw new RuntimeException('round_id is required when changing round fields.');
        $source=substr(trim((string)($a['source_key']??'')),0,191);if($source==='')$source='event-edit-'.$mode.'-'.$eventId.'-'.$roundId.'-'.substr(hash('sha256',json_encode($changes)),0,16);
        $batch='chatgpt-event-edit-'.gmdate('Ymd').'-'.substr(hash('sha256',$source),0,20);
        return EventIntegrationService::submitBatch($pdo,['batch_key'=>$batch,'source_system'=>'chatgpt_mcp','items'=>[['event_system'=>'jack_jill','data_mode'=>$mode,'source_key'=>$source,'operation'=>'edit_event','payload'=>['target_event_id'=>$eventId,'target_round_id'=>$roundId?:null,'changes'=>$changes]]]]);
    }
    private static function eventRoster(PDO $pdo,array $a):array
    {
        $mode=self::mode($a);$event=(int)($a['event_id']??0);$round=(int)($a['round_id']??0);if($event<1||$round<1)throw new RuntimeException('event_id and round_id are required.');$events=$mode==='test'?'bdc_test_events':'bdc_events';$rounds=$mode==='test'?'bdc_test_scoring_rounds':'bdc_scoring_rounds';$entries=$mode==='test'?'bdc_test_scoring_entries':'bdc_scoring_entries';$competitors=$mode==='test'?'bdc_test_competitors':'bdc_competitors';$q=$pdo->prepare("SELECT e.id event_id,e.name event_name,e.status event_status,r.id round_id,r.dance_style,r.division,r.round_type,r.status round_status,se.id entry_id,se.competitor_id,se.dance_role role,se.bib_number,se.display_name,CASE WHEN r.dance_style='salsa' THEN s.sdc_id ELSE c.bdc_id END identity_code FROM {$events} e JOIN {$rounds} r ON r.event_id=e.id LEFT JOIN {$entries} se ON se.round_id=r.id AND se.entry_status='active' LEFT JOIN {$competitors} c ON c.id=se.competitor_id LEFT JOIN bdc_sdc_competitors s ON s.competitor_id=se.competitor_id AND s.status='active' WHERE e.id=:event AND r.id=:round ORDER BY FIELD(se.dance_role,'leader','follower'),se.bib_number,se.display_name");$q->execute(['event'=>$event,'round'=>$round]);$rows=$q->fetchAll();if(!$rows)throw new RuntimeException('The event round was not found.');$meta=array_intersect_key($rows[0],array_flip(['event_id','event_name','event_status','round_id','dance_style','division','round_type','round_status']));$roster=[];foreach($rows as $row)if($row['entry_id']!==null){if(trim((string)$row['identity_code'])==='')throw new RuntimeException('An active roster entry is missing its '.(strtolower((string)$row['dance_style'])==='salsa'?'SDC':'BDC').' identity.');$roster[]=array_intersect_key($row,array_flip(['entry_id','competitor_id','identity_code','display_name','role','bib_number']));}return ['data_mode'=>$mode,'event'=>$meta,'count'=>count($roster),'leaders'=>count(array_filter($roster,fn($r)=>$r['role']==='leader')),'followers'=>count(array_filter($roster,fn($r)=>$r['role']==='follower')),'roster'=>$roster];
    }
    private static function stageRosterSync(PDO $pdo,array $a):array
    {
        $mode=self::mode($a);$event=(int)($a['event_id']??0);$round=(int)($a['round_id']??0);$leaderStart=(int)($a['leader_bib_start']??0);$followerStart=(int)($a['follower_bib_start']??0);$range=(int)($a['range_size']??50);if($event<1||$round<1||$leaderStart<1||$followerStart<1||$range<1||$range>500)throw new RuntimeException('Exact event, round, bib starts and a valid range_size are required.');$current=self::eventRoster($pdo,['data_mode'=>$mode,'event_id'=>$event,'round_id'=>$round]);$dance=(string)$current['event']['dance_style'];$division=(string)$current['event']['division'];$eligible=self::competitors($pdo,['dance_style'=>$dance,'division'=>$division]);$byKey=[];foreach($current['roster'] as $row)$byKey[strtoupper((string)$row['identity_code'])."\0".$row['role']]=['identity_code'=>(string)$row['identity_code'],'name'=>(string)$row['display_name'],'role'=>(string)$row['role'],'existing'=>true];foreach($eligible['competitors'] as $row)foreach((array)$row['eligible_roles'] as $role){$key=strtoupper((string)$row['identity_code'])."\0".$role;if(!isset($byKey[$key]))$byKey[$key]=['identity_code'=>(string)$row['identity_code'],'name'=>(string)$row['exact_name'],'role'=>$role,'existing'=>false];}$desired=array_values($byKey);usort($desired,static fn(array $x,array $y):int=>[$x['role']==='leader'?0:1,strtolower($x['name']),$x['identity_code']]<=>[$y['role']==='leader'?0:1,strtolower($y['name']),$y['identity_code']]);$offset=['leader'=>0,'follower'=>0];$normalized=[];$added=[];foreach($desired as $row){$role=$row['role'];if($offset[$role]>=$range)throw new RuntimeException(ucfirst($role).' roster exceeds the reserved '.$range.'-bib range.');$bib=($role==='leader'?$leaderStart:$followerStart)+$offset[$role]++;$normalized[]=['council_id'=>$row['identity_code'],'role'=>$role,'bib'=>$bib];if(!$row['existing'])$added[]=['identity_code'=>$row['identity_code'],'name'=>$row['name'],'role'=>$role,'bib'=>$bib];}$source=substr(trim((string)($a['source_key']??'')),0,191);if($source==='')$source='roster-sync-'.$mode.'-'.$event.'-'.$round.'-'.$leaderStart.'-'.$followerStart.'-'.substr(hash('sha256',json_encode($normalized)),0,12);$batch='chatgpt-roster-sync-'.gmdate('Ymd').'-'.substr(hash('sha256',$source),0,20);$result=EventIntegrationService::submitBatch($pdo,['batch_key'=>$batch,'source_system'=>'chatgpt_mcp','items'=>[['event_system'=>'jack_jill','data_mode'=>$mode,'source_key'=>$source,'operation'=>'sync_competitors','payload'=>['target_event_id'=>$event,'target_round_id'=>$round,'competitors'=>$normalized]]]]);$result['preview']=['event_name'=>$current['event']['event_name'],'division'=>$division,'previous_count'=>$current['count'],'new_count'=>count($normalized),'added'=>$added,'leader_bibs'=>$leaderStart.'-'.($leaderStart+$offset['leader']-1),'follower_bibs'=>$followerStart.'-'.($followerStart+$offset['follower']-1)];return $result;
    }
    private static function stageRosterChange(PDO $pdo,array $a,string $operation):array
    {
        $mode=self::mode($a);$event=(int)($a['event_id']??0);$round=(int)($a['round_id']??0);if($event<1||$round<1)throw new RuntimeException('Exact event_id and round_id are required.');$payload=['target_event_id'=>$event,'target_round_id'=>$round];
        if($operation==='remove_competitors'){$ids=array_values(array_unique(array_map('intval',(array)($a['entry_ids']??[]))));if(!$ids||in_array(0,$ids,true))throw new RuntimeException('Select at least one valid active entry_id.');$payload['entry_ids']=$ids;$fingerprint=$ids;}
        else{$updates=$a['updates']??null;if(!is_array($updates)||$updates===[])throw new RuntimeException('Select at least one bib update.');$normalized=[];foreach($updates as $row){if(!is_array($row))throw new RuntimeException('Every bib update must be an object.');$normalized[]=['entry_id'=>(int)($row['entry_id']??0),'bib'=>(int)($row['bib_number']??0)];}$payload['updates']=$normalized;$fingerprint=$normalized;}
        $source=substr(trim((string)($a['source_key']??'')),0,191);if($source==='')$source=$operation.'-'.$mode.'-'.$event.'-'.$round.'-'.substr(hash('sha256',json_encode($fingerprint)),0,16);$batch='chatgpt-roster-change-'.gmdate('Ymd').'-'.substr(hash('sha256',$source),0,20);
        return EventIntegrationService::submitBatch($pdo,['batch_key'=>$batch,'source_system'=>'chatgpt_mcp','items'=>[['event_system'=>'jack_jill','data_mode'=>$mode,'source_key'=>$source,'operation'=>$operation,'payload'=>$payload]]]);
    }
    private static function competitors(PDO $pdo,array $a):array
    {
        $dance=strtolower(trim((string)($a['dance_style']??'')));$division=strtolower(trim((string)($a['division']??'')));
        if(!in_array($dance,['bachata','salsa'],true))throw new RuntimeException('dance_style is required.');
        $role=strtolower(trim((string)($a['role']??'')));if($role!==''&&!in_array($role,['leader','follower'],true))throw new RuntimeException('role must be leader or follower.');
        $query=trim((string)($a['query']??''));$rows=JackJillCompetitorEligibilityService::directory($pdo,$dance,$role!==''?$role:null,1500);
        $registered=null;
        if(SpecialCategoryService::isSpecial($division)){
            if($dance==='salsa'){
                $category=$pdo->prepare("SELECT DISTINCT s.competitor_id FROM bdc_sdc_competitor_categories c JOIN bdc_sdc_competitors s ON s.id=c.sdc_competitor_id WHERE c.category=:category AND s.status='active'");
            }else{
                $category=$pdo->prepare("SELECT DISTINCT competitor_id FROM bdc_competitor_special_categories WHERE dance_style='bachata' AND category=:category");
            }
            $category->execute(['category'=>$division]);$registered=array_fill_keys(array_map('intval',$category->fetchAll(PDO::FETCH_COLUMN)),true);
        }
        $lower=static fn(string $v):string=>function_exists('mb_strtolower')?mb_strtolower($v,'UTF-8'):strtolower($v);$needle=$lower($query);$eligible=[];
        foreach($rows as $row){
            if($registered!==null&&!isset($registered[(int)$row['id']]))continue;
            if($needle!==''&&!str_contains($lower((string)($row['identity_code']??'').' '.(string)($row['exact_name']??'')),$needle))continue;
            $profileRole=strtolower((string)($row['dance_role']??''));$roles=$role!==''?[$role]:($profileRole==='both'?['leader','follower']:[$profileRole]);$allowed=[];
            foreach($roles as $candidateRole){
                if(!in_array($candidateRole,['leader','follower'],true))continue;
                $check=DivisionProgressionService::eligibilityFromApprovedHistory($pdo,(int)$row['id'],$candidateRole,$dance,$division);
                if(!empty($check['eligible']))$allowed[]=$candidateRole;
            }
            if(!$allowed)continue;$row['eligible_roles']=$allowed;$eligible[]=$row;
        }
        return ['dance_style'=>$dance,'division'=>$division,'count'=>count($eligible),'competitors'=>array_slice($eligible,0,500)];
    }
    private static function stage(PDO $pdo,array $a):array
    {
        $mode=self::mode($a);$event=(int)($a['target_event_id']??0);$round=(int)($a['target_round_id']??0);$competitors=$a['competitors']??null;
        if($event<1||$round<1||!is_array($competitors)||$competitors===[])throw new RuntimeException('Exact target_event_id, target_round_id and competitors are required.');
        $normalized=[];
        foreach($competitors as $competitor){
            if(!is_array($competitor))throw new RuntimeException('Every competitor selection must be an object.');
            $normalized[]=['council_id'=>(string)($competitor['identity_code']??''),'role'=>(string)($competitor['role']??''),'bib'=>$competitor['bib_number']??0];
        }
        $source=substr(trim((string)($a['source_key']??'')),0,191);if($source==='')$source='round-'.$mode.'-'.$event.'-'.$round.'-'.substr(hash('sha256',json_encode($normalized)),0,16);$batch='chatgpt-'.gmdate('Ymd').'-'.substr(hash('sha256',$source),0,20);return EventIntegrationService::submitBatch($pdo,['batch_key'=>$batch,'source_system'=>'chatgpt_mcp','items'=>[['event_system'=>'jack_jill','data_mode'=>$mode,'source_key'=>$source,'operation'=>'add_competitors','payload'=>['target_event_id'=>$event,'target_round_id'=>$round,'competitors'=>$normalized]]]]);
    }
    private static function status(PDO $pdo,array $a):array{$key=trim((string)($a['batch_key']??''));if($key==='')throw new RuntimeException('batch_key is required.');$row=EventIntegrationService::batchStatus($pdo,$key);if(!$row)throw new RuntimeException('Batch not found.');return ['batch'=>$row];}
    private static function stagePhoto(PDO $pdo,array $a):array
    {
        $identity=strtoupper(trim((string)($a['identity_code']??'')));if(!preg_match('/^(BDC|SDC)-\d+$/',$identity))throw new RuntimeException('A valid BDC or SDC identity_code is required.');
        $photo=(string)($a['photo_base64']??'');$mime=strtolower(trim((string)($a['photo_mime']??'')));if($photo===''||!in_array($mime,['image/jpeg','image/png','image/webp'],true))throw new RuntimeException('A JPG, PNG or WebP photo is required.');
        $source=substr(trim((string)($a['source_key']??'')),0,191);if($source==='')$source='photo-'.$identity.'-'.substr(hash('sha256',$photo),0,20);
        $batch='chatgpt-photo-'.gmdate('Ymd').'-'.substr(hash('sha256',$source),0,20);
        return ProfileIntegrationService::submitMcpCompetitorPhotoBatch($pdo,['batch_key'=>$batch,'source_system'=>'chatgpt_mcp','items'=>[['entity_type'=>'competitor','source_key'=>$source,'payload'=>['operation'=>'photo_replace','identity_code'=>$identity,'photo_base64'=>$photo,'photo_mime'=>$mime,'photo_name'=>substr(trim((string)($a['photo_name']??'')),0,190)]]]]);
    }
    private static function mode(array $a):string{$mode=strtolower(trim((string)($a['data_mode']??'')));if(!in_array($mode,['test','live'],true))throw new RuntimeException('data_mode must be test or live.');return $mode;}
}
