<?php
declare(strict_types=1);

namespace App\Services;

use App\Core\Auth;
use PDO;
use RuntimeException;

final class DanceCupCategoryEditService
{
    public static function ensureColumns(PDO $pdo,bool $test):void
    {
        $table=DanceCupScoringService::tables($test)['competitions'];
        foreach(['edit_unlocked_at DATETIME NULL','edit_unlocked_by BIGINT UNSIGNED NULL','edit_unlock_reason VARCHAR(500) NULL'] as $definition){try{$pdo->exec("ALTER TABLE {$table} ADD COLUMN {$definition}");}catch(\Throwable){}}
    }

    public static function state(PDO $pdo,int $competitionId,bool $test):array
    {
        self::ensureColumns($pdo,$test);$p=$test?'bdc_test_dance_cup':'bdc_dance_cup';$t=DanceCupScoringService::tables($test);
        $q=$pdo->prepare("SELECT c.*,(SELECT COUNT(*) FROM {$p}_marks m WHERE m.competition_id=c.id) mark_count,(SELECT COUNT(*) FROM {$p}_judge_sessions s WHERE s.competition_id=c.id AND (s.status IN('scoring','submitted') OR s.started_at IS NOT NULL)) started_sessions FROM {$t['competitions']} c WHERE c.id=:competition");$q->execute(['competition'=>$competitionId]);$row=$q->fetch();if(!$row)throw new RuntimeException('Dance Cup category not found.');$row['scoring_started']=(int)$row['mark_count']>0||(int)$row['started_sessions']>0;return $row;
    }

    public static function unlock(PDO $pdo,int $competitionId,string $reason,string $confirmation,int $userId,bool $test):void
    {
        if(!Auth::canOverrideCompletedScores())throw new RuntimeException('You do not have permission to unlock Dance Cup category editing.');$reason=trim($reason);if(strtoupper(trim($confirmation))!=='UNLOCK')throw new RuntimeException('Type UNLOCK exactly to confirm.');$reasonLength=function_exists('mb_strlen')?mb_strlen($reason):strlen($reason);if($reasonLength<8)throw new RuntimeException('Enter a clear unlock reason of at least 8 characters.');$t=DanceCupScoringService::tables($test);$state=self::state($pdo,$competitionId,$test);if(in_array((string)$state['status'],['submitted','pending_approval','approved'],true))throw new RuntimeException('Submitted or approved results must be reopened through the protected result workflow before editing the category.');$pdo->prepare("UPDATE {$t['competitions']} SET edit_unlocked_at=NOW(),edit_unlocked_by=:user,edit_unlock_reason=:reason WHERE id=:competition")->execute(['user'=>$userId,'reason'=>$reason,'competition'=>$competitionId]);Auth::audit($userId,'dance_cup_category_edit_unlocked',['reason'=>$reason,'data_mode'=>$test?'test':'live'],'dance_cup_competition',$competitionId);
    }

    public static function save(PDO $pdo,int $competitionId,array $data,array $criteria,string $resetConfirmation,int $userId,bool $test):array
    {
        $p=$test?'bdc_test_dance_cup':'bdc_dance_cup';$t=DanceCupScoringService::tables($test);$current=self::state($pdo,$competitionId,$test);if($current['scoring_started']&&empty($current['edit_unlocked_at']))throw new RuntimeException('Scoring has started. Unlock category editing before saving changes.');if(in_array((string)$current['status'],['submitted','pending_approval','approved'],true))throw new RuntimeException('Submitted or approved results cannot be edited here.');
        $category=trim((string)($data['category_name']??''));$entryType=(string)($data['entry_type']??'');$round=(string)($data['round_name']??'');$style=(string)($data['dance_style']??'');$level=(string)($data['competition_level']??'');$gender=(string)($data['gender_eligibility']??'');$performance=(string)($data['performance_type']??'');
        if($category==='')throw new RuntimeException('Category name is required.');if(!in_array($entryType,['solo','couple','duo','pro_am','team'],true))throw new RuntimeException('Invalid entry type.');if(!in_array($round,['qualifier','quarterfinal','semifinal','final'],true))throw new RuntimeException('Invalid round.');if(!in_array($style,['salsa','bachata','cha_cha','other'],true))throw new RuntimeException('Invalid dance style.');if(!in_array($level,['amateur','intermediate','pro_am','professional','open'],true))throw new RuntimeException('Invalid competition level.');if(!in_array($gender,['mixed','female_only','male_only'],true))throw new RuntimeException('Invalid category gender.');if(!in_array($performance,['showcase','classic','cabaret','shines','just_dance'],true))throw new RuntimeException('Invalid performance type.');if(!$criteria)throw new RuntimeException('Add at least one scoring criterion.');
        $normalized=[];$seen=[];$maximum=0.0;foreach($criteria as $criterion){$name=trim((string)($criterion['name']??''));$max=(float)($criterion['max']??0);$key=function_exists('mb_strtolower')?mb_strtolower($name,'UTF-8'):strtolower($name);if($name===''||$max<=0)throw new RuntimeException('Every criterion needs a name and maximum above zero.');if(isset($seen[$key]))throw new RuntimeException('Criterion names must be unique.');$seen[$key]=true;$maximum+=$max;$normalized[]=['name'=>$name,'max'=>$max];}if($maximum>1000)throw new RuntimeException('Combined maximum cannot exceed 1000.');
        $existingQ=$pdo->prepare("SELECT criterion_name,maximum_points FROM {$t['criteria']} WHERE competition_id=:competition ORDER BY sort_order,id");$existingQ->execute(['competition'=>$competitionId]);$existing=array_map(static fn(array $row):array=>['name'=>(string)$row['criterion_name'],'max'=>(float)$row['maximum_points']],$existingQ->fetchAll());$criteriaChanged=$existing!==$normalized;$reset=$criteriaChanged&&(int)$current['mark_count']>0;if($reset&&strtoupper(trim($resetConfirmation))!=='RESET SCORES')throw new RuntimeException('Criteria changed after scoring started. Type RESET SCORES exactly to clear incompatible marks and continue.');
        $pdo->beginTransaction();try{$lock=$pdo->prepare("SELECT id FROM {$t['competitions']} WHERE id=:competition FOR UPDATE");$lock->execute(['competition'=>$competitionId]);if(!$lock->fetchColumn())throw new RuntimeException('Category no longer exists.');$update=$pdo->prepare("UPDATE {$t['competitions']} SET category_name=:category,entry_type=:entry_type,dance_style=:style,competition_level=:level,gender_eligibility=:gender,performance_type=:performance,round_name=:round,maximum_score=:maximum,edit_unlocked_at=NULL,edit_unlocked_by=NULL,edit_unlock_reason=NULL WHERE id=:competition");$update->execute(['category'=>$category,'entry_type'=>$entryType,'style'=>$style,'level'=>$level,'gender'=>$gender,'performance'=>$performance,'round'=>$round,'maximum'=>$maximum,'competition'=>$competitionId]);if($criteriaChanged){if($reset){$pdo->prepare("DELETE FROM {$p}_marks WHERE competition_id=:competition")->execute(['competition'=>$competitionId]);$pdo->prepare("DELETE FROM {$p}_scoring_results WHERE competition_id=:competition")->execute(['competition'=>$competitionId]);$pdo->prepare("UPDATE {$p}_judge_sessions SET status='not_started',started_at=NULL,submitted_at=NULL,last_seen_at=NULL WHERE competition_id=:competition")->execute(['competition'=>$competitionId]);}$pdo->prepare("DELETE FROM {$t['criteria']} WHERE competition_id=:competition")->execute(['competition'=>$competitionId]);$insert=$pdo->prepare("INSERT INTO {$t['criteria']}(competition_id,criterion_name,maximum_points,sort_order) VALUES(:competition,:name,:maximum,:sort)");foreach($normalized as $index=>$criterion)$insert->execute(['competition'=>$competitionId,'name'=>$criterion['name'],'maximum'=>$criterion['max'],'sort'=>$index+1]);}$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}Auth::audit($userId,'dance_cup_category_edited',['criteria_changed'=>$criteriaChanged,'scores_reset'=>$reset,'data_mode'=>$test?'test':'live'],'dance_cup_competition',$competitionId);return ['criteria_changed'=>$criteriaChanged,'scores_reset'=>$reset];
    }
}
