<?php
declare(strict_types=1);
namespace App\Services;
use PDO;
final class JudgeDirectoryService{
 public static function ensure(PDO $pdo):void{
  $pdo->exec("CREATE TABLE IF NOT EXISTS bdc_judges(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,judge_code VARCHAR(24) NULL,full_name VARCHAR(160) NOT NULL,country VARCHAR(100) NULL,country_code CHAR(2) NULL,photo_url VARCHAR(500) NULL,instagram VARCHAR(160) NULL,email VARCHAR(190) NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',notes TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE INDEX uq_judge_code(judge_code),INDEX idx_judge_name(full_name),INDEX idx_judge_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  foreach(['bdc_scoring_judges','bdc_test_scoring_judges'] as $table){try{$pdo->exec("ALTER TABLE {$table} ADD COLUMN judge_id BIGINT UNSIGNED NULL AFTER id");}catch(\Throwable){}try{$pdo->exec("ALTER TABLE {$table} ADD INDEX idx_judge_directory(judge_id)");}catch(\Throwable){}}
 }
 public static function search(PDO $pdo,string $term,int $limit=15):array{self::ensure($pdo);$term=trim($term);if(mb_strlen($term)<2)return [];$s=$pdo->prepare("SELECT id,judge_code,full_name,country,country_code,photo_url,instagram,email FROM bdc_judges WHERE status='active' AND (full_name LIKE :q OR judge_code LIKE :prefix OR instagram LIKE :q) ORDER BY CASE WHEN full_name LIKE :prefix THEN 0 ELSE 1 END,full_name LIMIT ".max(1,min(30,$limit)));$s->execute(['q'=>'%'.$term.'%','prefix'=>$term.'%']);return $s->fetchAll();}
 public static function findOrCreate(PDO $pdo,string $name,array $meta=[]):array{self::ensure($pdo);$name=trim($name);if($name==='')throw new \RuntimeException('Judge name is required.');$s=$pdo->prepare("SELECT * FROM bdc_judges WHERE LOWER(full_name)=LOWER(:n) AND status='active' ORDER BY id LIMIT 1");$s->execute(['n'=>$name]);if($j=$s->fetch())return $j;$pdo->prepare("INSERT INTO bdc_judges(full_name,country,country_code,photo_url,instagram,email,status) VALUES(:n,:country,:code,:photo,:ig,:email,'active')")->execute(['n'=>$name,'country'=>trim((string)($meta['country']??''))?:null,'code'=>CountryFlagService::code($meta['country_code']??$meta['country']??null),'photo'=>trim((string)($meta['photo_url']??''))?:null,'ig'=>trim((string)($meta['instagram']??''))?:null,'email'=>trim((string)($meta['email']??''))?:null]);$id=(int)$pdo->lastInsertId();$code='JDG-'.str_pad((string)$id,6,'0',STR_PAD_LEFT);$pdo->prepare('UPDATE bdc_judges SET judge_code=:c WHERE id=:id')->execute(['c'=>$code,'id'=>$id]);$s=$pdo->prepare('SELECT * FROM bdc_judges WHERE id=:id');$s->execute(['id'=>$id]);return $s->fetch();}
 public static function backfillAssignments(PDO $pdo):void{self::ensure($pdo);foreach(['bdc_scoring_judges','bdc_test_scoring_judges'] as $table){try{$rows=$pdo->query("SELECT id,judge_name FROM {$table} WHERE judge_id IS NULL AND judge_name<>''")->fetchAll();foreach($rows as $r){$j=self::findOrCreate($pdo,(string)$r['judge_name']);$pdo->prepare("UPDATE {$table} SET judge_id=:j WHERE id=:id")->execute(['j'=>$j['id'],'id'=>$r['id']]);}}catch(\Throwable){}}}
}