<?php
declare(strict_types=1);
namespace App\Services;
use PDO;
final class ProjectionSettingsService{
 public static function ensure(PDO $pdo):void{$pdo->exec("CREATE TABLE IF NOT EXISTS bdc_projection_settings(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,round_id BIGINT UNSIGNED NOT NULL,data_mode ENUM('real','test') NOT NULL DEFAULT 'real',screen_format VARCHAR(20) NOT NULL DEFAULT '16:9',density VARCHAR(20) NOT NULL DEFAULT 'maximum',custom_width INT UNSIGNED NULL,custom_height INT UNSIGNED NULL,updated_by BIGINT UNSIGNED NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE INDEX uq_projection_round_mode(round_id,data_mode)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
 public static function get(PDO $pdo,int $roundId,bool $test):array{self::ensure($pdo);$s=$pdo->prepare('SELECT screen_format,density,custom_width,custom_height FROM bdc_projection_settings WHERE round_id=:r AND data_mode=:m LIMIT 1');$s->execute(['r'=>$roundId,'m'=>$test?'test':'real']);return $s->fetch()?:['screen_format'=>'16:9','density'=>'maximum','custom_width'=>null,'custom_height'=>null];}
 public static function save(PDO $pdo,int $roundId,bool $test,array $v,int $userId):array{$formats=array_merge(array_keys(ProjectionLayoutService::PRESETS),['custom']);$format=in_array((string)($v['screen_format']??''),$formats,true)?(string)$v['screen_format']:'16:9';$density=in_array((string)($v['density']??''),['maximum','auto','large'],true)?(string)$v['density']:'maximum';$w=max(0,(int)($v['custom_width']??0));$h=max(0,(int)($v['custom_height']??0));if($format==='custom'&&($w<100||$h<100))throw new \RuntimeException('Custom screen requires width and height of at least 100 pixels.');self::ensure($pdo);$pdo->prepare("INSERT INTO bdc_projection_settings(round_id,data_mode,screen_format,density,custom_width,custom_height,updated_by) VALUES(:r,:m,:f,:d,:w,:h,:u) ON DUPLICATE KEY UPDATE screen_format=VALUES(screen_format),density=VALUES(density),custom_width=VALUES(custom_width),custom_height=VALUES(custom_height),updated_by=VALUES(updated_by),updated_at=NOW()")->execute(['r'=>$roundId,'m'=>$test?'test':'real','f'=>$format,'d'=>$density,'w'=>$w?:null,'h'=>$h?:null,'u'=>$userId?:null]);return self::get($pdo,$roundId,$test);}
 public static function reset(PDO $pdo,int $roundId,bool $test,int $userId):array{return self::save($pdo,$roundId,$test,['screen_format'=>'16:9','density'=>'maximum'], $userId);}
}