<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Config;use PDO;use RuntimeException;
final class RandomPairingService{
 public static function ensure(PDO $p):void{$p->exec("CREATE TABLE IF NOT EXISTS bdc_pairing_presenter_links(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,round_id BIGINT UNSIGNED NOT NULL,data_mode ENUM('real','test') NOT NULL,token_hash CHAR(64) NOT NULL,token_value CHAR(48) NULL,status ENUM('active','used','revoked','expired') NOT NULL DEFAULT 'active',expires_at DATETIME NOT NULL,created_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,used_at DATETIME NULL,UNIQUE INDEX uq_pairing_link_round_mode(round_id,data_mode),UNIQUE INDEX uq_pairing_link_token(token_hash)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$p->exec("CREATE TABLE IF NOT EXISTS bdc_pairing_random_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,round_id BIGINT UNSIGNED NOT NULL,data_mode ENUM('real','test') NOT NULL,algorithm VARCHAR(80) NOT NULL,leader_count INT UNSIGNED NOT NULL,follower_count INT UNSIGNED NOT NULL,pairing_hash CHAR(64) NOT NULL,pairing_json LONGTEXT NOT NULL,generated_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_pairing_audit_round(round_id,data_mode,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
 public static function generateLink(PDO $p,int $round,bool $test,int $user):string{self::ensure($p);self::assertFinal($p,$round,$test);$token=bin2hex(random_bytes(24));$p->prepare("INSERT INTO bdc_pairing_presenter_links(round_id,data_mode,token_hash,token_value,status,expires_at,created_by) VALUES(:r,:m,:h,:t,'active',DATE_ADD(NOW(),INTERVAL 12 HOUR),:u) ON DUPLICATE KEY UPDATE token_hash=VALUES(token_hash),token_value=VALUES(token_value),status='active',expires_at=VALUES(expires_at),created_by=VALUES(created_by),created_at=NOW(),used_at=NULL")->execute(['r'=>$round,'m'=>$test?'test':'real','h'=>hash('sha256',$token),'t'=>$token,'u'=>$user?:null]);return $token;}
 public static function activeLink(PDO $p,int $round,bool $test):?array{self::ensure($p);$s=$p->prepare("SELECT token_value,expires_at FROM bdc_pairing_presenter_links WHERE round_id=:r AND data_mode=:m AND status='active' AND expires_at>NOW() LIMIT 1");$s->execute(['r'=>$round,'m'=>$test?'test':'real']);$row=$s->fetch();if(!$row||empty($row['token_value']))return null;$row['url']=self::url((string)$row['token_value']);return $row;}
 public static function byToken(PDO $p,string $token):?array{self::ensure($p);if(!preg_match('/^[a-f0-9]{48}$/',$token))return null;$s=$p->prepare("SELECT * FROM bdc_pairing_presenter_links WHERE token_hash=:h AND status='active' AND expires_at>NOW() LIMIT 1");$s->execute(['h'=>hash('sha256',$token)]);return $s->fetch()?:null;}
 public static function url(string $token):string{$path=url('pairing-presenter/?token='.rawurlencode($token));$app=rtrim((string)Config::get('app.url',''),'/');if(!$app)return $path;$u=parse_url($app);return is_array($u)&&isset($u['scheme'],$u['host'])?$u['scheme'].'://'.$u['host'].(isset($u['port'])?':'.(int)$u['port']:'').$path:$path;}
 public static function randomize(PDO $p,int $round,bool $test,?int $user=null):array{self::ensure($p);self::assertFinal($p,$round,$test);$pre=$test?'bdc_test_':'bdc_';$q=$p->prepare("SELECT id,bib_number,display_name FROM {$pre}scoring_entries WHERE round_id=:r AND dance_role='leader' AND entry_status='active' ORDER BY bib_number,id");$q->execute(['r'=>$round]);$leaders=$q->fetchAll();$q=$p->prepare("SELECT id,bib_number,display_name FROM {$pre}scoring_entries WHERE round_id=:r AND dance_role='follower' AND entry_status='active' ORDER BY bib_number,id");$q->execute(['r'=>$round]);$followers=$q->fetchAll();if(!$leaders||!$followers)throw new RuntimeException('Final Leaders and Followers are required before matching.');if(count($leaders)!==count($followers))throw new RuntimeException('Random Match requires equal finalist counts. Current Final: '.count($leaders).' Leaders and '.count($followers).' Followers.');self::secureShuffle($followers);$pairs=[];foreach($leaders as $i=>$l)$pairs[]=['number'=>$i+1,'leader'=>$l,'follower'=>$followers[$i]];$p->beginTransaction();try{$p->prepare("DELETE FROM {$pre}scoring_final_pairs WHERE round_id=:r")->execute(['r'=>$round]);$in=$p->prepare("INSERT INTO {$pre}scoring_final_pairs(round_id,pair_number,leader_entry_id,follower_entry_id,pairing_status,created_by) VALUES(:r,:n,:l,:f,'draft',:u)");foreach($pairs as $x)$in->execute(['r'=>$round,'n'=>$x['number'],'l'=>$x['leader']['id'],'f'=>$x['follower']['id'],'u'=>$user]);$json=json_encode($pairs,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$hash=hash('sha256',$json);$p->prepare("INSERT INTO bdc_pairing_random_audit(round_id,data_mode,algorithm,leader_count,follower_count,pairing_hash,pairing_json,generated_by) VALUES(:r,:m,'secure_fisher_yates_random_int_v1',:lc,:fc,:h,:j,:u)")->execute(['r'=>$round,'m'=>$test?'test':'real','lc'=>count($leaders),'fc'=>count($followers),'h'=>$hash,'j'=>$json,'u'=>$user]);$p->commit();return ['pairs'=>$pairs,'hash'=>$hash,'algorithm'=>'Secure Fisher–Yates (random_int)'];}catch(\Throwable $e){if($p->inTransaction())$p->rollBack();throw $e;}}
 public static function confirm(PDO $p,int $round,bool $test):void{self::ensure($p);$pre=$test?'bdc_test_':'bdc_';$q=$p->prepare("SELECT COUNT(*) FROM {$pre}scoring_final_pairs WHERE round_id=:r AND follower_entry_id IS NULL");$q->execute(['r'=>$round]);if((int)$q->fetchColumn())throw new RuntimeException('Every Leader must have a Follower before confirmation.');$p->prepare("UPDATE {$pre}scoring_final_pairs SET pairing_status='confirmed' WHERE round_id=:r")->execute(['r'=>$round]);$p->prepare("UPDATE bdc_pairing_presenter_links SET status='used',used_at=NOW() WHERE round_id=:r AND data_mode=:m")->execute(['r'=>$round,'m'=>$test?'test':'real']);}
 private static function secureShuffle(array &$a):void{for($i=count($a)-1;$i>0;$i--){$j=random_int(0,$i);[$a[$i],$a[$j]]=[$a[$j],$a[$i]];}}
 private static function assertFinal(PDO $p,int $r,bool $t):void{$table=$t?'bdc_test_scoring_rounds':'bdc_scoring_rounds';$s=$p->prepare("SELECT round_type FROM {$table} WHERE id=:r");$s->execute(['r'=>$r]);if($s->fetchColumn()!=='final')throw new RuntimeException('Random matching is available only for a Final round.');}
}
