<?php
declare(strict_types=1);
namespace App\Services;
use PDO;use RuntimeException;use Throwable;
final class ScoringDraftEditorService{
 public static function load(PDO $pdo,int $roundId,bool $test=false):array{$p=$test?'bdc_test_':'bdc_';$s=$pdo->prepare("SELECT r.*,e.name event_name,e.event_date FROM {$p}scoring_rounds r JOIN {$p}events e ON e.id=r.event_id WHERE r.id=:id LIMIT 1");$s->execute(['id'=>$roundId]);$round=$s->fetch();if(!$round)throw new RuntimeException('Draft scoring round not found.');return$round;}
 public static function hasScoring(PDO $pdo,int $roundId,bool $test=false):bool{$p=$test?'bdc_test_':'bdc_';foreach(["{$p}scoring_marks","{$p}scoring_final_marks"] as $table){$s=$pdo->prepare("SELECT COUNT(*) FROM {$table} WHERE round_id=:round");$s->execute(['round'=>$roundId]);if((int)$s->fetchColumn()>0)return true;}return false;}
 public static function update(PDO $pdo,int $roundId,array $input,bool $test=false):void{
  $round=self::load($pdo,$roundId,$test);if(!in_array((string)$round['status'],['draft','discarded'],true))throw new RuntimeException('Only an unscored Draft can be edited.');if(self::hasScoring($pdo,$roundId,$test))throw new RuntimeException('Draft details are locked because judge scoring has started.');
  $name=trim((string)($input['event_name']??''));$date=trim((string)($input['event_date']??''));$dance=(string)($input['dance_style']??'bachata');$division=(string)($input['division']??'novice');if($name==='')throw new RuntimeException('Event name is required.');if($date!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))throw new RuntimeException('Enter a valid event date.');if(!in_array($dance,['bachata','salsa'],true))throw new RuntimeException('Invalid dance style.');$allowed=$dance==='salsa'?['novice','intermediate','advanced','salsa_rising','salsa_open']:['novice','intermediate','advanced','all_star','bachata_rising','bachata_open','bachata_invitational'];if(!in_array($division,$allowed,true))throw new RuntimeException('The selected division does not belong to '.ucfirst($dance).'.');
  $p=$test?'bdc_test_':'bdc_';$duplicate=$pdo->prepare("SELECT id FROM {$p}scoring_rounds WHERE event_id=:event AND dance_style=:dance AND division=:division AND round_type=:type AND scoring_mode=:mode AND status<>'archived' AND id<>:id LIMIT 1");$duplicate->execute(['event'=>$round['event_id'],'dance'=>$dance,'division'=>$division,'type'=>$round['round_type'],'mode'=>$round['scoring_mode']??'manual','id'=>$roundId]);if($duplicate->fetchColumn())throw new RuntimeException('This Event + Dance + Division scoring round already exists.');
  if($name!==(string)$round['event_name']||$date!==(string)($round['event_date']??'')){$eventScoring=$pdo->prepare("SELECT (SELECT COUNT(*) FROM {$p}scoring_marks m JOIN {$p}scoring_rounds r ON r.id=m.round_id WHERE r.event_id=:event1)+(SELECT COUNT(*) FROM {$p}scoring_final_marks fm JOIN {$p}scoring_rounds fr ON fr.id=fm.round_id WHERE fr.event_id=:event2)");$eventScoring->execute(['event1'=>$round['event_id'],'event2'=>$round['event_id']]);if((int)$eventScoring->fetchColumn()>0)throw new RuntimeException('Event name and date are locked because another round in this event has scoring.');}
  $pdo->beginTransaction();try{$pdo->prepare("UPDATE {$p}events SET name=:name,normalised_name=:normalised,event_date=NULLIF(:date,'') WHERE id=:id")->execute(['name'=>$name,'normalised'=>mb_strtolower($name),'date'=>$date,'id'=>$round['event_id']]);$pdo->prepare("UPDATE {$p}scoring_rounds SET dance_style=:dance,division=:division,updated_at=NOW() WHERE id=:id")->execute(['dance'=>$dance,'division'=>$division,'id'=>$roundId]);if(!$test){foreach(['bdc_registration_desk_links','bdc_registration_desk_activity'] as $table){try{$pdo->prepare("UPDATE {$table} SET dance_style=:dance,division=:division WHERE event_id=:event AND dance_style=:old_dance AND division=:old_division")->execute(['dance'=>$dance,'division'=>$division,'event'=>$round['event_id'],'old_dance'=>$round['dance_style']??'bachata','old_division'=>$round['division']]);}catch(Throwable $e){if(str_contains($e->getMessage(),'Duplicate'))throw new RuntimeException('A Registration Desk link already exists for the selected Dance + Division.');throw$e;}}}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
 }
}
