<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use App\Core\Database;
use App\Services\MobileProjectionRemoteService;
use App\Services\ScoringFlightService;
$pdo=Database::connection();$token=trim((string)($_GET['token']??$_POST['token']??''));$link=MobileProjectionRemoteService::byToken($pdo,$token);if(!$link){http_response_code(403);exit('This Mobile Projection Remote is invalid or expired.');}
$json=static function(array $payload,int $status=200):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);exit;};
$sessionPayload=static fn(array $session):array=>['screen_type'=>$session['screen_type']??'holding','page_number'=>(int)($session['page_number']??1),'auto_page'=>(bool)($session['auto_page']??false),'page_delay_seconds'=>(int)($session['page_delay_seconds']??15),'effect_type'=>$session['effect_type']??null,'state_version'=>(int)($session['state_version']??0)];
try{
    if($_SERVER['REQUEST_METHOD']==='POST'){$session=MobileProjectionRemoteService::command($pdo,$link,(string)($_POST['action']??''),$_POST);$json(['ok'=>true,'session'=>$sessionPayload($session)]);}
    $state=MobileProjectionRemoteService::state($pdo,$link);
    if(($_GET['format']??'')==='json'){$json(['ok'=>true,'session'=>$sessionPayload($state['session']),'round'=>$state['round'],'judges'=>$state['judges']??[]]);}
}catch(Throwable $e){if($_SERVER['REQUEST_METHOD']==='POST'||($_GET['format']??'')==='json')$json(['ok'=>false,'error'=>$e->getMessage()],422);$error=$e->getMessage();$state=['session'=>[],'round'=>null,'judges'=>[]];}
$test=$link['data_mode']==='test';$eventTable=$test?'bdc_test_events':'bdc_events';$q=$pdo->prepare("SELECT name FROM {$eventTable} WHERE id=:e");$q->execute(['e'=>(int)$link['event_id']]);$eventName=(string)($q->fetchColumn()?:'BDC Event');$session=$state['session'];$round=$state['round'];$judgeOptions=$state['judges']??[];$screens=$round?MobileProjectionRemoteService::safeScreens((string)$round['round_type']):[];unset($screens['flights'],$screens['judge_call']);$flightButtons=[];
if($round){try{$flightSummary=ScoringFlightService::summary($pdo,(int)$round['id'],$test);foreach(($flightSummary['flights']??[]) as $flight){$flightNumber=(int)($flight['number']??0);if($flightNumber>0)$flightButtons[$flightNumber]='Flight Round '.$flightNumber;}}catch(Throwable){$flightButtons=[];}}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Mobile Projection Remote</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#07101f;color:#f8fafc;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.wrap{max-width:620px;margin:auto;padding:18px 14px calc(28px + env(safe-area-inset-bottom))}.eyebrow{color:#fb7185;font-size:.78rem;font-weight:900;letter-spacing:.1em}.head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.status{background:#122037;border:1px solid #29405f;border-radius:14px;padding:12px;margin:14px 0}.status strong{display:block;font-size:1.05rem}.muted{color:#9fb0c7;font-size:.84rem}.card{background:#101b2e;border:1px solid #243854;border-radius:18px;padding:14px;margin-top:12px;box-shadow:0 12px 35px rgba(0,0,0,.2)}h1{font-size:1.55rem;margin:.25rem 0}h2{font-size:1rem;margin:0 0 10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}button{min-height:54px;border:1px solid #385373;border-radius:13px;background:#172943;color:#fff;font-weight:800;font-size:.95rem;padding:10px;touch-action:manipulation}button:active{transform:scale(.98)}button.active{background:#dc3545;border-color:#ff6572}button:disabled{opacity:.5}.effects button{font-size:.88rem}.wide{grid-column:1/-1}.page{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:9px}.page b{text-align:center;font-size:1.2rem}.judge-call{border:2px solid #dc3545;background:linear-gradient(145deg,#172943,#281529);box-shadow:0 0 0 3px rgba(220,53,69,.12),0 12px 35px rgba(0,0,0,.28)}.judge-call h2{font-size:1.28rem;color:#fff}.judge-call select,.paging-delay select{width:100%;min-height:60px;margin:8px 0 10px;border:2px solid #4d6e96;border-radius:13px;background-color:#07101f!important;color:#fff!important;-webkit-text-fill-color:#fff;padding:10px 12px;font-size:1.05rem;font-weight:800;color-scheme:dark}.judge-call select option{background-color:#07101f!important;color:#fff!important;-webkit-text-fill-color:#fff}.paging-delay select option{background-color:#07101f!important;color:#fff!important;-webkit-text-fill-color:#fff}.judge-call button{width:100%;min-height:64px;background:#dc3545;border-color:#ff6572;font-size:1.08rem}.paging-delay{margin-top:12px}.paging-delay label{display:block;font-weight:900}.success{color:#6ee7a5}.error{color:#fda4af}.test{background:#fbbf24;color:#111827;padding:5px 8px;border-radius:99px;font-size:.72rem;font-weight:900}.busy{opacity:.55;pointer-events:none}@media(min-width:480px){.grid.screens{grid-template-columns:repeat(3,1fr)}}
</style></head><body><main class="wrap" id="app">
<div class="head"><div><div class="eyebrow"><?=$test?'TEST · ':''?>MOBILE PROJECTION REMOTE</div><h1><?=e($eventName)?></h1><div class="muted"><?=$round?e(ucwords(str_replace('_',' ',(string)$round['division'])).' · '.ucfirst((string)$round['round_type'])):'Waiting for active round'?></div></div><?php if($test):?><span class="test">TEST</span><?php endif;?></div>
<?php if(!empty($error)):?><div class="status error"><?=e($error)?></div><?php else:?><div class="status"><strong id="liveState">LIVE: <?=e(strtoupper((string)($session['screen_type']??'holding')))?></strong><span class="muted" id="message">Connected to the event projector.</span></div><?php endif;?>
<?php if($round):?>
<section class="card judge-call" id="judgeCallPanel"><h2>Call a Specific Judge</h2><div class="muted">Choose any assigned judge, then send that judge to the projector.</div><select id="judgeSelect" aria-label="Select assigned judge" <?=$judgeOptions?'':'disabled'?>><?php if(!$judgeOptions):?><option>No assigned judges</option><?php endif;?><?php foreach($judgeOptions as $judge):?><option value="<?=(int)$judge['page']?>" <?=($session['screen_type']??'')==='judge_call'&&(int)($session['page_number']??1)===(int)$judge['page']?'selected':''?>>J<?=(int)$judge['judge_order']?> · <?=e((string)$judge['judge_name'])?><?=!empty($judge['is_chief'])?' · Chief':''?> · <?=e((string)$judge['scope_label'])?></option><?php endforeach;?></select><button type="button" data-action="call_judge" <?=$judgeOptions?'':'disabled'?>>Call Selected Judge</button></section>
<section class="card"><h2>Projector Screen</h2><div class="grid screens"><?php foreach($flightButtons as $flightNumber=>$flightLabel):?><button type="button" data-action="screen" data-screen="flights" data-page="<?=$flightNumber?>" class="<?=($session['screen_type']??'')==='flights'&&(int)($session['page_number']??1)===$flightNumber?'active':''?>"><?=e($flightLabel)?></button><?php endforeach;?><?php foreach($screens as $value=>$label):?><button type="button" data-action="screen" data-screen="<?=e($value)?>" class="<?=($session['screen_type']??'holding')===$value?'active':''?>"><?=e($label)?></button><?php endforeach;?></div></section>
<section class="card"><h2>Page / Judge Call</h2><div class="page"><button type="button" data-action="previous_page">← Previous</button><b id="pageNumber"><?=(int)($session['page_number']??1)?></b><button type="button" data-action="next_page">Next →</button></div><div class="grid"><button type="button" data-action="auto_on" id="autoOn" class="<?=!empty($session['auto_page'])?'active':''?>">Auto Page On</button><button type="button" data-action="auto_off" id="autoOff" class="<?=empty($session['auto_page'])?'active':''?>">Auto Page Off</button></div><div class="paging-delay"><label for="pageDelay">Automatic Page Delay</label><div class="muted">Competitor pages default to 15 seconds.</div><select id="pageDelay"><?php foreach([5,10,15,20,30,45,60] as $delay):?><option value="<?=$delay?>" <?=(int)($session['page_delay_seconds']??15)===$delay?'selected':''?>><?=$delay?> seconds</option><?php endforeach;?></select><button type="button" data-action="set_page_delay" class="wide">Save Page Delay</button></div></section>
<section class="card"><h2>Presentation Effects</h2><div class="grid effects"><button type="button" data-action="effect" data-effect="countdown" class="wide">5 · 4 · 3 · 2 · 1 Countdown</button><button type="button" data-action="effect" data-effect="hearts">💖 Hearts</button><button type="button" data-action="effect" data-effect="balloons">🎈 Balloons</button><button type="button" data-action="effect" data-effect="heart_smiles">🥰 Smiling Hearts</button><button type="button" data-action="effect" data-effect="finger_hearts">🫰 Korean Finger Hearts</button><button type="button" data-action="effect" data-effect="none" class="wide">Clear Effect</button></div></section>
<?php endif;?></main><script>
(()=>{'use strict';const token=<?=json_encode($token)?>,app=document.getElementById('app'),message=document.getElementById('message'),judgeSelect=document.getElementById('judgeSelect'),pageDelay=document.getElementById('pageDelay');function paint(s){document.getElementById('liveState').textContent='LIVE: '+String(s.screen_type||'holding').toUpperCase();document.getElementById('pageNumber').textContent=String(s.page_number||1);document.querySelectorAll('[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===s.screen_type&&(!b.dataset.page||Number(b.dataset.page)===Number(s.page_number||1))));document.getElementById('autoOn').classList.toggle('active',!!s.auto_page);document.getElementById('autoOff').classList.toggle('active',!s.auto_page);if(pageDelay&&s.page_delay_seconds)pageDelay.value=String(s.page_delay_seconds);if(judgeSelect&&s.screen_type==='judge_call')judgeSelect.value=String(s.page_number||1)}async function command(button){app.classList.add('busy');if(message)message.textContent='Sending command…';try{const action=button.dataset.action,body=new URLSearchParams({token,action:action==='call_judge'?'screen':action});if(action==='call_judge'){body.set('screen_type','judge_call');body.set('page_number',judgeSelect.value)}if(action==='set_page_delay')body.set('page_delay_seconds',pageDelay.value);if(button.dataset.screen)body.set('screen_type',button.dataset.screen);if(button.dataset.page)body.set('page_number',button.dataset.page);if(button.dataset.effect)body.set('effect_type',button.dataset.effect);const r=await fetch('',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','Accept':'application/json'},cache:'no-store',body:body.toString()}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Command failed');paint(j.session);if(message){message.className='muted success';message.textContent=button.dataset.screen==='callbacks'?'Countdown started; callbacks appear automatically.':action==='call_judge'?'Selected judge is now on the projector.':action==='set_page_delay'?'Automatic page delay saved at '+pageDelay.value+' seconds.':'Projector updated.'}}catch(e){if(message){message.className='muted error';message.textContent=e.message}}finally{app.classList.remove('busy')}}document.querySelectorAll('button[data-action]').forEach(b=>b.addEventListener('click',()=>command(b)));setInterval(async()=>{if(document.hidden)return;try{const r=await fetch('?token='+encodeURIComponent(token)+'&format=json&_='+Date.now(),{cache:'no-store'}),j=await r.json();if(j.ok)paint(j.session)}catch(e){}},3000)})();
</script></body></html>
