<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use App\Core\Csrf;use App\Core\Database;use App\Services\SchemaUpdater;
$pdo=Database::connection();SchemaUpdater::run($pdo);$mode=($_GET['mode']??$_POST['mode']??'new')==='update'?'update':'new';$error='';$success='';$matches=[];
$q=trim((string)($_GET['q']??''));
if($mode==='update'&&$q!==''){$n=mb_strtolower(trim(preg_replace('/[^\pL\pN]+/u',' ',$q)??$q));$s=$pdo->prepare("SELECT id,bdc_id,exact_name,country,current_division,dance_role,photo_url FROM bdc_competitors WHERE exact_name LIKE :q OR normalised_name LIKE :n OR bdc_id=:id OR instagram=:ig ORDER BY exact_name LIMIT 20");$s->execute(['q'=>'%'.$q.'%','n'=>'%'.$n.'%','id'=>$q,'ig'=>ltrim($q,'@')]);$matches=$s->fetchAll();}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Csrf::verify($_POST['_csrf']??null))$error='Invalid security token. Please refresh and try again.';
 else{
  $name=trim((string)($_POST['full_name']??''));$email=strtolower(trim((string)($_POST['email']??'')));$cid=(int)($_POST['competitor_id']??0);
  if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL))$error='Full name and a valid email are required.';
  elseif($mode==='update'&&$cid<1)$error='Please select your existing BDC profile.';
  else{
   $photo=null;
   if(!empty($_FILES['photo']['tmp_name'])){$f=$_FILES['photo'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$allow=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($allow[$mime])||$f['size']>5*1024*1024)$error='Photo must be JPG, PNG or WebP and under 5 MB.';else{$fn='request-'.bin2hex(random_bytes(8)).'.'.$allow[$mime];$dest=dirname(__DIR__).'/uploads/competitors/'.$fn;if(!move_uploaded_file($f['tmp_name'],$dest))$error='Photo upload failed.';else$photo=url('uploads/competitors/'.$fn);}}
   if($error===''){$type=$mode==='update'?'profile_update':'new_registration';$s=$pdo->prepare("INSERT INTO bdc_profile_requests(request_type,competitor_id,full_name,email,phone,instagram,country,dance_role,current_division,photo_url,notes,payload_json,status) VALUES(:t,:cid,:n,:e,:p,:ig,:c,:r,:d,:photo,:notes,:payload,'pending')");$payload=json_encode(['submitted_ip'=>$_SERVER['REMOTE_ADDR']??null],JSON_UNESCAPED_UNICODE);$s->execute(['t'=>$type,'cid'=>$cid?:null,'n'=>$name,'e'=>$email,'p'=>trim((string)($_POST['phone']??''))?:null,'ig'=>ltrim(trim((string)($_POST['instagram']??'')),'@')?:null,'c'=>trim((string)($_POST['country']??''))?:null,'r'=>$_POST['dance_role']??'unknown','d'=>$_POST['current_division']??'unknown','photo'=>$photo,'notes'=>trim((string)($_POST['notes']??''))?:null,'payload'=>$payload]);$success=$mode==='update'?'Your profile update request was submitted for admin approval.':'Your registration was submitted for admin approval.';}
  }
 }
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BDC Competitor Registration</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="<?=e(url('public/assets/css/app.css'))?>" rel="stylesheet"></head><body class="bg-light">
<a href="https://bachatadancecouncil.com/" class="bdc-global-home-link" style="position:fixed;top:12px;right:12px;z-index:1090;display:inline-flex;align-items:center;gap:.35rem;padding:.4rem .7rem;border:1px solid #d7a51f;border-radius:.4rem;background:#d9a928;color:#172033;font:600 14px/1.2 Arial,sans-serif;text-decoration:none;box-shadow:0 2px 8px rgba(0,0,0,.18)">🏠 BDC Home</a>
<nav class="navbar navbar-dark bg-dark"><div class="container"><a class="navbar-brand" href="<?=e(url())?>">Bachata Dance Council</a><a class="btn btn-outline-light btn-sm" href="<?=e(url('results/'))?>">Results</a></div></nav><main class="container py-5" style="max-width:900px"><h1 class="mb-2">BDC Competitor Portal</h1><p class="text-muted">New registrations and profile changes become public only after admin approval.</p><div class="btn-group mb-4"><a class="btn <?=$mode==='new'?'btn-dark':'btn-outline-dark'?>" href="?mode=new">New competitor</a><a class="btn <?=$mode==='update'?'btn-dark':'btn-outline-dark'?>" href="?mode=update">Update existing profile</a></div>
<?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<?php if($mode==='update'):?><div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Find your existing profile</h2><form class="row g-2"><input type="hidden" name="mode" value="update"><div class="col-md-9"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Search exact name, BDC ID or Instagram"></div><div class="col-md-3 d-grid"><button class="btn btn-outline-dark">Search</button></div></form></div></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="card border-0 shadow-sm"><div class="card-body p-4"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="mode" value="<?=e($mode)?>">
<?php if($mode==='update'):?><label class="form-label fw-semibold">Select your BDC profile</label><div class="row g-2 mb-3"><?php foreach($matches as $m):?><div class="col-md-6"><label class="border rounded p-3 d-flex gap-3 align-items-center w-100 bg-white"><input class="form-check-input" type="radio" name="competitor_id" value="<?=$m['id']?>" required><img src="<?=e($m['photo_url']?:url('public/assets/img/default-competitor.svg'))?>" style="width:56px;height:56px;object-fit:cover;border-radius:8px"><span><strong><?=e($m['exact_name'])?></strong><br><small class="text-muted"><?=e($m['bdc_id'])?> · <?=e((string)$m['country'])?> · <?=e(ucfirst($m['current_division']))?></small></span></label></div><?php endforeach;?></div><?php if($q!==''&&!$matches):?><div class="alert alert-warning">No matching profile found. Check the spelling or register as a new competitor.</div><?php endif;?><?php endif;?>
<div class="row g-3"><div class="col-md-6"><label class="form-label">Full name *</label><input class="form-control" name="full_name" required></div><div class="col-md-6"><label class="form-label">Email *</label><input class="form-control" type="email" name="email" required></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" name="phone"></div><div class="col-md-6"><label class="form-label">Instagram</label><div class="input-group"><span class="input-group-text">@</span><input class="form-control" name="instagram"></div></div><div class="col-md-6"><label class="form-label">Country</label><input class="form-control" name="country"></div><div class="col-md-3"><label class="form-label">Role</label><select class="form-select" name="dance_role"><option value="unknown">Select</option><option value="leader">Lead</option><option value="follower">Follow</option><option value="both">Both</option></select></div><div class="col-md-3"><label class="form-label">Current division</label><select class="form-select" name="current_division"><option value="unknown">Select</option><option value="novice">Novice</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option><option value="all_star">All Star</option><option value="professional">Professional</option></select></div><div class="col-md-6"><label class="form-label">Profile photo</label><input class="form-control" type="file" name="photo" accept="image/jpeg,image/png,image/webp"><div class="form-text">JPG, PNG or WebP, maximum 5 MB.</div></div><div class="col-12"><label class="form-label">Notes for admin</label><textarea class="form-control" name="notes" rows="3"></textarea></div></div><div class="mt-4"><button class="btn btn-dark btn-lg"><?= $mode==='update'?'Submit update request':'Submit registration' ?></button></div></div></form></main></body></html>
