#!/usr/bin/env bash
set -euo pipefail
python3 <<'PY'
from pathlib import Path
import json,re
p=Path('judge-scoring/index.php')
s=p.read_text()
old='''<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><?php if($notice):?><div class="alert success"><?=e($notice)?></div><?php endif;?>
<button type="button" class="criteria-btn" onclick="document.getElementById('criteriaDialog').showModal()">View Criteria</button><dialog id="criteriaDialog" class="criteria-dialog"><h2>Judging Criteria</h2><ul><?php foreach(JudgingCriteriaService::weights() as [$name,$weight]):?><li><strong><?=e($name)?></strong>, <?=e($weight)?></li><?php endforeach;?></ul><?php if($isFinal):?><p>Rank your <strong>TOP <?=$finalRankLimit?></strong> best couples from 1 to <?=$finalRankLimit?>. Use each rank once. Leave all other couples as <strong>NO RANK</strong>.</p><?php else:?><h3><?=e($selectionRoundLabel)?> Instructions</h3><ul><?php $dialogScope=(string)$session['scoring_scope'];foreach(['leader'=>'Leaders','follower'=>'Followers'] as $dialogRole=>$dialogLabel):if(!in_array($dialogScope,['all',$dialogRole],true)||!$entries[$dialogRole])continue;$cfg=$roleTierConfig[$dialogRole];$places=$roleAltPlaces[$dialogRole];?><li><strong><?=e($dialogLabel)?> · Tier <?=(int)$cfg['tier']?> · <?=$allRoleCounts[$dialogRole]?> competitors:</strong> choose <strong><?=(int)$cfg['yes']?> YES</strong>. A1 = <strong><?=e($places['A1'])?> place</strong>, A2 = <strong><?=e($places['A2'])?> place</strong>, A3 = <strong><?=e($places['A3'])?> place</strong>.</li><?php endforeach;?><li>Mark everyone else <strong>NO</strong>.</li><li>Use the optional comment field for a private note.</li></ul><?php endif;?><p>Judge independently and keep all scoring confidential.</p><button type="button" class="criteria-btn" onclick="document.getElementById('criteriaDialog').close()">Close</button></dialog>'''
new='''<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><?php if($notice):?><div class="alert success"><?=e($notice)?></div><?php endif;?>
<button type="button" class="criteria-btn" onclick="document.getElementById('criteriaDialog').showModal()">View Criteria</button><dialog id="criteriaDialog" class="criteria-dialog"><h2>Judging Criteria</h2><ul><?php foreach(JudgingCriteriaService::weights() as [$name,$weight]):?><li><strong><?=e($name)?></strong>, <?=e($weight)?></li><?php endforeach;?></ul><?php if($isFinal):?><p>Rank your <strong>TOP <?=$finalRankLimit?></strong> best couples from 1 to <?=$finalRankLimit?>. Use each rank once. Leave all other couples as <strong>NO RANK</strong>.</p><?php else:?><h3><?=e($selectionRoundLabel)?> Instructions</h3><ul><?php $dialogScope=(string)$session['scoring_scope'];$dialogSeen=[];foreach(['leader','follower'] as $dialogRole):if(!in_array($dialogScope,['all',$dialogRole],true)||!$entries[$dialogRole])continue;$cfg=$roleTierConfig[$dialogRole];$places=$roleAltPlaces[$dialogRole];$key=$cfg['yes'].'|'.$places['A1'].'|'.$places['A2'].'|'.$places['A3'];if(isset($dialogSeen[$key]))continue;$dialogSeen[$key]=true;?><li>Choose <strong><?=(int)$cfg['yes']?> YES</strong> for your <strong>Top <?=(int)$cfg['yes']?> best dancers</strong>. A1 = <strong><?=e($places['A1'])?> place</strong>, A2 = <strong><?=e($places['A2'])?> place</strong>, A3 = <strong><?=e($places['A3'])?> place</strong>.</li><?php endforeach;?><li>Mark everyone else <strong>NO</strong>.</li><li>Comments are optional and private to this judge/device.</li></ul><?php endif;?><p>Judge independently and keep all scoring confidential.</p><button type="button" class="criteria-btn" onclick="document.getElementById('criteriaDialog').close()">Close</button></dialog>'''
if old not in s: raise SystemExit('criteria instruction anchor missing')
s=s.replace(old,new,1)
old='''<div class="alert success"><strong><?=e($selectionRoundLabel)?> Instructions</strong><ul style="margin:7px 0 0;padding-left:20px"><?php $sheetScope=(string)$session['scoring_scope'];foreach(['leader'=>'Leaders','follower'=>'Followers'] as $sheetRole=>$sheetLabel):if(!in_array($sheetScope,['all',$sheetRole],true)||!$entries[$sheetRole])continue;$cfg=$roleTierConfig[$sheetRole];$places=$roleAltPlaces[$sheetRole];?><li><strong><?=e($sheetLabel)?> · Tier <?=(int)$cfg['tier']?> · <?=$allRoleCounts[$sheetRole]?> competitors:</strong> Choose <strong><?=(int)$cfg['yes']?> YES</strong> for your <strong>Top <?=(int)$cfg['yes']?> best dancers</strong>. A1 = <strong><?=e($places['A1'])?> place</strong>, A2 = <strong><?=e($places['A2'])?> place</strong>, A3 = <strong><?=e($places['A3'])?> place</strong>.</li><?php endforeach;?><li>Mark everyone else <strong>NO</strong>.</li><li>Comments are optional and private to this judge/device.</li></ul></div>'''
new='''<div class="alert success"><strong><?=e($selectionRoundLabel)?> Instructions</strong><ul style="margin:7px 0 0;padding-left:20px"><?php $sheetScope=(string)$session['scoring_scope'];$sheetSeen=[];foreach(['leader','follower'] as $sheetRole):if(!in_array($sheetScope,['all',$sheetRole],true)||!$entries[$sheetRole])continue;$cfg=$roleTierConfig[$sheetRole];$places=$roleAltPlaces[$sheetRole];$key=$cfg['yes'].'|'.$places['A1'].'|'.$places['A2'].'|'.$places['A3'];if(isset($sheetSeen[$key]))continue;$sheetSeen[$key]=true;?><li>Choose <strong><?=(int)$cfg['yes']?> YES</strong> for your <strong>Top <?=(int)$cfg['yes']?> best dancers</strong>. A1 = <strong><?=e($places['A1'])?> place</strong>, A2 = <strong><?=e($places['A2'])?> place</strong>, A3 = <strong><?=e($places['A3'])?> place</strong>.</li><?php endforeach;?><li>Mark everyone else <strong>NO</strong>.</li><li>Comments are optional and private to this judge/device.</li></ul></div>'''
if old not in s: raise SystemExit('sheet instruction anchor missing')
s=s.replace(old,new,1)
# Judges should not see tier labels in counters or max-limit warnings either.
s=s.replace("const limit=Number(roleYesLimits[role]||0),tier=Number(roleTiers[role]||0);el.innerHTML='<span class=\"counter-item counter-yes\">'+(tier?'TIER '+tier+' · ':'')+'YES '+state.yes+' / '+limit+'", "const limit=Number(roleYesLimits[role]||0);el.innerHTML='<span class=\"counter-item counter-yes\">YES '+state.yes+' / '+limit+")
s=s.replace("+' (Tier '+roleTiers[role]+'). Clear or change another YES first.'", "+'. Clear or change another YES first.'")
p.write_text(s)

vp=Path('VERSION.json');data=json.loads(vp.read_text());data['version']='2.3.5-dev685';data['build']=3392;data['release_date']='2026-09-07';feature='Judge-facing Heats instructions are action-only: no Lead/Follow tier or competitor-count logic is exposed; identical role quotas are shown once, with YES and A1/A2/A3 places in bold, while saved role-specific validation remains unchanged.';data.setdefault('features',[]).insert(0,feature);vp.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
PY
php -l judge-scoring/index.php
python3 <<'PY'
from pathlib import Path
s=Path('judge-scoring/index.php').read_text()
assert 'Choose <strong><?=(int)$cfg[\'yes\']?> YES</strong> for your <strong>Top <?=(int)$cfg[\'yes\']?> best dancers</strong>' in s
assert '<?=e($sheetLabel)?> · Tier' not in s
assert '<?=e($dialogLabel)?> · Tier' not in s
assert "(tier?'TIER '" not in s
assert "(Tier '+roleTiers[role]" not in s
assert '$sheetSeen=[]' in s and '$dialogSeen=[]' in s
print('dev685 clean judge instruction assertions passed')
PY
git config user.name 'BDC Release Bot';git config user.email 'actions@users.noreply.github.com';git add judge-scoring/index.php VERSION.json;git commit -m 'Release dev685 clean judge heats instructions';git push origin HEAD:develop
