<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\CompetitorIdentityService;
Auth::requireSuperAdmin();$pdo=Database::connection();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Csrf::verify($_POST['_csrf']??null))$error='Invalid security token.';else{
  $id=(int)($_POST['id']??0);$action=(string)($_POST['action']??'');$s=$pdo->prepare("SELECT * FROM bdc_competitor_link_suggestions WHERE id=:id AND status='pending'");$s->execute(['id'=>$id]);$row=$s->fetch();
  if(!$row)$error='Suggestion is no longer pending.';elseif($action==='approve'){CompetitorIdentityService::link($pdo,(int)$row['competitor_a_id'],(int)$row['competitor_b_id']);$pdo->prepare("UPDATE bdc_competitor_link_suggestions SET status='approved',reviewed_by=:u,reviewed_at=NOW() WHERE id=:id")->execute(['u'=>Auth::user()['id'],'id'=>$id]);}elseif($action==='reject')$pdo->prepare("UPDATE bdc_competitor_link_suggestions SET status='rejected',reviewed_by=:u,reviewed_at=NOW() WHERE id=:id")->execute(['u'=>Auth::user()['id'],'id'=>$id]);
 }
}
$rows=$pdo->query("SELECT s.*,a.bdc_id a_bdc,a.exact_name a_name,a.dance_role a_role,a.current_division a_division,b.bdc_id b_bdc,b.exact_name b_name,b.dance_role b_role,b.current_division b_division FROM bdc_competitor_link_suggestions s JOIN bdc_competitors a ON a.id=s.competitor_a_id JOIN bdc_competitors b ON b.id=s.competitor_b_id WHERE s.status='pending' ORDER BY s.confidence DESC,s.created_at")->fetchAll();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Identity Match Review</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="../">Competitors</a></div></nav><main class="container py-4"><h1 class="h3">Shared-person match review</h1><p class="text-muted">Reliable email or multi-identifier matches are linked automatically. Only uncertain single-identifier matches appear here.</p><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Profile A</th><th>Profile B</th><th>Matched by</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=e($r['a_name'])?></strong><div class="small text-muted"><?=e($r['a_bdc'].' · '.$r['a_role'].' · '.$r['a_division'])?></div></td><td><strong><?=e($r['b_name'])?></strong><div class="small text-muted"><?=e($r['b_bdc'].' · '.$r['b_role'].' · '.$r['b_division'])?></div></td><td><?=e($r['match_reason'])?></td><td><form method="post" class="d-flex gap-2"><?=Csrf::field()?><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-success" name="action" value="approve">Link</button><button class="btn btn-sm btn-outline-danger" name="action" value="reject">Not same person</button></form></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="4" class="text-center text-muted py-5">No uncertain matches need review.</td></tr><?php endif;?></tbody></table></div></div></main></body></html>
