<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\SpecialCategoryRecoveryService;
Auth::requireSuperAdmin();$pdo=Database::connection();SpecialCategoryRecoveryService::ensureSchema($pdo);$auditPreview=SpecialCategoryRecoveryService::recoverManualAssignments($pdo,false);$backups=SpecialCategoryRecoveryService::availableBackups();$preview=null;$dataEntryPreview=null;$message='';$error='';$type='';$name='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Csrf::verify($_POST['_csrf']??null))$error='Invalid security token.';
 else try{
  $action=(string)($_POST['action']??'preview_backup');
  if($action==='preview_data_entry'){
   foreach(['amateur_csv','open_csv'] as $field){if(!isset($_FILES[$field])||!is_uploaded_file((string)$_FILES[$field]['tmp_name'])||(int)$_FILES[$field]['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Upload both official Google Forms CSV exports.');if((int)$_FILES[$field]['size']>5*1024*1024)throw new RuntimeException('Each data-entry CSV must be 5 MB or smaller.');}
   $manifest=SpecialCategoryRecoveryService::dataEntryManifest((string)$_FILES['amateur_csv']['tmp_name'],(string)$_FILES['open_csv']['tmp_name']);$_SESSION['special_category_data_entry_manifest']=$manifest;$dataEntryPreview=SpecialCategoryRecoveryService::previewDataEntryManifest($pdo,$manifest);
  }elseif($action==='restore_data_entry'){
   if(strtoupper(trim((string)($_POST['confirmation']??'')))!=='RESTORE DATA ENTRY CATEGORIES')throw new RuntimeException('Type RESTORE DATA ENTRY CATEGORIES to confirm.');$manifest=$_SESSION['special_category_data_entry_manifest']??[];if(!is_array($manifest)||$manifest===[])throw new RuntimeException('The data-entry preview expired. Upload both CSV exports again.');$result=SpecialCategoryRecoveryService::restoreDataEntryManifest($pdo,$manifest,(int)(Auth::user()['id']??0));Auth::audit((int)(Auth::user()['id']??0),'special_category_data_entry_recovery',$result,'competitor_recovery',null);$message=$result['restored'].' verified data-entry assignments restored. Safety backup: '.$result['safety_backup'].'.';$dataEntryPreview=SpecialCategoryRecoveryService::previewDataEntryManifest($pdo,$manifest);
  }else{
  $type=(string)($_POST['backup_type']??'');$name=(string)($_POST['backup_name']??'');$key=(string)($_POST['backup_key']??'');if(($type===''||$name==='')&&str_contains($key,'|'))[$type,$name]=explode('|',$key,2);
  if($action==='restore_backup'){
   if(strtoupper(trim((string)($_POST['confirmation']??'')))!=='RESTORE SPECIAL CATEGORIES')throw new RuntimeException('Type RESTORE SPECIAL CATEGORIES to confirm.');
   $result=SpecialCategoryRecoveryService::restoreFromBackup($pdo,$type,$name,(int)(Auth::user()['id']??0));Auth::audit((int)(Auth::user()['id']??0),'special_category_backup_recovery',$result,'competitor_recovery',null);$message=$result['restored'].' remaining Special Category assignments restored. Safety backup: '.$result['safety_backup'].'.';
  }
  $preview=SpecialCategoryRecoveryService::previewBackup($pdo,$type,$name);
  }
 }catch(Throwable $e){$error=$e->getMessage();}
}
$rows=$pdo->query("SELECT r.*,c.bdc_id,c.exact_name FROM bdc_special_category_recovery r JOIN bdc_competitors c ON c.id=r.competitor_id ORDER BY r.applied_at IS NULL,r.applied_at DESC,r.id DESC")->fetchAll();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Special Category Recovery</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="./">Competitors</a><a class="btn btn-outline-light btn-sm" href="../">Dashboard</a></div></nav><main class="container py-4" style="max-width:1300px"><span class="badge text-bg-danger">SUPER ADMIN · TARGETED RECOVERY</span><h1 class="h3 mt-2">Manual Special Category Recovery</h1><p class="text-muted">Restore only manually assigned Special Category fields. Never apply an old full database over current Production.</p>
<?php if($message):?><div class="alert alert-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="row g-3 mb-4"><div class="col"><div class="card"><div class="card-body">Recovered from audit<br><strong class="fs-3"><?=(int)$auditPreview['candidates']?></strong></div></div></div><div class="col"><div class="card"><div class="card-body">Recovery evidence rows<br><strong class="fs-3"><?=count($rows)?></strong></div></div></div><div class="col"><div class="card"><div class="card-body">Available DB backups<br><strong class="fs-3"><?=count($backups)?></strong></div></div></div></div>
<section class="card border-primary mb-4"><div class="card-body"><h2 class="h5">Official data-entry reconciliation</h2><p class="text-muted">Upload the untouched CSV exports from the Amateur and 4th Asia Open Google Forms. Open entries take precedence over Amateur entries for the same person and dance style. Exact-name and email matching is previewed before any database change.</p><form method="post" enctype="multipart/form-data" class="row g-3"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="preview_data_entry"><div class="col-lg-5"><label class="form-label">Amateur J&amp;J responses CSV</label><input class="form-control" type="file" name="amateur_csv" accept=".csv,text/csv" required></div><div class="col-lg-5"><label class="form-label">4th Asia Open responses CSV</label><input class="form-control" type="file" name="open_csv" accept=".csv,text/csv" required></div><div class="col-lg-2 d-flex align-items-end"><button class="btn btn-primary w-100">Compare Data Entry</button></div></form></div></section>
<?php if($dataEntryPreview):?><section class="card border-info mb-4"><div class="card-body"><h2 class="h5">Data-entry comparison</h2><div class="row g-2 mb-3"><?php foreach(['unique_people'=>'Unique people','assignments'=>'Style assignments','matched_people'=>'Matched people','recoverable'=>'Missing assignments','already_special'=>'Already special','unmatched'=>'Unmatched','conflicts'=>'Conflicts'] as $key=>$label):?><div class="col"><div class="alert alert-light border mb-0"><strong class="fs-4"><?=(int)$dataEntryPreview[$key]?></strong><br><small><?=e($label)?></small></div></div><?php endforeach;?></div>
<?php if($dataEntryPreview['recoverable']>0):?><form method="post" class="border border-danger rounded p-3 mb-3" onsubmit="return confirm('Restore only verified missing data-entry assignments? A fresh safety backup is created first.');"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="restore_data_entry"><div class="input-group"><input class="form-control" name="confirmation" required placeholder="Type RESTORE DATA ENTRY CATEGORIES"><button class="btn btn-danger">Restore <?=(int)$dataEntryPreview['recoverable']?> Verified Assignments</button></div></form><?php endif;?>
<div class="table-responsive" style="max-height:520px"><table class="table table-sm"><thead><tr><th>Submitted name</th><th>Matched competitor</th><th>Dance</th><th>Current</th><th>Expected</th><th>Source</th><th>Status</th></tr></thead><tbody><?php foreach($dataEntryPreview['candidates'] as $candidate):?><tr><td><?=e($candidate['name'])?></td><td><?=e(($candidate['bdc_id']??'').' '.($candidate['matched_name']??'—'))?></td><td><?=e(ucfirst($candidate['dance_style']))?></td><td><?=e(ucwords(str_replace('_',' ',$candidate['current_category']?:'—')))?></td><td><?=e(ucwords(str_replace('_',' ',$candidate['category'])))?></td><td><?=e(ucfirst($candidate['source']))?></td><td><?=e(ucwords(str_replace('_',' ',$candidate['status'])))?></td></tr><?php endforeach;?></tbody></table></div></div></section><?php endif;?>
<section class="card border-warning mb-4"><div class="card-body"><h2 class="h5">Recover remaining assignments from backup</h2><p class="text-muted">Choose the newest backup created before dev397. Preview first. Already-correct categories are skipped; only remaining lost Special Category values are restored.</p><?php if($backups):?><form method="post" class="row g-3"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="preview_backup"><div class="col-lg-9"><select class="form-select" name="backup_key" required><option value="">Select pre-dev397 backup</option><?php foreach($backups as $backup):?><option value="<?=e($backup['type'].'|'.$backup['name'])?>"><?=e(date('Y-m-d H:i:s',(int)$backup['created_at']).' · '.ucfirst($backup['type']).' · '.$backup['name'])?></option><?php endforeach;?></select></div><div class="col-lg-3"><button class="btn btn-warning w-100">Preview Backup</button></div></form><?php else:?><div class="alert alert-danger mb-0">No server database backups are available.</div><?php endif;?></div></section>
<?php if($preview):?><section class="card border-primary mb-4"><div class="card-body"><h2 class="h5">Backup preview: <?=e($preview['backup'])?></h2><div class="row g-3 mb-3"><div class="col"><div class="alert alert-light border"><strong><?=(int)$preview['total']?></strong><br>Total in backup</div></div><div class="col"><div class="alert alert-warning"><strong><?=(int)$preview['recoverable']?></strong><br>Remaining to restore</div></div><div class="col"><div class="alert alert-success"><strong><?=(int)$preview['already_special']?></strong><br>Already correct</div></div><div class="col"><div class="alert alert-danger"><strong><?=(int)$preview['missing']?></strong><br>Missing competitors</div></div></div>
<?php if($preview['recoverable']>0):?><form method="post" class="border border-danger rounded p-3 mb-3" onsubmit="return confirm('Restore only the remaining lost assignments? A fresh safety backup is created first.');"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="restore_backup"><input type="hidden" name="backup_type" value="<?=e($type)?>"><input type="hidden" name="backup_name" value="<?=e($name)?>"><div class="input-group"><input class="form-control" name="confirmation" required placeholder="Type RESTORE SPECIAL CATEGORIES"><button class="btn btn-danger">Restore <?=(int)$preview['recoverable']?> Remaining Assignments</button></div></form><?php else:?><div class="alert alert-success">No remaining lost assignments in this backup.</div><?php endif;?>
<div class="table-responsive" style="max-height:460px"><table class="table table-sm"><thead><tr><th>BDC ID</th><th>Competitor</th><th>Dance</th><th>Current</th><th>Backup</th><th>Status</th></tr></thead><tbody><?php foreach($preview['candidates'] as $candidate):?><tr><td><code><?=e($candidate['bdc_id']?:'Legacy #'.$candidate['backup_competitor_id'])?></code></td><td><?=e($candidate['exact_name'])?></td><td><?=e(ucfirst($candidate['dance_style']))?></td><td><?=e($candidate['current_category']?ucwords(str_replace('_',' ',$candidate['current_category'])):'—')?></td><td><?=e(ucwords(str_replace('_',' ',$candidate['category'])))?></td><td><?php if(!$candidate['competitor_id']):?><span class="badge text-bg-danger">Missing</span><?php elseif($candidate['needs_restore']):?><span class="badge text-bg-warning">Restore</span><?php else:?><span class="badge text-bg-success">Already correct · skipped</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></section><?php endif;?>
<section class="card"><div class="card-body"><h2 class="h5">Recovery history</h2><div class="table-responsive"><table class="table"><thead><tr><th>BDC ID</th><th>Competitor</th><th>Dance</th><th>Recovered category</th><th>Source</th><th>Applied</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><code><?=e($row['bdc_id'])?></code></td><td><?=e($row['exact_name'])?></td><td><?=e(ucfirst($row['dance_style']))?></td><td><?=e(ucwords(str_replace('_',' ',$row['recovered_category'])))?></td><td><?=e($row['source_kind']==='backup'?($row['source_name']?:'Backup'):'#'.(string)$row['audit_log_id'])?></td><td><?=e($row['applied_at']?:'Preview only')?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="6" class="text-center text-muted">No recovery records.</td></tr><?php endif;?></tbody></table></div></div></section></main></body></html>
