<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\SpecialCategoryReconciliationService;
Auth::requireSuperAdmin();$pdo=Database::connection();$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Csrf::verify($_POST['_csrf']??null))$error='Invalid security token.';
 else try{if(strtoupper(trim((string)($_POST['confirmation']??'')))!=='QUARANTINE TEST CATEGORIES')throw new RuntimeException('Type QUARANTINE TEST CATEGORIES to confirm.');$result=SpecialCategoryReconciliationService::quarantine($pdo,(array)($_POST['category_ids']??[]),(int)(Auth::user()['id']??0));Auth::audit((int)(Auth::user()['id']??0),'special_category_test_quarantine',$result,'competitor_reconciliation',null);$message=$result['quarantined'].' unsupported assignment(s) quarantined. Safety backup: '.$result['safety_backup'].'.';}catch(Throwable $e){$error=$e->getMessage();}
}
$preview=SpecialCategoryReconciliationService::preview($pdo);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Special Category Evidence Review</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><style>body{background:#eef2f8}.hero{background:linear-gradient(135deg,#10264a,#5f1737);color:#fff;border-radius:20px}.badge-keep{background:#198754}.badge-quarantine{background:#dc3545}.badge-review{background:#f0ad00;color:#1b2430}.table-wrap{max-height:65vh}.sticky-top{top:0}</style></head><body><main class="container-fluid py-4 px-lg-5"><section class="hero p-4 mb-4"><div class="d-flex flex-wrap justify-content-between gap-3"><div><span class="badge text-bg-warning">SUPER ADMIN · PREVIEW FIRST</span><h1 class="h3 mt-2 mb-1">Special Category Evidence Review</h1><p class="mb-0 opacity-75">Protect genuine manual and verified registrations. Quarantine only unsupported legacy Test contamination.</p></div><div><a class="btn btn-light" href="./">Back to Competitors</a></div></div></section>
<?php if($message):?><div class="alert alert-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<?php if(!$preview['evidence_available']):?><div class="alert alert-danger"><strong>Cleanup locked.</strong> Approved-result evidence could not be checked. Every unsupported row is held for review.</div><?php endif;?>
<div class="row g-3 mb-4"><?php foreach(['keep'=>['Protected','success'],'quarantine'=>['Quarantine candidates','danger'],'review'=>['Needs review','warning']] as $key=>$meta):?><div class="col-md-4"><div class="card border-<?=$meta[1]?> h-100"><div class="card-body"><div class="text-muted"><?=e($meta[0])?></div><strong class="display-6"><?=(int)$preview[$key]?></strong></div></div></div><?php endforeach;?></div>
<form method="post" onsubmit="return confirm('Create a safety backup and quarantine only the selected unsupported legacy assignments?');"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><div class="card shadow-sm"><div class="card-header bg-white d-flex flex-wrap justify-content-between gap-3 align-items-center"><div><strong>Assignment evidence</strong><div class="small text-muted">Protected and Review rows cannot be selected.</div></div><?php if($preview['quarantine']>0):?><div class="input-group" style="max-width:620px"><input class="form-control" name="confirmation" placeholder="Type QUARANTINE TEST CATEGORIES" required><button class="btn btn-danger">Backup and Quarantine Selected</button></div><?php endif;?></div><div class="table-responsive table-wrap"><table class="table table-hover align-middle mb-0"><thead class="table-light sticky-top"><tr><th></th><th>BDC ID</th><th>Competitor</th><th>Dance</th><th>Category</th><th>Stored source</th><th>Evidence decision</th></tr></thead><tbody><?php foreach($preview['rows'] as $row):?><tr><td><?php if($row['classification']==='quarantine'):?><input class="form-check-input" type="checkbox" name="category_ids[]" value="<?=(int)$row['id']?>"><?php endif;?></td><td><code><?=e($row['bdc_id'])?></code></td><td><strong><?=e($row['exact_name'])?></strong></td><td><?=e(ucfirst($row['dance_style']))?></td><td><?=e(ucwords(str_replace('_',' ',$row['category'])))?></td><td><?=e(ucwords(str_replace('_',' ',$row['source_kind'])))?><div class="small text-muted"><?=e((string)($row['source_name']??''))?></div></td><td><span class="badge badge-<?=e($row['classification'])?>"><?=e(ucfirst($row['classification']))?></span><div class="small mt-1"><?=e($row['reason'])?></div></td></tr><?php endforeach;?></tbody></table></div></div></form></main></body></html>
