<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Database;
Auth::requirePermission('competitors.edit');$pdo=Database::connection();
$status=(string)($_GET['status']??'pending_review');$allowed=['pending_review','failed','completed','duplicate','all'];if(!in_array($status,$allowed,true))$status='pending_review';
$where=$status==='all'?'':'WHERE s.status=:status';$stmt=$pdo->prepare("SELECT s.*,c.bdc_id,c.exact_name competitor_name FROM bdc_form_sync_submissions s LEFT JOIN bdc_competitors c ON c.id=s.competitor_id $where ORDER BY s.created_at DESC,s.id DESC LIMIT 500");$stmt->execute($status==='all'?[]:['status'=>$status]);$rows=$stmt->fetchAll();
function syncCandidates(PDO $pdo,?string $json):array{$ids=array_values(array_filter(array_map('intval',(array)json_decode((string)$json,true))));if(!$ids)return[];$marks=implode(',',array_fill(0,count($ids),'?'));$q=$pdo->prepare("SELECT id,bdc_id,exact_name,email,phone,instagram,country FROM bdc_competitors WHERE id IN($marks) ORDER BY exact_name,id");$q->execute($ids);return$q->fetchAll();}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Form Sync | BDC Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container"><a class="navbar-brand" href="<?=e(url('admin/'))?>">BDC Admin</a><a class="btn btn-outline-light btn-sm" href="<?=e(url('admin/competitors/'))?>">Competitors</a></div></nav><main class="container py-4"><div class="mb-4"><h1 class="h3 mb-1">Google Form Sync</h1><p class="text-muted mb-0">Completed imports, exact duplicates, ambiguous identities and failed rows.</p></div><div class="btn-group flex-wrap mb-4"><?php foreach(['pending_review'=>'Pending Review','failed'=>'Failed','completed'=>'Completed','duplicate'=>'Duplicates','all'=>'All'] as $key=>$label):?><a class="btn <?=$status===$key?'btn-dark':'btn-outline-dark'?>" href="?status=<?=e($key)?>"><?=e($label)?></a><?php endforeach;?></div><?php foreach($rows as $row):$candidates=syncCandidates($pdo,$row['candidate_ids_json']??null);?><section class="card border-0 shadow-sm mb-3"><div class="card-header bg-white d-flex justify-content-between gap-3"><div><strong><?=e($row['participant_name'])?></strong><div class="small text-muted"><?=e(ucfirst($row['form_kind']))?> form · row <?=e((string)($row['source_row']?:'—'))?> · <?=e($row['created_at'])?></div></div><span class="badge text-bg-<?=$row['status']==='completed'?'success':($row['status']==='failed'?'danger':'warning')?> align-self-start"><?=e(str_replace('_',' ',$row['status']))?></span></div><div class="card-body"><?php if($row['competitor_id']):?><p class="mb-2">Linked to <a href="<?=e(url('admin/competitors/edit.php?id='.(int)$row['competitor_id']))?>"><?=e($row['bdc_id'].' · '.$row['competitor_name'])?></a></p><?php endif;?><?php if($candidates):?><strong>Identity candidates</strong><div class="list-group mt-2"><?php foreach($candidates as $candidate):?><a class="list-group-item list-group-item-action" href="<?=e(url('admin/competitors/edit.php?id='.(int)$candidate['id']))?>"><strong><?=e($candidate['bdc_id'].' · '.$candidate['exact_name'])?></strong><div class="small text-muted"><?=e(implode(' · ',array_filter([$candidate['email'],$candidate['phone'],$candidate['instagram'],$candidate['country']])))?></div></a><?php endforeach;?></div><?php endif;?><?php if($row['error_message']):?><div class="alert alert-danger mt-2 mb-0"><?=e($row['error_message'])?></div><?php endif;?></div></section><?php endforeach;?><?php if(!$rows):?><div class="card border-0 shadow-sm"><div class="card-body text-center text-muted py-5">No sync rows in this status.</div></div><?php endif;?></main></body></html>
