<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/bootstrap.php'
use App\Core\Auth;use App\Core\Database;use App\Services\TestAutomaticJudgeService;
Auth::requireAdmin();$pdo=Database::connection();$roundId=(int)($_GET['round_id']??0);header('Content-Type: application/json');header('Cache-Control:no-store');
try{
 $r=$pdo->prepare('SELECT round_type FROM bdc_test_scoring_rounds WHERE id=:r');$r->execute(['r'=>$roundId]);$type=(string)$r->fetchColumn();if(!$type)throw new RuntimeException('Round not found.');
 $judges=TestAutomaticJudgeService::progress($pdo,$roundId);$j=$pdo->prepare('SELECT id,judge_name,judge_order,is_chief,scoring_scope FROM bdc_test_scoring_judges WHERE round_id=:r ORDER BY judge_order');$j->execute(['r'=>$roundId]);$columns=$j->fetchAll();$entries=[];
 if($type==='final'){$q=$pdo->prepare("SELECT fp.id pair_id,fp.pair_number,le.display_name leader_name,fe.display_name follower_name FROM bdc_test_scoring_final_pairs fp JOIN bdc_test_scoring_entries le ON le.id=fp.leader_entry_id LEFT JOIN bdc_test_scoring_entries fe ON fe.id=fp.follower_entry_id WHERE fp.round_id=:r AND fp.pairing_status='confirmed' ORDER BY fp.pair_number");$q->execute(['r'=>$roundId]);foreach($q->fetchAll() as $entry){$m=$pdo->prepare('SELECT judge_id,rank_value FROM bdc_test_scoring_final_marks WHERE round_id=:r AND pair_id=:p');$m->execute(['r'=>$roundId,'p'=>$entry['pair_id']]);$entry['marks']=array_column($m->fetchAll(PDO::FETCH_KEY_PAIR),1,0);$entries[]=$entry;}}
 else{$q=$pdo->prepare("SELECT id,bib_number,display_name,dance_role FROM bdc_test_scoring_entries WHERE round_id=:r AND entry_status='active' ORDER BY dance_role,bib_number");$q->execute(['r'=>$roundId]);foreach($q->fetchAll() as $entry){$m=$pdo->prepare('SELECT judge_id,mark_type,alt_rank,weighted_score FROM bdc_test_scoring_marks WHERE round_id=:r AND entry_id=:e');$m->execute(['r'=>$roundId,'e'=>$entry['id']]);$marks=[];$score=0.0;foreach($m->fetchAll() as $mark){$marks[(int)$mark['judge_id']]=$mark['mark_type']==='yes'?'YES':($mark['mark_type']==='alt'?'A'.(int)$mark['alt_rank']:'NO');$score+=(float)$mark['weighted_score'];}$entry['marks']=$marks;$entry['score']=$score;$entries[]=$entry;}}
 echo json_encode(['ok'=>true,'round_type'=>$type,'judges'=>$judges,'judge_columns'=>$columns,'entries'=>$entries]);
}catch(Throwable $e){http_response_code(422);echo json_encode(['ok'=>false,'error'=>$e->getMessage()]);}
