<?php
/** @var array $sessions @var array $state @var array $entries @var array $judges @var array $automaticCheckpoints */
$automaticLocked=(string)$competition['status']==='submitted';
?>
<section id="automatic-workspace" class="mt-4" data-dc-automatic data-api="scoring-api.php?id=<?=$id?><?=$suffix?>" data-csrf="<?=e($csrf)?>" data-competition="<?=$id?>" data-mode="<?=$test?'test':'real'?>">
  <nav class="dc-workflow-steps mb-4" aria-label="Automatic scoring workflow">
    <a href="#automatic-roster"><span>1</span> Roster</a><a href="#judge-progress"><span>2</span> Judge Scoring</a><a href="#round-controls"><span>3</span> Checkpoint &amp; Print</a><a href="#calculated-ranking"><span>4</span> Ranking</a><a href="#round-controls"><span>5</span> Submit</a><a href="#projection-controls"><span>6</span> Projection</a>
  </nav>

  <section id="judge-progress" class="card border-0 shadow-sm mb-4">
    <div class="card-body p-3 p-md-4">
      <div class="d-flex flex-wrap justify-content-between align-items-start gap-2 mb-3"><div><span class="badge text-bg-primary">STEP 2</span><h2 class="h4 mt-2 mb-1">All Judges · Live Status</h2><p class="text-muted mb-0">Every assigned judge is shown below and refreshes automatically every two seconds.</p></div><div class="d-flex gap-2 align-items-center"><small class="text-muted" data-dc-last-updated>Waiting for refresh…</small><button type="button" class="btn btn-outline-primary btn-sm" data-dc-refresh-status>Refresh Now</button></div></div>
      <?php foreach($sessions as $session):$required=(int)$session['entry_count']*(int)$session['criterion_count'];$done=min($required,(int)$session['mark_count']);$judgeUrl=url('admin/dance-cup/judge-scoring.php?token='.rawurlencode((string)$session['access_token']).($test?'&data_mode=test':''));?>
      <article class="card judge-state <?=e((string)$session['status'])?> mb-3" data-session-id="<?=(int)$session['id']?>"><div class="card-body">
        <?php $liveStatus=$session['status']==='submitted'?'Submitted':($required>0&&$done>=$required?'Complete':($session['status']==='scoring'?'Scoring':'Not Started'));$liveTone=$liveStatus==='Submitted'?'success':($liveStatus==='Complete'?'primary':($liveStatus==='Scoring'?'warning':'secondary'));?>
        <div class="d-flex justify-content-between gap-2"><div><strong>J<?=(int)$session['judge_order']?> · <?=e($session['judge_name'])?><?=$session['is_chief']?' ★ Chief Judge':''?></strong><div class="small text-muted"><span data-session-count><?=$done?> / <?=$required?> marks</span></div></div><span data-session-state class="badge text-bg-<?=$liveTone?>"><?=e($liveStatus)?></span></div>
        <div class="progress my-3" style="height:8px"><div class="progress-bar" data-session-progress style="width:<?=$required?round($done/$required*100):0?>%"></div></div>
        <div class="link-row"><input id="unifiedJudgeLink<?=(int)$session['id']?>" class="form-control" readonly value="<?=e($judgeUrl)?>"><button type="button" class="btn btn-outline-primary" data-copy="unifiedJudgeLink<?=(int)$session['id']?>">Copy</button><a class="btn btn-primary" target="_blank" rel="noopener" href="<?=e($judgeUrl)?>">Open Judge Sheet</a></div>
        <form method="post" class="d-flex gap-2 flex-wrap mt-2"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="data_mode" value="<?=$test?'test':'real'?>"><input type="hidden" name="session_id" value="<?=(int)$session['id']?>"><button class="btn btn-sm btn-outline-secondary" name="action" value="regenerate" onclick="return confirm('Regenerate this judge link?')" <?=$automaticLocked?'disabled':''?>>Regenerate Link</button><?php if($session['status']==='submitted'&&!$automaticLocked):?><button class="btn btn-sm btn-outline-danger" name="action" value="reopen" onclick="return confirm('Reopen this judge and preserve current marks?')">Reopen Judge Scores</button><?php endif;?></form>
      </div></article>
      <?php endforeach;?>
      <?php if(!$sessions):?><div class="alert alert-warning mb-0">Add contestants, judges and exactly one Chief Judge above to open judge scoring.</div><?php endif;?>
    </div>
  </section>

  <section class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-md-4">
    <div class="d-flex flex-wrap justify-content-between gap-3"><div><h2 class="h4 mb-1">Live Judge Score Matrix</h2><p class="text-muted mb-0" data-dc-round-summary><?=$state['mark_count']?> / <?=$state['required_marks']?> marks · <?=$state['completed_judges']?> / <?=$state['judge_count']?> judges complete</p></div><span class="badge <?=$automaticLocked?'text-bg-success':'text-bg-secondary'?> align-self-start" data-dc-status><?=e(strtoupper((string)$competition['status']))?></span></div>
    <div class="table-responsive mt-3"><table class="table table-bordered align-middle mb-0"><thead><tr><th>No.</th><th>Contestant</th><?php foreach($judges as $judge):?><th>J<?=(int)$judge['judge_order']?><small class="d-block"><?=e($judge['judge_name'])?></small></th><?php endforeach;?><th>Calculated Place</th></tr></thead><tbody><?php foreach($entries as $entry):$resultRow=null;foreach($state['results'] as $candidate)if((int)$candidate['entry_id']===(int)$entry['id']){$resultRow=$candidate;break;}?><tr><td><strong>#<?=(int)$entry['bib_number']?></strong></td><td><?=e($entry['display_name'])?></td><?php foreach($judges as $judge):$judgeTotal=$state['row_totals'][(int)$entry['id']][(int)$judge['id']]??null;?><td data-dc-matrix-total data-entry="<?=(int)$entry['id']?>" data-judge="<?=(int)$judge['id']?>"><?=$judgeTotal===null?'<span class="text-muted">—</span>':e(rtrim(rtrim(number_format((float)$judgeTotal,2,'.',''),'0'),'.'))?></td><?php endforeach;?><td><?=$resultRow?'<strong>#'.(int)$resultRow['placement'].'</strong>':'<span class="text-muted">Not calculated</span>'?></td></tr><?php endforeach;?><?php if(!$entries):?><tr><td colspan="<?=count($judges)+3?>" class="text-muted">No contestants assigned.</td></tr><?php endif;?></tbody></table></div>
  </div></section>

  <section id="round-controls" class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-md-4">
    <span class="badge text-bg-success">STEPS 3–5</span><h2 class="h4 mt-2">Checkpoint, Print, Rank &amp; Submit</h2>
    <div class="dc-unified-actions">
      <form method="post" class="dc-checkpoint-form"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="data_mode" value="<?=$test?'test':'real'?>"><input type="hidden" name="action" value="checkpoint"><input class="form-control" name="checkpoint_label" placeholder="Checkpoint name"><button class="btn btn-outline-success">Save Checkpoint</button></form>
      <a class="btn btn-outline-dark" target="_blank" rel="noopener" href="judge-sheet.php?id=<?=$id?><?=$suffix?>">Print Judge Sheets</a>
      <button type="button" class="btn btn-warning" data-dc-api-action="calculate" <?=$state['mark_count']<1||$automaticLocked?'disabled':''?>>Calculate &amp; Sort Ranking</button>
      <button type="button" class="btn btn-success" data-dc-api-action="submit" data-dc-lock-on-submit <?=(!$state['all_marks_complete']||!$state['results_current']||$automaticLocked)?'disabled':''?>>Submit Scores &amp; Lock</button>
    </div>
    <div class="alert alert-info mt-3 mb-0" data-dc-notice><?=$automaticLocked?'Round locked. Results and checkpoints remain available for review.':'Judge Submit is optional. When every required mark is complete, calculate and review the ranking; final Submit Scores & Lock will lock every judge sheet together.'?></div>
    <div class="mt-3"><strong>Saved checkpoints</strong><div class="mt-2"><?php foreach($automaticCheckpoints as $checkpoint):?><span class="badge text-bg-light border me-2 mb-2"><?=e($checkpoint['label'])?> · <?=e($checkpoint['created_at'])?></span><?php endforeach;?><?php if(!$automaticCheckpoints):?><span class="text-muted small">No checkpoints saved yet.</span><?php endif;?></div></div>
  </div></section>

  <section id="calculated-ranking" class="card border-0 shadow-sm mb-4"><div class="card-body p-3 p-md-4"><h2 class="h4">Calculated Ranking</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Place</th><th>No.</th><th>Contestant / Team</th><th>Total Score</th></tr></thead><tbody data-dc-results><?php foreach($state['results'] as $result):?><tr><td><strong>#<?=(int)$result['placement']?></strong></td><td>#<?=(int)$result['bib_number']?></td><td><?=e($result['display_name'])?></td><td><?=e(rtrim(rtrim(number_format((float)$result['total_score'],2,'.',''),'0'),'.'))?></td></tr><?php endforeach;?><?php if(!$state['results']):?><tr><td colspan="4" class="text-muted">Judge scores will appear here after Calculate &amp; Sort Ranking.</td></tr><?php endif;?></tbody></table></div></div></section>

  <section id="projection-controls" class="card border-danger shadow-sm mb-4"><div class="card-body p-3 p-md-4"><span class="badge text-bg-danger">STEP 6</span><h2 class="h4 mt-2">Live Projection</h2><div class="d-flex gap-2 flex-wrap"><a class="btn btn-danger" target="_blank" rel="noopener" href="projection-control.php?id=<?=$id?><?=$suffix?>">Open Projection Control</a><a class="btn btn-outline-danger" target="_blank" rel="noopener" href="<?=e($projectorUrl)?>">Open Projector Screen</a><form method="post"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="data_mode" value="<?=$test?'test':'real'?>"><button class="btn btn-outline-secondary" name="action" value="reset_projection" onclick="return confirm('Regenerate the projector link?')">Regenerate Projector Link</button></form></div></div></section>
</section>
<script defer src="../../public/js/dance-cup-scoring-live.js?v=432"></script>
<script defer src="../../public/js/dance-cup-unified-workspace-v430.js?v=430"></script>
