<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Database;use App\Services\SchemaUpdater;
Auth::requireAdmin();$pdo=Database::connection();
$eventId=(int)($_GET['event_id']??0);
$events=$pdo->query("SELECT id,name,event_date FROM bdc_events ORDER BY event_date DESC,name LIMIT 300")->fetchAll();
$params=[];$where='';if($eventId){$where='WHERE t.event_id=:event';$params=['event'=>$eventId];}
$s=$pdo->prepare("SELECT t.*,u.full_name FROM bdc_competition_timeline t LEFT JOIN bdc_users u ON u.id=t.user_id $where ORDER BY t.created_at DESC LIMIT 500");$s->execute($params);$items=$s->fetchAll();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Competition Timeline | BDC</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="<?=e(url('admin/'))?>">BDC Admin</a><a class="btn btn-warning btn-sm" href="https://bachatadancecouncil.com/">🏠 BDC Home</a></div></nav><main class="container py-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">Competition Timeline</h1><p class="text-muted mb-0">Chronological scoring and competition activity.</p></div><a class="btn btn-outline-dark" href="<?=e(url('admin/'))?>">Dashboard</a></div><form class="card card-body border-0 shadow-sm mb-4"><label class="form-label">Filter by event</label><div class="d-flex gap-2"><select class="form-select" name="event_id"><option value="0">All events</option><?php foreach($events as $e):?><option value="<?=(int)$e['id']?>" <?=$eventId===(int)$e['id']?'selected':''?>><?=e(($e['event_date']?:'Date pending').' — '.$e['name'])?></option><?php endforeach;?></select><button class="btn btn-dark">Filter</button></div></form><div class="card border-0 shadow-sm"><div class="card-body"><?php if(!$items):?><p class="text-muted mb-0">No timeline entries yet.</p><?php else:?><div class="list-group list-group-flush"><?php foreach($items as $i):?><div class="list-group-item px-0"><div class="d-flex justify-content-between"><strong><?=e($i['event_label'])?></strong><span class="text-muted small"><?=e($i['created_at'])?></span></div><div class="small text-muted"><?=e($i['full_name']?:'System')?> · <?=e($i['event_key'])?></div></div><?php endforeach;?></div><?php endif;?></div></div></main></body></html>
