<?php
declare(strict_types=1);
require dirname(__DIR__, 2) . '/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;
Auth::requireAdmin();$pdo=Database::connection();
$mode=in_array((string)($_GET['mode']??'manual'),['manual','automated'],true)?(string)$_GET['mode']:'manual';
$events=$pdo->query("SELECT e.id,e.name,e.event_date FROM bdc_events e LEFT JOIN bdc_scoring_archived_events a ON a.event_id=e.id WHERE e.status NOT IN ('completed','published') AND a.event_id IS NULL ORDER BY e.event_date DESC,e.name")->fetchAll();
$occupied=$pdo->query("SELECT DISTINCT event_id,dance_style,division FROM bdc_scoring_rounds WHERE status<>'archived'")->fetchAll();
$stmt=$pdo->prepare("SELECT r.*,e.name event_name,e.status event_status,(SELECT COUNT(*) FROM bdc_scoring_entries x WHERE x.round_id=r.id) entry_count,(SELECT COUNT(*) FROM bdc_scoring_judges x WHERE x.round_id=r.id) judge_count,(SELECT COUNT(*) FROM bdc_scoring_marks x WHERE x.round_id=r.id) mark_count,(SELECT COUNT(*) FROM bdc_scoring_final_marks x WHERE x.round_id=r.id) final_mark_count FROM bdc_scoring_rounds r JOIN bdc_events e ON e.id=r.event_id LEFT JOIN bdc_scoring_archived_events a ON a.event_id=e.id WHERE e.status NOT IN ('completed','published') AND a.event_id IS NULL AND r.status NOT IN ('completed','archived') AND r.scoring_mode=:mode ORDER BY r.updated_at DESC LIMIT 30");
$stmt->execute(['mode'=>$mode]);$rounds=$stmt->fetchAll();$csrf=Csrf::token();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scoring Dashboard | BDC</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="../">BDC Admin</a><div><a class="btn btn-outline-light btn-sm" href="../completed-events/">Completed Events</a> <a class="btn btn-outline-light btn-sm" href="../">Dashboard</a></div></div></nav>
<main class="container-fluid py-4" style="max-width:1600px"><h1 class="h3">Scoring Dashboard</h1><p class="text-muted">BDC Scoring Engine · Event Round Workflow</p>
<?php if(isset($_GET['draft_deleted'])):?><div class="alert alert-success">Draft scoring workflow deleted. The Event + Dance + Division is available to create again.</div><?php endif;?><?php if(isset($_GET['draft_updated'])):?><div class="alert alert-success">Draft event and division details updated.</div><?php endif;?>
<div class="card shadow-sm mb-4"><div class="card-body"><h2 class="h5">Create Scoring Round</h2><p class="text-muted">Choose an active event. Existing Event + Dance + Division combinations cannot be duplicated; open the saved draft instead, or delete the draft to restart.</p>
<form method="post" action="index.php?mode=<?=e($mode)?>" class="row g-3"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="create_round"><input type="hidden" name="scoring_mode" value="<?=e($mode)?>">
<div class="col-lg-6"><label class="form-label">Select Existing Event</label><select class="form-select" name="event_id" id="eventId"><option value="">Select event</option><?php foreach($events as $event):?><option value="<?=(int)$event['id']?>"><?=e(($event['event_date']?:'Date pending').' — '.$event['name'])?></option><?php endforeach;?></select></div>
<div class="col-lg-3"><label class="form-label">Dance Style</label><select class="form-select" name="dance_style" id="danceStyle"><option value="bachata">Bachata</option><option value="salsa">Salsa</option></select></div>
<div class="col-lg-3"><label class="form-label">Division</label><select class="form-select" name="division" id="division"><option value="novice">Novice</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option><option value="bachata_rising" data-dance="bachata">BDC Rising Star</option><option value="bachata_open" data-dance="bachata">BDC Open</option><option value="bachata_invitational" data-dance="bachata">Bachata Invitational</option><option value="salsa_rising" data-dance="salsa">Salsa Rising</option><option value="salsa_open" data-dance="salsa">Salsa Open</option></select><div id="occupiedNote" class="form-text text-danger d-none">This scoring workflow already exists. Open it under Saved Rounds or delete the Draft to restart.</div></div>
<div class="col-12 text-center text-muted fw-semibold">OR CREATE A BASIC EVENT</div><div class="col-lg-8"><label class="form-label">New Event Name</label><input class="form-control" name="new_event_name" maxlength="190"></div><div class="col-lg-4"><label class="form-label">Event Date</label><input class="form-control" type="date" name="new_event_date"></div><div class="col-12"><button class="btn btn-success createBtn" name="round_type" value="heats">Start with Heats</button> <button class="btn btn-dark createBtn" name="round_type" value="final">Go Straight to Final</button></div></form></div></div>
<div class="card shadow-sm"><div class="card-body"><h2 class="h5">Saved Rounds</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Event</th><th>Dance</th><th>Division</th><th>Round</th><th>Status</th><th>Updated</th><th class="text-end">Actions</th></tr></thead><tbody>
<?php if(!$rounds):?><tr><td colspan="7" class="text-center text-muted py-4">No active scoring rounds.</td></tr><?php else:foreach($rounds as $r):$draft=in_array((string)$r['status'],['draft','discarded'],true);$hasScores=(int)$r['mark_count']>0||(int)$r['final_mark_count']>0;$dataCount=(int)$r['entry_count']+(int)$r['judge_count']+(int)$r['mark_count']+(int)$r['final_mark_count'];?><tr><td><?=e($r['event_name'])?></td><td><span class="badge text-bg-secondary"><?=e(ucfirst($r['dance_style']??'bachata'))?></span></td><td><?=e(ucwords(str_replace('_',' ',$r['division'])))?></td><td><?=e(ucfirst($r['round_type']))?></td><td><span class="badge text-bg-secondary"><?=e(ucwords(str_replace('_',' ',$r['status'])))?></span><?php if($draft&&$dataCount>0):?><div class="small text-warning-emphasis">Contains scoring setup</div><?php endif;?></td><td><?=e($r['updated_at'])?></td><td class="text-end"><div class="d-inline-flex gap-2"><a class="btn btn-sm btn-outline-dark" href="index.php?mode=<?=e($r['scoring_mode'])?>&amp;round_id=<?=(int)$r['id']?>">Open</a><?php if($draft&&!$hasScores):?><a class="btn btn-sm btn-outline-primary" href="edit-draft.php?mode=<?=e($r['scoring_mode'])?>&amp;round_id=<?=(int)$r['id']?>">Edit Draft Details</a><?php endif;?><?php if($draft):?><form method="post" action="delete-draft.php"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="event_id" value="<?=(int)$r['event_id']?>"><input type="hidden" name="dance_style" value="<?=e($r['dance_style']??'bachata')?>"><input type="hidden" name="division" value="<?=e($r['division'])?>"><input type="hidden" name="mode" value="<?=e($mode)?>"><button class="btn btn-sm btn-outline-danger">Delete Draft</button></form><?php endif;?></div></td></tr><?php endforeach;endif;?></tbody></table></div></div></div></main>
<script>const occupied=<?=json_encode($occupied,JSON_UNESCAPED_SLASHES)?>,ev=document.getElementById('eventId'),d=document.getElementById('danceStyle'),v=document.getElementById('division'),note=document.getElementById('occupiedNote'),buttons=[...document.querySelectorAll('.createBtn')];function sync(){[...v.options].forEach(o=>{const only=o.dataset.dance;o.hidden=!!only&&only!==d.value;o.disabled=!!only&&only!==d.value});const allowed=d.value==='salsa'?['novice','intermediate','advanced','salsa_rising','salsa_open']:['novice','intermediate','advanced','bachata_rising','bachata_open','bachata_invitational'];if(!allowed.includes(v.value))v.value='novice';const hit=ev.value&&occupied.some(x=>String(x.event_id)===ev.value&&(x.dance_style||'bachata')===d.value&&x.division===v.value);note.classList.toggle('d-none',!hit);buttons.forEach(b=>b.disabled=!!hit)}[ev,d,v].forEach(x=>x.addEventListener('change',sync));sync();</script></body></html>
