<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\AutomaticJudgeBrowserService;use App\Services\ScoringRosterCheckpointService;
Auth::requireAdmin();$pdo=Database::connection();$roundId=(int)($_POST['round_id']??0);$return='automatic-round.php?round_id='.$roundId;
try{
 if($_SERVER['REQUEST_METHOD']!=='POST'||!Csrf::verify($_POST['_csrf']??null))throw new RuntimeException('Invalid request. Refresh the dashboard and try again.');
 $s=$pdo->prepare("SELECT * FROM bdc_scoring_rounds WHERE id=:id AND scoring_mode='automated' LIMIT 1");$s->execute(['id'=>$roundId]);$round=$s->fetch();if(!$round)throw new RuntimeException('Automatic scoring round not found.');
 if(in_array((string)$round['status'],['completed','pending_approval','archived'],true))throw new RuntimeException('This scoring round is read-only. Completed rounds require a Scorer or Super Admin RESUBMIT override.');
 $action=(string)($_POST['action']??'');$userId=(int)(Auth::user()['id']??0);
 if($action==='settings'){
  $tier=(int)($_POST['competition_tier']??0);$yes=[1=>5,2=>10,3=>15][$tier]??0;if(!$yes)throw new RuntimeException('Select a valid competition tier.');
  $pdo->prepare('UPDATE bdc_scoring_rounds SET yes_count=:yes,callback_count=:yes,tier_manual_override=1,yes_weight=10.00,alt1_weight=4.50,alt2_weight=4.30,alt3_weight=4.20 WHERE id=:id')->execute(['yes'=>$yes,'id'=>$roundId]);$message='BDC Tier '.$tier.' settings saved.';
 }elseif($action==='add_entry'){
  ScoringRosterCheckpointService::assertEditable($pdo,$roundId);
  $role=(string)($_POST['dance_role']??'');$bib=(int)($_POST['bib_number']??0);$term=trim((string)($_POST['competitor_search']??''));$mode=(string)($_POST['entry_mode']??'existing');if(!in_array($role,['leader','follower'],true)||$bib<1||$term==='')throw new RuntimeException('Choose role, bib and competitor.');
  $q=$pdo->prepare("SELECT display_name FROM bdc_scoring_entries WHERE round_id=:r AND dance_role=:role AND bib_number=:bib AND entry_status='active' LIMIT 1");$q->execute(['r'=>$roundId,'role'=>$role,'bib'=>$bib]);if($name=$q->fetchColumn())throw new RuntimeException('Bib '.$bib.' is already assigned to '.$name.'.');
  $bdc='';if(preg_match('/^(BDC-\d+)/i',$term,$m))$bdc=strtoupper($m[1]);$q=$pdo->prepare("SELECT id,bdc_id,exact_name,dance_role FROM bdc_competitors WHERE status<>'archived' AND dance_role=:role AND (bdc_id=:bdc OR LOWER(exact_name)=LOWER(:name)) ORDER BY CASE WHEN bdc_id=:preferred THEN 0 ELSE 1 END,id LIMIT 2");$q->execute(['role'=>$role,'bdc'=>$bdc!==''?$bdc:$term,'name'=>$term,'preferred'=>$bdc]);$matches=$q->fetchAll();if(count($matches)>1&&$bdc==='')throw new RuntimeException('Several '.$role.' competitors have this name. Select the exact BDC ID.');$competitor=$matches[0]??null;
  if(!$competitor&&$mode!=='create')throw new RuntimeException(ucfirst($role).' competitor not found. Select the correct '.$role.' BDC ID or use Create Name & Add.');
  if(!$competitor){$normalised=mb_strtolower(trim((string)preg_replace('/\s+/',' ',$term)));$same=$pdo->prepare('SELECT bdc_id,exact_name FROM bdc_competitors WHERE normalised_name=:name ORDER BY id LIMIT 1');$same->execute(['name'=>$normalised]);if($existing=$same->fetch())throw new RuntimeException('This name already exists as '.$existing['exact_name'].' ('.$existing['bdc_id'].'). Add the existing BDC ID.');$next=(int)$pdo->query("SELECT COALESCE(MAX(CAST(SUBSTRING(bdc_id,5) AS UNSIGNED)),0)+1 FROM bdc_competitors WHERE bdc_id LIKE 'BDC-%'")->fetchColumn();$bdcId='BDC-'.str_pad((string)$next,6,'0',STR_PAD_LEFT);$pdo->prepare("INSERT INTO bdc_competitors(bdc_id,exact_name,normalised_name,dance_role,current_division,status,is_historical) VALUES(:bdc,:name,:normalised,:role,:division,'pending',0)")->execute(['bdc'=>$bdcId,'name'=>$term,'normalised'=>$normalised,'role'=>$role,'division'=>$round['division']]);$competitor=['id'=>(int)$pdo->lastInsertId(),'bdc_id'=>$bdcId,'exact_name'=>$term,'dance_role'=>$role];}
  $profile=$pdo->prepare('SELECT dance_role FROM bdc_competitor_discipline_profiles WHERE competitor_id=:c AND dance_style=:dance LIMIT 1');$profile->execute(['c'=>$competitor['id'],'dance'=>$round['dance_style']??'bachata']);$profileRole=(string)($profile->fetchColumn()?:$competitor['dance_role']);if(!in_array($profileRole,[$role,'both','unknown'],true))throw new RuntimeException($competitor['exact_name'].' is registered as '.ucfirst($profileRole).' for this dance style.');
  $existingEntry=$pdo->prepare("SELECT dance_role,bib_number,display_name FROM bdc_scoring_entries WHERE round_id=:round AND competitor_id=:competitor AND entry_status='active' LIMIT 1");$existingEntry->execute(['round'=>$roundId,'competitor'=>$competitor['id']]);if($already=$existingEntry->fetch())throw new RuntimeException($already['display_name'].' is already entered as '.ucfirst((string)$already['dance_role']).' with bib #'.(int)$already['bib_number'].'. Change the existing bib instead of adding the competitor again.');
  $pdo->prepare("INSERT INTO bdc_scoring_entries(round_id,competitor_id,dance_role,bib_number,display_name,entry_status) VALUES(:r,:c,:role,:bib,:name,'active')")->execute(['r'=>$roundId,'c'=>$competitor['id'],'role'=>$role,'bib'=>$bib,'name'=>$competitor['exact_name']]);$message=ucfirst($role).' added: '.$competitor['exact_name'].' ('.$competitor['bdc_id'].').';
 }elseif($action==='update_bib'){
  ScoringRosterCheckpointService::assertEditable($pdo,$roundId);
  $entryId=(int)($_POST['entry_id']??0);$bib=(int)($_POST['bib_number']??0);if($entryId<1||$bib<1)throw new RuntimeException('Enter a valid bib number.');$entry=$pdo->prepare("SELECT dance_role,display_name FROM bdc_scoring_entries WHERE id=:entry AND round_id=:round AND entry_status='active'");$entry->execute(['entry'=>$entryId,'round'=>$roundId]);$row=$entry->fetch();if(!$row)throw new RuntimeException('Competitor entry not found.');$taken=$pdo->prepare("SELECT display_name FROM bdc_scoring_entries WHERE round_id=:round AND dance_role=:role AND bib_number=:bib AND entry_status='active' AND id<>:entry LIMIT 1");$taken->execute(['round'=>$roundId,'role'=>$row['dance_role'],'bib'=>$bib,'entry'=>$entryId]);if($name=$taken->fetchColumn())throw new RuntimeException('Bib '.$bib.' is already assigned to '.$name.'.');$pdo->prepare('UPDATE bdc_scoring_entries SET bib_number=:bib WHERE id=:entry AND round_id=:round')->execute(['bib'=>$bib,'entry'=>$entryId,'round'=>$roundId]);$message=$row['display_name'].' bib updated.';
 }elseif($action==='remove_entry'){ScoringRosterCheckpointService::assertEditable($pdo,$roundId);$entryId=(int)($_POST['entry_id']??0);$pdo->prepare("UPDATE bdc_scoring_entries SET entry_status='withdrawn' WHERE id=:entry AND round_id=:round")->execute(['entry'=>$entryId,'round'=>$roundId]);$message='Competitor removed from this round.';
 }elseif($action==='save_competitors'){ScoringRosterCheckpointService::checkpoint($pdo,$roundId,$userId,'save');$message='Competitor roster checkpoint saved as draft.';
 }elseif($action==='submit_competitors'){ScoringRosterCheckpointService::checkpoint($pdo,$roundId,$userId,'submit');$message='Competitors submitted and locked. Judging can now begin.';
 }elseif($action==='reopen_competitors'){if(!Auth::isSuperAdmin())throw new RuntimeException('Only the Super Admin can reopen submitted competitors.');ScoringRosterCheckpointService::checkpoint($pdo,$roundId,$userId,'reopen',false,(string)($_POST['reopen_reason']??''));$message='Competitor roster reopened for correction.';
 }elseif($action==='unlock_all_judges'){
  if(!Auth::canOverrideCompletedScores())throw new RuntimeException('Only a Scorer, Master Scorer or Super Admin can use the emergency unlock.');
  $reason=trim((string)($_POST['unlock_all_reason']??''));$confirmation=strtoupper(trim((string)($_POST['unlock_all_confirmation']??'')));
  if($confirmation!=='UNLOCK ALL')throw new RuntimeException('Type UNLOCK ALL to confirm the emergency override.');
  $unlocked=AutomaticJudgeBrowserService::unlockAllSubmitted($pdo,$roundId,$userId,$reason);
  $pdo->prepare("UPDATE bdc_scoring_rounds SET status=CASE WHEN status='scores_submitted' THEN 'draft' ELSE status END WHERE id=:id")->execute(['id'=>$roundId]);
  $message=$unlocked['count'].' locked judge score columns reopened. Existing scores were preserved and must be resubmitted.';
 }
 else throw new RuntimeException('Unsupported Automatic dashboard action.');
 Auth::audit($userId,'automatic_scoring_'.$action,['round_id'=>$roundId],'scoring_round',$roundId);$_SESSION['automatic_scoring_notice']=$message;
}catch(Throwable $error){$_SESSION['automatic_scoring_error']=$error->getMessage();}
header('Location: '.$return,true,303);exit;
