<?php
declare(strict_types=1);

use App\Core\Auth;
use App\Core\Config;
use App\Core\Csrf;
use App\Core\Database;
use App\Services\SpecialCategoryService;
use App\Services\ScoringJudgeAssignmentService;
use App\Services\AutomaticJudgeBrowserService;
use App\Services\ScoringRulesService;
use App\Services\ScoringRosterCheckpointService;
use App\Services\JackJillCompetitorEligibilityService;
use App\Services\RoleYesConfigurationService;

function bdcRenderAutomaticCommonSetup(int $roundId):string
{
    $pdo=Database::connection();
    $stmt=$pdo->prepare("SELECT r.*,e.name event_name FROM bdc_scoring_rounds r JOIN bdc_events e ON e.id=r.event_id WHERE r.id=:round LIMIT 1");$stmt->execute(['round'=>$roundId]);$round=$stmt->fetch();
    if(!$round||($round['scoring_mode']??'')!=='automated'||($round['round_type']??'')==='final')return '';
    $judgeStmt=$pdo->prepare('SELECT * FROM bdc_scoring_judges WHERE round_id=:round ORDER BY is_chief DESC,judge_order,id');$judgeStmt->execute(['round'=>$roundId]);$judges=$judgeStmt->fetchAll();
    $judgeDirectory=[];try{$judgeDirectory=ScoringJudgeAssignmentService::directory($pdo);}catch(Throwable $directoryError){error_log('BDC automatic scoring judge directory unavailable: '.$directoryError->getMessage());}
    $entryStmt=$pdo->prepare("SELECT se.*,c.bdc_id,c.status competitor_status FROM bdc_scoring_entries se JOIN bdc_competitors c ON c.id=se.competitor_id WHERE se.round_id=:round AND se.entry_status='active' ORDER BY se.dance_role,se.bib_number");$entryStmt->execute(['round'=>$roundId]);$entries=['leader'=>[],'follower'=>[]];foreach($entryStmt->fetchAll() as $entry)$entries[$entry['dance_role']][]=$entry;
    $activeCompetitorIds=[];foreach(array_merge($entries['leader'],$entries['follower']) as $entry)$activeCompetitorIds[(int)$entry['competitor_id']]=true;
    $rosterState=ScoringRosterCheckpointService::state($pdo,$roundId);$rosterSubmitted=(string)$rosterState['status']==='submitted';$nextBib=['leader'=>1,'follower'=>1];foreach(['leader','follower'] as $role)foreach($entries[$role] as $entry)$nextBib[$role]=max($nextBib[$role],(int)$entry['bib_number']+1);
    $suggestions=JackJillCompetitorEligibilityService::directory($pdo,(string)$round['dance_style'],null,1500);$csrf=Csrf::token();$special=SpecialCategoryService::isSpecial((string)$round['division']);$categoryLabel=$special?SpecialCategoryService::label((string)$round['division']):ucfirst((string)$round['division']);
    $linkStmt=$pdo->prepare('SELECT * FROM bdc_registration_desk_links WHERE event_id=:event AND division=:division LIMIT 1');$linkStmt->execute(['event'=>$round['event_id'],'division'=>$round['division']]);$link=$linkStmt->fetch();
    if(!$link){$token=bin2hex(random_bytes(24));$insert=$pdo->prepare('INSERT INTO bdc_registration_desk_links(event_id,division,token_hash,token_hint,created_by) VALUES(:event,:division,:hash,:hint,:user)');$insert->execute(['event'=>$round['event_id'],'division'=>$round['division'],'hash'=>hash('sha256',$token),'hint'=>substr($token,0,8),'user'=>(int)(Auth::user()['id']??0)?:null]);$link=['id'=>(int)$pdo->lastInsertId(),'plain_token'=>$token];$_SESSION['registration_desk_tokens'][(int)$link['id']]=$token;}
    if($_SERVER['REQUEST_METHOD']==='POST'&&(string)($_POST['action']??'')==='regenerate_registration_desk_link'&&(int)($_POST['round_id']??0)===$roundId&&Csrf::verify($_POST['_csrf']??null)){$token=bin2hex(random_bytes(24));$pdo->prepare('UPDATE bdc_registration_desk_links SET token_hash=:hash,token_hint=:hint,is_enabled=1 WHERE id=:id')->execute(['hash'=>hash('sha256',$token),'hint'=>substr($token,0,8),'id'=>(int)$link['id']]);$_SESSION['registration_desk_tokens'][(int)$link['id']]=$token;$link['plain_token']=$token;}
    $token=(string)($link['plain_token']??($_SESSION['registration_desk_tokens'][(int)$link['id']]??''));$deskUrl='';if($token!==''){$path=url('registration-desk/?token='.rawurlencode($token).'&round_id='.$roundId);$appUrl=rtrim((string)Config::get('app.url',''),'/');$parts=parse_url($appUrl);$deskUrl=is_array($parts)&&isset($parts['scheme'],$parts['host'])?$parts['scheme'].'://'.$parts['host'].(isset($parts['port'])?':'.(int)$parts['port']:'').$path:$path;}
    if(!$special){$tierInfo=ScoringRulesService::normalizeNormalRoundTier(count($entries['leader']),count($entries['follower']),(int)$round['yes_count'],(int)$round['callback_count'],(int)$round['tier_manual_override']===1);if($tierInfo['corrected']){$pdo->prepare('UPDATE bdc_scoring_rounds SET yes_count=:yes,callback_count=:callbacks WHERE id=:round')->execute(['yes'=>$tierInfo['yes_count'],'callbacks'=>$tierInfo['callback_count'],'round'=>$roundId]);$round['yes_count']=$tierInfo['yes_count'];$round['callback_count']=$tierInfo['callback_count'];}}
    $currentTier=(int)$round['yes_count']===5?1:((int)$round['yes_count']===15?3:2);$e=static fn(string $value):string=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');$html='<div id="automatic-common-setup">';
    $flashError=(string)($_SESSION['automatic_scoring_error']??'');$flashNotice=(string)($_SESSION['automatic_scoring_notice']??'');unset($_SESSION['automatic_scoring_error'],$_SESSION['automatic_scoring_notice']);if($flashError!=='')$html.='<div class="alert alert-danger">'.$e($flashError).'</div>';if($flashNotice!=='')$html.='<div class="alert alert-success">'.$e($flashNotice).'</div>';
    $html.='<div class="row g-3 mb-4"><div class="col-lg-4"><div class="card shadow-sm h-100"><div class="card-body"><h2 class="h5">'.($special?'Special Category Settings':$e(ucfirst((string)$round['round_type'])).' Settings').'</h2>';
    if($special){
        $schedule=SpecialCategoryService::schedule((string)$round['division']);$points=[];foreach($schedule as $rank=>$point)$points[]=$rank.'='.number_format((float)$point,0);$html.='<div class="alert alert-info py-2"><strong>'.$e($categoryLabel).'</strong><br>Fixed points: '.$e(implode(' · ',$points)).'</div>';
        $roleConfig=RoleYesConfigurationService::resolve($pdo,$roundId,(int)$round['yes_count']);$roleSaved=$roleConfig['leader']['saved']&&$roleConfig['follower']['saved'];$startedStmt=$pdo->prepare("SELECT COUNT(*) FROM bdc_scoring_marks WHERE round_id=:round AND (mark_type<>'blank' OR weighted_score>0)");$startedStmt->execute(['round'=>$roundId]);$scoringStarted=(int)$startedStmt->fetchColumn()>0;
        $html.='<form method="post" action="special-settings.php" class="row g-3"><input type="hidden" name="_csrf" value="'.$e($csrf).'"><input type="hidden" name="round_id" value="'.$roundId.'"><input type="hidden" name="return_to" value="automatic-round.php">';
        foreach(['leader'=>'LEAD','follower'=>'FOLLOW'] as $role=>$label){$count=$roleConfig[$role]['count'];$recommend=RoleYesConfigurationService::recommended($count,(int)$round['yes_count']);$selected=$roleSaved?$roleConfig[$role]['yes']:$recommend['yes'];$html.='<div class="col-12"><div class="border rounded p-3"><div class="fw-bold mb-2">'.$label.'</div><div class="small text-muted mb-2">'.$count.' competitors · Recommended Tier '.$recommend['tier'].' · '.$recommend['yes'].' YES</div><label class="form-label">YES count</label><select class="form-select" name="'.$role.'_yes_count" '.(($roleSaved||$scoringStarted)?'disabled':'').'><option value="5" '.($selected===5?'selected':'').'>5 YES</option><option value="10" '.($selected===10?'selected':'').'>10 YES</option><option value="15" '.($selected===15?'selected':'').'>15 YES</option></select>'.(($roleSaved||$scoringStarted)?'<input type="hidden" name="'.$role.'_yes_count" value="'.$selected.'">':'').'</div></div>';}
        $html.='<div class="col-12"><div class="border rounded p-3 bg-light"><div class="fw-semibold mb-2">Alternates · Locked</div><div class="row g-2 text-center"><div class="col-4"><small class="text-muted d-block">ALT 1</small><strong>4.5</strong></div><div class="col-4"><small class="text-muted d-block">ALT 2</small><strong>4.3</strong></div><div class="col-4"><small class="text-muted d-block">ALT 3</small><strong>4.2</strong></div></div></div></div>';
        $html.='<div class="col-12">'.($scoringStarted?'<span class="badge text-bg-secondary">Locked because judging has started</span>':($roleSaved?'<span class="badge text-bg-success">Role YES counts locked</span>':'<button class="btn btn-dark btn-sm" name="action" value="special_role_settings_lock">Save &amp; Lock Role YES Counts</button>')).'</div></form><div class="small text-muted mt-2">Lead and Follow are configured independently. Fixed-point rules and A1/A2/A3 weights remain unchanged.</div>';
    }else{
        $html.='<form method="post" action="automatic-setup-action.php" class="row g-3"><input type="hidden" name="_csrf" value="'.$e($csrf).'"><input type="hidden" name="action" value="settings"><input type="hidden" name="round_id" value="'.$roundId.'"><div class="col-12"><label class="form-label">Competition Tier</label><select class="form-select" name="competition_tier" id="competitionTier" onchange="updateTierSummary()"><option value="1" '.($currentTier===1?'selected':'').'>Tier 1 · 5–15 competitors</option><option value="2" '.($currentTier===2?'selected':'').'>Tier 2 · 16–30 competitors</option><option value="3" '.($currentTier===3?'selected':'').'>Tier 3 · 31+ competitors</option></select></div><div class="col-6"><label class="form-label">YES per Judge</label><input class="form-control" id="tierYesCount" value="'.(int)$round['yes_count'].'" readonly></div><div class="col-6"><label class="form-label">Alternates</label><input class="form-control" value="3" readonly></div><div class="col-12"><div class="border rounded p-3 bg-light"><div class="fw-semibold mb-2">Official BDC Weights · Locked</div><div class="row g-2 text-center"><div class="col-3"><small class="text-muted d-block">YES</small><strong>10</strong></div><div class="col-3"><small class="text-muted d-block">ALT 1</small><strong>4.5</strong></div><div class="col-3"><small class="text-muted d-block">ALT 2</small><strong>4.3</strong></div><div class="col-3"><small class="text-muted d-block">ALT 3</small><strong>4.2</strong></div></div></div></div><div class="col-12"><small class="text-muted">Automatic tier uses the larger individual role count, not Leaders + Followers combined.</small></div><div class="col-12"><button class="btn btn-outline-dark btn-sm">Save Tier Settings</button></div></form>';
    }
    $html.='</div></div></div>';
    $display=$judges?:[['judge_name'=>'','is_chief'=>1,'scoring_scope'=>'all'],['judge_name'=>'','is_chief'=>0,'scoring_scope'=>'all'],['judge_name'=>'','is_chief'=>0,'scoring_scope'=>'all']];$html.='<div class="col-lg-8"><div class="card shadow-sm h-100" id="judge-setup"><div class="card-body"><h2 class="h5">Judge Setup</h2><div class="small text-muted mb-3">Search the Judge Database or type a new name. New names automatically receive a Judge ID.</div><form method="post" action="save-judges.php"><input type="hidden" name="_csrf" value="'.$e($csrf).'"><input type="hidden" name="action" value="save_judges"><input type="hidden" name="round_id" value="'.$roundId.'"><div id="judgesWrap">';
    foreach($display as $i=>$judge){$html.='<div class="row g-2 mb-2 judge-row align-items-center"><div class="col-md-2"><strong>Judge '.($i+1).'</strong><input type="hidden" name="judge_assignment_id[]" value="'.(int)($judge['id']??0).'"><input type="hidden" name="judge_directory_id[]" value="'.(int)($judge['judge_id']??0).'"></div><div class="col-md-5"><input class="form-control" name="judge_name[]" list="judgeDirectorySuggestions" value="'.$e((string)$judge['judge_name']).'" placeholder="Search or type a new judge" required></div><div class="col-md-3"><select class="form-select" name="judge_scope[]">';foreach(['all'=>'All','leader'=>'Leaders','follower'=>'Followers'] as $value=>$label)$html.='<option value="'.$value.'" '.(($judge['scoring_scope']??'all')===$value?'selected':'').'>'.$label.'</option>';$html.='</select></div><div class="col-md-2"><label><input type="radio" name="chief_index" value="'.$i.'" '.((int)$judge['is_chief']?'checked':'').'> Chief</label></div></div>';}
    $html.='</div><div class="d-flex gap-2 flex-wrap"><button type="button" class="btn btn-outline-secondary btn-sm" onclick="addJudge()">+ Judge</button><button class="btn btn-dark btn-sm">Submit Judges</button></div></form></div></div></div></div><datalist id="judgeDirectorySuggestions">';foreach($judgeDirectory as $directoryJudge){$name=(string)($directoryJudge['display_name']?:$directoryJudge['full_name']);$code=(string)($directoryJudge['judge_code']??'');$country=(string)($directoryJudge['country']??'');$search=implode(' · ',array_filter([$name,$code,$country]));$html.='<option value="'.$e($search).'" data-judge-name="'.$e($name).'" data-judge-id="'.(int)$directoryJudge['id'].'"></option>';}$html.='</datalist>';
    $html.='<script>(function(){const form=document.querySelector("#judge-setup form"),wrap=document.getElementById("judgesWrap"),list=document.getElementById("judgeDirectorySuggestions");if(!form||!wrap||!list)return;const master=[...list.options].map(option=>({value:option.value,name:option.dataset.judgeName||option.value,label:option.label||option.textContent||"",id:option.dataset.judgeId||"0"})),normalise=value=>value.trim().replace(/\\s+/g," ").toLocaleLowerCase();function sync(){wrap.querySelectorAll(".judge-row").forEach((row,index)=>{const label=row.querySelector("strong");if(label)label.textContent="Judge "+(index+1);const radio=row.querySelector("input[type=radio]");if(radio)radio.value=String(index);});}window.addJudge=function(){const row=wrap.querySelector(".judge-row");if(!row)return;const clone=row.cloneNode(true);clone.querySelectorAll