<?php
declare(strict_types=1);
ob_start(static fn(string $html):string=>str_replace('</head>','<script defer src="../../public/assets/js/bdc-theme.js?v=505"></script></head>',$html));
$mode=(string)($_GET['mode']??'');$roundId=(int)($_GET['round_id']??$_POST['round_id']??0);$action=(string)($_POST['action']??'');
if($mode==='special'){header('Location: ?mode=manual'.($roundId?'&round_id='.$roundId:''));exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='create_round'&&in_array((string)($_POST['division']??''),['bachata_rising','bachata_open','bachata_invitational','salsa_rising','salsa_open'],true)){require __DIR__.'/integrated-special-create.php';exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='create_round'){require __DIR__.'/create-round-action.php';exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&in_array($action,['create_next_round','delete_scoring_workflow'],true)){require __DIR__.'/discipline-actions.php';exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='add_entry'&&$roundId){require_once dirname(__DIR__,2).'/bootstrap.php';try{$pdo=App\Core\Database::connection();$s=$pdo->prepare('SELECT dance_style FROM bdc_scoring_rounds WHERE id=:id');$s->execute(['id'=>$roundId]);if((string)$s->fetchColumn()==='salsa'){require __DIR__.'/discipline-actions.php';exit;}}catch(Throwable){}}
if($_SERVER['REQUEST_METHOD']==='GET'&&$mode===''&&!$roundId){require dirname(__DIR__,2).'/bootstrap.php';App\Core\Auth::requireAdmin();?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jack &amp; Jill Scoring | BDC</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="../../public/css/scoring-premium.css?v=275" rel="stylesheet"><style>body{min-height:100vh;background:#f4f6f9}.mode-shell{max-width:1200px}.mode-card{height:100%;border:1px solid #dfe3e8;border-radius:18px;box-shadow:0 10px 28px rgba(15,23,42,.07)}.mode-icon{display:grid;width:58px;height:58px;place-items:center;border-radius:15px;background:#111827;color:#fff;font-size:1.7rem}</style></head><body><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="../">BDC Admin</a><a class="btn btn-outline-light btn-sm" href="../">Dashboard</a></div></nav><main class="container mode-shell py-5"><div class="text-center mb-5"><div class="text-primary fw-bold text-uppercase small mb-2">Live Operations</div><h1 class="display-6 fw-bold">Jack &amp; Jill Scoring</h1><p class="text-muted mb-0">Choose Manual Scoring, Automatic Scoring or Live Projection. Existing events and scores remain available in both scoring modes.</p></div><div class="row g-4"><div class="col-lg-4"><section class="card mode-card"><div class="card-body p-4 d-flex flex-column"><div class="mode-icon mb-4">✎</div><h2 class="h3">Manual Scoring</h2><p class="text-muted flex-grow-1">Open the existing Manual scoring dashboard and all saved rounds.</p><a class="btn btn-dark btn-lg" href="?mode=manual">Continue</a></div></section></div><div class="col-lg-4"><section class="card mode-card"><div class="card-body p-4 d-flex flex-column"><div class="mode-icon mb-4">⚙</div><h2 class="h3">Automatic Scoring</h2><p class="text-muted flex-grow-1">Open judge links, live scoring progress and existing Automatic rounds.</p><a class="btn btn-primary btn-lg" href="?mode=automated">Continue</a></div></section></div><div class="col-lg-4"><section class="card mode-card border-danger"><div class="card-body p-4 d-flex flex-column"><div class="mode-icon mb-4">▣</div><h2 class="h3">Live Projection</h2><p class="text-muted flex-grow-1">Open the existing Live Scoreboard and projection controls.</p><a class="btn btn-danger btn-lg" target="_blank" rel="noopener" href="../live-screen/">Open Projector</a></div></section></div></div><div class="text-center mt-4"><a href="../">Dashboard</a> · <a href="../dance-cup/">Dance Cup Scoring</a> · <a href="../completed-events/">Completed Events</a></div></main></body></html><?php exit;}
if($_SERVER['REQUEST_METHOD']==='GET'&&$roundId===0&&in_array($mode,['manual','automated'],true)){require __DIR__.'/active-dashboard.php';exit;}
require_once dirname(__DIR__,2).'/bootstrap.php';App\Core\Auth::requireAdmin();
if(($_GET['judge_panel']??'')==='1'){require __DIR__.'/judge-control.php';exit;}
$guardPdo=App\Core\Database::connection();App\Services\ScoringPageGuardService::prepare($guardPdo,false);$reserve=str_repeat('x',262144);register_shutdown_function(static function()use(&$reserve,$mode,$roundId):void{$last=error_get_last();if(!$last||!in_array($last['type'],[E_ERROR,E_PARSE,E_CORE_ERROR,E_COMPILE_ERROR],true))return;$reserve='';if($_SERVER['REQUEST_METHOD']==='POST'&&$mode==='automated'&&$roundId>0&&!headers_sent()){$_SESSION['automatic_scoring_error']='Automatic scoring stopped: '.(string)($last['message']??'fatal server error');header('Location: automatic-round.php?round_id='.$roundId,true,303);return;}App\Services\ScoringPageGuardService::renderFatal($last,false);});set_exception_handler(static function(Throwable $e):void{App\Services\ScoringPageGuardService::renderFailure($e,false);});
if($_SERVER['REQUEST_METHOD']==='GET'&&$mode==='automated'&&$roundId>0){try{$s=$guardPdo->prepare('SELECT round_type FROM bdc_scoring_rounds WHERE id=:id');$s->execute(['id'=>$roundId]);if((string)$s->fetchColumn()!=='final'){header('Location: automatic-round.php?round_id='.$roundId);exit;}}catch(Throwable $e){App\Services\ScoringPageGuardService::renderFailure($e,false);}}
if($_SERVER['REQUEST_METHOD']==='POST'&&$mode==='automated'&&$roundId>0&&in_array($action,['settings','add_entry','update_bib','remove_entry'],true)){
 @ini_set('zlib.output_compression','0');
 try{require __DIR__.'/core.php';}
 catch(Throwable $e){App\Services\ScoringPageGuardService::renderFailure($e,false);}
 exit;
}
ob_start(static function(string $html):string{if(preg_match('/round_id=(\d+)/',$html,$m)){$id=(int)$m[1];$html=str_replace('href="publish.php?round_id='.$id.'"','href="publish-gate.php?round_id='.$id.'"',$html);if(!str_contains($html,'Live Screen / Projection Control')){$button='<a class="btn btn-danger btn-sm" target="_blank" rel="noopener" href="../live-screen/control.php?round_id='.$id.'">Live Screen / Projection Control</a>';$html=str_replace('<a class="btn btn-warning btn-sm" href="https://bachatadancecouncil.com/">BDC Home</a>',$button.'<a class="btn btn-warning btn-sm" href="https://bachatadancecouncil.com/">BDC Home</a>',$html);}}return$html;});
try{require __DIR__.'/core.php';}catch(Throwable $e){
 while(ob_get_level()>0)ob_end_clean();
 if($_SERVER['REQUEST_METHOD']==='POST'&&$mode==='automated'&&$roundId>0){
  $_SESSION['automatic_scoring_error']=$e->getMessage();
  header('Location: automatic-round.php?round_id='.$roundId,true,303);
  exit;
 }
 App\Services\ScoringPageGuardService::renderFailure($e,false);
}
