<?php
declare(strict_types=1);
ob_start();
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\LiveDisplaySessionService;
Auth::requireAdmin();
$respond=static function(array $payload,int $status=200):never{$leaked=(string)ob_get_clean();if($leaked!=='')error_log('BDC projector controller suppressed output: '.substr(strip_tags($leaked),0,500));http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);exit;};
if($_SERVER['REQUEST_METHOD']!=='POST'||!Csrf::verify($_POST['_csrf']??null))$respond(['ok'=>false,'error'=>'Invalid request.'],419);
$pdo=Database::connection();$eventId=(int)($_POST['event_id']??0);$sessionId=(int)($_POST['session_id']??0);$test=($_POST['data_mode']??'real')==='test';$userId=(int)(Auth::user()['id']??0);
try{$session=$sessionId>0?LiveDisplaySessionService::byId($pdo,$sessionId,$test):LiveDisplaySessionService::forEvent($pdo,$eventId,$test);if(!$session)throw new RuntimeException('Generate the Live Display link first.');$eventId=(int)$session['event_id'];$action=(string)($_POST['action']??'update');if($action==='prepare_holding')$session=LiveDisplaySessionService::beginSelection($pdo,$eventId,(int)($_POST['round_id']??0),$test,$userId);elseif($action==='unlock_results')$session=LiveDisplaySessionService::setResultsUnlocked($pdo,$eventId,$test,true,$userId);elseif($action==='lock_results')$session=LiveDisplaySessionService::setResultsUnlocked($pdo,$eventId,$test,false,$userId);elseif($action==='effect')$session=LiveDisplaySessionService::effect($pdo,$eventId,$test,(string)($_POST['effect_type']??'none'),$userId);else $session=LiveDisplaySessionService::update($pdo,$eventId,$test,$_POST,$userId);$respond(['ok'=>true,'session'=>['screen_type'=>$session['screen_type']??'holding','reveal_place'=>$session['reveal_place']??null,'effect_type'=>$session['effect_type']??null,'effect_version'=>(int)($session['effect_version']??0),'page_number'=>(int)($session['page_number']??1),'auto_page'=>(bool)($session['auto_page']??false),'page_delay_seconds'=>(int)($session['page_delay_seconds']??30),'loop_enabled'=>(bool)($session['loop_enabled']??false),'loop_screens'=>$session['loop_screens']??'','loop_delay_seconds'=>(int)($session['loop_delay_seconds']??15),'results_unlocked'=>(bool)($session['results_unlocked']??false),'state_version'=>(int)($session['state_version']??0)]]);}catch(Throwable $e){$respond(['ok'=>false,'error'=>$e->getMessage()],422);}
