<?php
declare(strict_types=1);require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\AiOperationsService;
Auth::requireSuperAdmin();$pdo=Database::connection();AiOperationsService::ensure($pdo);$mode=(string)($_GET['mode']??$_POST['mode']??'test');if(!in_array($mode,['test','live'],true))$mode='test';$error='';$notice='';$report=null;
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Csrf::verify($_POST['_csrf']??null))$error='Invalid security token.';else try{$type=(string)($_POST['report_type']??'');$report=AiOperationsService::generate($pdo,$mode,$type,(int)(Auth::user()['id']??0));$notice='AI report generated and saved.';Auth::audit((int)(Auth::user()['id']??0),'ai_report_generated',['mode'=>$mode,'type'=>$type],'ai_operations_report',$report['id']);}catch(Throwable $e){$error=$e->getMessage();}}
$snapshot=AiOperationsService::snapshot($pdo,$mode);$findings=AiOperationsService::findings($snapshot);$recent=AiOperationsService::recent($pdo,$mode);$types=AiOperationsService::types();$configured=AiOperationsService::configured();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Operations | BDC Admin</title><link rel="stylesheet" href="<?=e(url('public/assets/css/app.css?v=203'))?>"><style>body{background:#f1f5f8}.wrap{max-width:1250px;margin:auto;padding:20px}.card{background:white;border:1px solid #d7e0e8;border-radius:7px;padding:20px;margin-bottom:16px}.head{border-top:5px solid #2898d4}.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center;justify-content:space-between}.tabs a{display:inline-block;padding:10px 20px;border:1px solid #218dcc;text-decoration:none;color:#176a9b}.tabs a.on{background:#218dcc;color:#fff}.badge{padding:6px 10px;border-radius:14px;font-weight:700}.test{background:#fff0b5;color:#735400}.live,.ok{background:#d9f3e3;color:#176b38}.bad{background:#ffe0e0;color:#9d1c29}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(165px,1fr));gap:10px}.metric{background:#f7f9fb;border-left:4px solid #2997d1;padding:13px}.metric strong{display:block;font-size:25px}.finding{background:#fafafa;border-left:5px solid #f0b31d;padding:12px;margin:8px 0}.finding.critical{border-color:#d9363e}.finding.healthy{border-color:#2da85b}.report{white-space:pre-wrap;line-height:1.5;background:#f7f9fb;border:1px solid #d9e1e7;padding:16px}.muted{color:#5a6470}.alert{padding:12px;margin-bottom:14px}.err{background:#ffe3e3;color:#8d1622}.success{background:#ddf5e5;color:#176b38}.button{background:#218dcc;color:#fff;border:0;border-radius:4px;padding:11px 17px;font-weight:700}.button:disabled{opacity:.5}select{padding:10px;min-width:250px}table{width:100%;border-collapse:collapse}th,td{padding:9px;text-align:left;border-bottom:1px solid #e0e5e9}</style></head><body><main class="wrap"><section class="card head"><div class="row"><div><h1>AI Operations</h1><p class="muted">Reports, optimization suggestions, and portal monitoring.</p></div><a href="<?=e(url('admin/'))?>">← Dashboard</a></div><span class="badge <?=$mode==='test'?'test':'live'?>"><?=$mode==='test'?'TESTING DATA':'LIVE DATA'?></span> <span class="badge <?=$configured?'ok':'bad'?>"><?=$configured?'AI CONNECTED':'API KEY NOT CONFIGURED'?></span></section>
<?php if($error):?><div class="alert err"><?=e($error)?></div><?php endif;?><?php if($notice):?><div class="alert success"><?=e($notice)?></div><?php endif;?>
<section class="card"><h2>Data Environment</h2><div class="tabs"><a class="<?=$mode==='test'?'on':''?>" href="?mode=test">Testing</a><a class="<?=$mode==='live'?'on':''?>" href="?mode=live">Live</a></div><p class="muted">Testing and Live are isolated. AI receives aggregate counts only—never names, contact details, BDC IDs, judge identities, or raw scores.</p></section>
<section class="card"><h2>Operational Health</h2><div class="metrics"><?php foreach($snapshot['metrics'] as $key=>$value):?><div class="metric"><span><?=e(ucwords(str_replace('_',' ',$key)))?></span><strong><?=$value===null?'—':(int)$value?></strong></div><?php endforeach;?></div><h3>Monitor Findings</h3><?php foreach($findings as $f):?><div class="finding <?=e($f['level'])?>"><strong><?=e($f['title'])?></strong><div><?=e($f['detail'])?></div></div><?php endforeach;?></section>
<section class="card"><h2>Generate AI Report</h2><p class="muted">Advisory only: AI cannot edit competitors, judging, scores, results, or settings.</p><form method="post"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="mode" value="<?=e($mode)?>"><select name="report_type"><?php foreach($types as $key=>$label):?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select> <button class="button" <?=$configured?'':'disabled'?>>Generate &amp; Save</button></form><?php if(!$configured):?><p class="alert err">Configure <code>OPENAI_API_KEY</code> in the Bluehost server environment. Never enter the key into this dashboard or commit it to GitHub.</p><?php endif;?></section>
<?php if($report):?><section class="card"><h2>New Report</h2><div class="report"><?=e($report['report_text'])?></div></section><?php endif;?><section class="card"><h2>Saved Reports · <?=e(ucfirst($mode))?></h2><?php if(!$recent):?><p class="muted">No reports saved yet.</p><?php else:?><div style="overflow:auto"><table><thead><tr><th>Date</th><th>Type</th><th>Model</th><th>Admin</th><th>Report</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?=e($r['created_at'])?></td><td><?=e($types[$r['report_type']]??$r['report_type'])?></td><td><?=e($r['model'])?></td><td><?=e($r['generated_by_name']??'Admin')?></td><td><details><summary>View</summary><div class="report"><?=e($r['report_text'])?></div></details></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></main></body></html>
