<?php
declare(strict_types=1);

register_shutdown_function(static function()use($pdo):void{
    if($_SERVER['REQUEST_METHOD']!=='POST'||($_POST['action']??'')!=='approve')return;$requestId=(int)($_POST['request_id']??0);if($requestId<1)return;
    try{$request=$pdo->prepare("SELECT competitor_id,payload_json FROM bdc_profile_requests WHERE id=:id AND status='approved'");$request->execute(['id'=>$requestId]);$row=$request->fetch();$payload=$row?json_decode((string)$row['payload_json'],true):null;if(!$row||!is_array($payload)||($payload['competition_type']??'')!=='dance_cup'||(int)$row['competitor_id']<1)return;
        $details=$pdo->prepare('SELECT dance_style,entry_type,competition_level,partner_or_team_name,team_size,competitor_gender FROM bdc_profile_request_dance_cup_categories WHERE request_id=:request');$details->execute(['request'=>$requestId]);$profiles=$details->fetchAll();if(!$profiles)return;$competitorId=(int)$row['competitor_id'];$gender=(string)$profiles[0]['competitor_gender'];if(in_array($gender,['male','female','non_binary','prefer_not_to_say'],true))$pdo->prepare('UPDATE bdc_competitors SET gender=:gender WHERE id=:id')->execute(['gender'=>$gender,'id'=>$competitorId]);
        $save=$pdo->prepare("INSERT INTO bdc_competitor_dance_cup_profiles(competitor_id,dance_style,entry_type,competition_level,partner_or_team_name,team_size,source_request_id,status) VALUES(:competitor,:style,:entry,:level,:partner,:team_size,:request,'active') ON DUPLICATE KEY UPDATE partner_or_team_name=VALUES(partner_or_team_name),team_size=VALUES(team_size),source_request_id=VALUES(source_request_id),status='active'");foreach($profiles as $profile)$save->execute(['competitor'=>$competitorId,'style'=>$profile['dance_style'],'entry'=>$profile['entry_type'],'level'=>$profile['competition_level'],'partner'=>$profile['partner_or_team_name'],'team_size'=>$profile['team_size'],'request'=>$requestId]);
    }catch(Throwable $exception){error_log('Dance Cup profile approval sync failed: '.$exception->getMessage());}
});

ob_start(static function(string $html)use($pdo,&$status):string{
    try{$where=$status==='all'?'':' AND r.status=:status';$q=$pdo->prepare("SELECT r.id,r.full_name,d.competitor_gender,d.dance_style,d.entry_type,d.competition_level,d.partner_or_team_name,d.team_size FROM bdc_profile_request_dance_cup_categories d JOIN bdc_profile_requests r ON r.id=d.request_id WHERE 1=1{$where} ORDER BY r.created_at DESC,r.id DESC,d.dance_style,d.entry_type,d.competition_level");$q->execute($status==='all'?[]:['status'=>$status]);$rows=$q->fetchAll();if(!$rows)return $html;
        $summary='<section class="card border-primary shadow-sm mb-4"><div class="card-body"><h2 class="h5">BDC Dance Cup registration profiles</h2><p class="text-muted small">Reusable eligibility only. Events and category gender rules are assigned later in the scoring workspace.</p><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Request</th><th>Competitor</th><th>Gender</th><th>Style</th><th>Format</th><th>Level</th><th>Partner / Team</th></tr></thead><tbody>';
        foreach($rows as $row){$partner=(string)($row['partner_or_team_name']?:'—');if($row['team_size'])$partner.=' · '.(int)$row['team_size'].' dancers';$summary.='<tr><td>#'.(int)$row['id'].'</td><td>'.e((string)$row['full_name']).'</td><td>'.e(ucwords(str_replace('_',' ',(string)$row['competitor_gender']))).'</td><td>'.e(ucwords(str_replace('_',' ',(string)$row['dance_style']))).'</td><td>'.e(ucwords(str_replace('_',' ',(string)$row['entry_type']))).'</td><td>'.e(ucwords(str_replace('_',' ',(string)$row['competition_level']))).'</td><td>'.e($partner).'</td></tr>';}
        return str_replace('<div class="btn-group flex-wrap mb-4">',$summary.'</tbody></table></div></div></section><div class="btn-group flex-wrap mb-4">',$html);
    }catch(Throwable $ignored){return $html;}
});
