<?php
declare(strict_types=1);

return static function(PDO $pdo):void{
    $has=static function(string $table,string $column)use($pdo):bool{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table AND COLUMN_NAME=:column');$q->execute(['table'=>$table,'column'=>$column]);return (int)$q->fetchColumn()>0;};
    if(!$has('bdc_competitors','gender'))$pdo->exec("ALTER TABLE bdc_competitors ADD gender ENUM('male','female','non_binary','prefer_not_to_say','unknown') NOT NULL DEFAULT 'unknown' AFTER country");
    if(!$has('bdc_profile_request_dance_cup_categories','competitor_gender'))$pdo->exec("ALTER TABLE bdc_profile_request_dance_cup_categories MODIFY event_name VARCHAR(190) NULL, MODIFY category_name VARCHAR(190) NULL, ADD competitor_gender VARCHAR(30) NOT NULL DEFAULT 'unknown' AFTER team_size");
    $pdo->exec("CREATE TABLE IF NOT EXISTS bdc_competitor_dance_cup_profiles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,competitor_id BIGINT UNSIGNED NOT NULL,dance_style VARCHAR(80) NOT NULL,entry_type VARCHAR(20) NOT NULL,competition_level VARCHAR(30) NOT NULL,partner_or_team_name VARCHAR(190) NULL,team_size INT UNSIGNED NULL,source_request_id BIGINT UNSIGNED NULL,status ENUM('active','archived') NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_competitor_dc_profile(competitor_id,dance_style,entry_type,competition_level),INDEX idx_competitor_dc_lookup(dance_style,entry_type,competition_level,status),CONSTRAINT fk_competitor_dc_profile FOREIGN KEY(competitor_id) REFERENCES bdc_competitors(id) ON DELETE CASCADE,CONSTRAINT fk_competitor_dc_request FOREIGN KEY(source_request_id) REFERENCES bdc_profile_requests(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    foreach(['bdc_dance_cup_competitions','bdc_test_dance_cup_competitions'] as $table)if(!$has($table,'gender_eligibility'))$pdo->exec("ALTER TABLE {$table} ADD gender_eligibility ENUM('mixed','female_only','male_only') NOT NULL DEFAULT 'mixed' AFTER competition_level");
};
