<?php
declare(strict_types=1);
return static function(PDO $pdo):void{
 $has=function(string $table,string $column)use($pdo):bool{$s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t AND COLUMN_NAME=:c');$s->execute(['t'=>$table,'c'=>$column]);return(bool)$s->fetchColumn();};
 if(!$has('bdc_competitors','original_photo_url'))$pdo->exec('ALTER TABLE bdc_competitors ADD original_photo_url VARCHAR(1000) NULL AFTER photo_url');
 if(!$has('bdc_scoring_rounds','scoring_mode'))$pdo->exec("ALTER TABLE bdc_scoring_rounds ADD scoring_mode ENUM('manual','automated') NOT NULL DEFAULT 'manual' AFTER round_type");
 $pdo->exec("CREATE TABLE IF NOT EXISTS bdc_competitor_link_suggestions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,competitor_a_id BIGINT UNSIGNED NOT NULL,competitor_b_id BIGINT UNSIGNED NOT NULL,match_reason VARCHAR(100) NOT NULL,confidence ENUM('certain','review') NOT NULL DEFAULT 'review',status ENUM('pending','approved','rejected','auto_linked') NOT NULL DEFAULT 'pending',reviewed_by BIGINT UNSIGNED NULL,reviewed_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE INDEX uq_link_pair(competitor_a_id,competitor_b_id),INDEX idx_link_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS bdc_two_factor_codes(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,code_hash CHAR(64) NOT NULL,expires_at DATETIME NOT NULL,attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,used_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_2fa_user(user_id,expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS bdc_trusted_devices(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,selector CHAR(24) NOT NULL UNIQUE,token_hash CHAR(64) NOT NULL,user_agent_hash CHAR(64) NOT NULL,expires_at DATETIME NOT NULL,last_used_at DATETIME NULL,revoked_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_trusted_user(user_id,expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
};
