<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';

use App\Core\Auth;
use App\Core\Database;

Auth::requirePermission('competitors.view');
$pdo=Database::connection();
$error='';
$tableExists=static function(string $table)use($pdo):bool{try{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table');$q->execute(['table'=>$table]);return (int)$q->fetchColumn()>0;}catch(Throwable){return false;}};
$columnExists=static function(string $table,string $column)use($pdo):bool{try{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table AND COLUMN_NAME=:column');$q->execute(['table'=>$table,'column'=>$column]);return (int)$q->fetchColumn()>0;}catch(Throwable){return false;}};
$requestsReady=$tableExists('bdc_profile_request_dance_cup_categories')&&$tableExists('bdc_profile_requests');
$profilesReady=$tableExists('bdc_competitor_dance_cup_profiles');
$historyReady=$tableExists('bdc_dance_cup_result_history')&&$columnExists('bdc_dance_cup_result_history','competitor_id')&&$columnExists('bdc_dance_cup_result_history','event_id')&&$columnExists('bdc_dance_cup_result_history','placement')&&$columnExists('bdc_dance_cup_result_history','approved_at');
$genderReady=$columnExists('bdc_competitors','gender');
$categoryStatusReady=$columnExists('bdc_profile_request_dance_cup_categories','registration_status');
$q=trim((string)($_GET['q']??''));$style=(string)($_GET['style']??'');$entry=(string)($_GET['entry']??'');$level=(string)($_GET['level']??'');$registrationStatus=(string)($_GET['registration_status']??'');$registration_status=$registrationStatus;
$registrationRows=[];$profileRows=[];$counts=['people'=>0,'requests'=>0,'profiles'=>0,'published'=>0,'winners'=>0];

try{
    if($requestsReady){
        $where=['1=1'];$params=[];
        if($q!==''){$where[]='(r.full_name LIKE :q OR r.instagram LIKE :q OR c.bdc_id LIKE :q OR d.partner_or_team_name LIKE :q)';$params['q']='%'.$q.'%';}
        if(in_array($style,['salsa','bachata','cha_cha','other'],true)){$where[]='d.dance_style=:style';$params['style']=$style;}
        if(in_array($entry,['solo','couple','pro_am','team'],true)){$where[]='d.entry_type=:entry';$params['entry']=$entry;}
        if(in_array($level,['open','amateur','intermediate','professional'],true)){$where[]='d.competition_level=:level';$params['level']=$level;}
        if($categoryStatusReady&&in_array($registrationStatus,['submitted','under_review','approved','rejected'],true)){$where[]='d.registration_status=:registration_status';$params['registration_status']=$registrationStatus;}
        $categoryStatusSelect=$categoryStatusReady?'d.registration_status':'\'submitted\'';
        $sql="SELECT d.id category_request_id,d.request_id,d.dance_style,d.entry_type,d.competition_level,d.partner_or_team_name,d.team_size,d.competitor_gender,{$categoryStatusSelect} registration_status,r.full_name,r.instagram,r.country,r.created_at,r.competitor_id,c.bdc_id FROM bdc_profile_request_dance_cup_categories d JOIN bdc_profile_requests r ON r.id=d.request_id LEFT JOIN bdc_competitors c ON c.id=r.competitor_id WHERE ".implode(' AND ',$where)." ORDER BY r.created_at DESC,r.id DESC,d.dance_style,d.entry_type,d.competition_level";
        $stmt=$pdo->prepare($sql);$stmt->execute($params);$registrationRows=$stmt->fetchAll();
        $counts['people']=(int)$pdo->query('SELECT COUNT(DISTINCT request_id) FROM bdc_profile_request_dance_cup_categories')->fetchColumn();
        $counts['requests']=(int)$pdo->query('SELECT COUNT(*) FROM bdc_profile_request_dance_cup_categories')->fetchColumn();
    }
    if($profilesReady){
        $genderSelect=$genderReady?'c.gender':'NULL gender';
        $stmt=$pdo->query("SELECT p.*,c.bdc_id,c.exact_name,c.instagram,c.country,{$genderSelect},c.photo_url FROM bdc_competitor_dance_cup_profiles p JOIN bdc_competitors c ON c.id=p.competitor_id WHERE p.status='active' ORDER BY c.exact_name,p.dance_style,p.entry_type,p.competition_level");
        $profileRows=$stmt->fetchAll();$counts['profiles']=count($profileRows);
    }
    if($historyReady){$counts['published']=(int)$pdo->query('SELECT COUNT(*) FROM bdc_dance_cup_result_history')->fetchColumn();$counts['winners']=(int)$pdo->query('SELECT COUNT(*) FROM bdc_dance_cup_result_history WHERE placement=1')->fetchColumn();}
}catch(Throwable $exception){$error='Some Dance Cup dashboard data could not be loaded: '.$exception->getMessage();}

$label=static fn(?string $value):string=>ucwords(str_replace('_',' ',(string)$value));
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dance Cup Participants | BDC</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="../../public/css/scoring-premium.css?v=449" rel="stylesheet"><script defer src="../../public/assets/js/bdc-theme.js?v=420"></script><style>.summary-card{border:0;border-radius:16px}.summary-card strong{font-size:1.8rem}.dc-photo{width:52px;height:62px;object-fit:cover;border-radius:9px}.dc-section{border:0;border-radius:16px}.table td,.table th{vertical-align:middle}.status-submitted,.status-under_review{background:#fff3cd;color:#664d03}.status-approved{background:#d1e7dd;color:#0f5132}.status-rejected{background:#f8d7da;color:#842029}</style></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="./">BDC Dance Cup</a><div class="d-flex gap-2"><a class="btn btn-outline-light btn-sm" href="approvals.php">Approvals</a><a class="btn btn-outline-light btn-sm" href="workflow.php?workflow=automatic">Scoring</a><a class="btn btn-light btn-sm" href="../">Dashboard</a></div></div></nav><main class="container-fluid py-4" style="max-width:1650px"><div class="mb-3"><h1 class="h3 mb-1">Dance Cup Participant Management</h1><p class="text-muted mb-0">Registration categories appear immediately. Approved reusable profiles and published history remain separate.</p></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if(!$requestsReady):?><div class="alert alert-warning">The Dance Cup registration-category migration has not completed yet.</div><?php endif;?><div class="row g-3 mb-4"><?php foreach(['All Participants'=>$counts['people'],'Registration Categories'=>$counts['requests'],'Active Profiles'=>$counts['profiles'],'Published Results'=>$counts['published'],'Winning Results'=>$counts['winners']] as $title=>$value):?><div class="col-6 col-xl"><section class="card summary-card shadow-sm h-100"><div class="card-body"><span class="text-muted small"><?=e($title)?></span><strong class="d-block"><?=$value?></strong></div></section></div><?php endforeach;?></div>

<form class="card dc-section shadow-sm mb-4"><div class="card-body"><div class="row g-2"><div class="col-lg-4"><label class="form-label small">Search registrations</label><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Name, BDC ID, Instagram, partner or team"></div><?php foreach(['style'=>['Dance Style',[''=>'All styles','salsa'=>'Salsa','bachata'=>'Bachata','cha_cha'=>'Cha Cha','other'=>'Other']],'entry'=>['Entry Type',[''=>'All entry types','solo'=>'Solo','couple'=>'Couple','pro_am'=>'Pro Am','team'=>'Team']],'level'=>['Level',[''=>'All levels','open'=>'Open','amateur'=>'Amateur','intermediate'=>'Intermediate','professional'=>'Professional']],'registration_status'=>['Registration Status',[''=>'All statuses','submitted'=>'Submitted','under_review'=>'Under Review','approved'=>'Approved','rejected'=>'Rejected']]] as $name=>[$title,$options]):?><div class="col-6 col-lg-2"><label class="form-label small"><?=e($title)?></label><select class="form-select" name="<?=$name?>"><?php foreach($options as $value=>$text):?><option value="<?=e($value)?>" <?=($$name===$value)?'selected':''?>><?=e($text)?></option><?php endforeach;?></select></div><?php endforeach;?><div class="col-12"><button class="btn btn-dark">Apply Filters</button> <a class="btn btn-outline-secondary" href="participants.php">Reset</a></div></div></div></form>

<section class="card dc-section shadow-sm mb-4"><div class="card-body"><div class="d-flex justify-content-between gap-2 flex-wrap"><div><h2 class="h4 mb-1">Registration Categories</h2><p class="text-muted">These are the default categories selected on the public registration form. Registration status is independent from profile or identity review.</p></div><span class="badge text-bg-primary align-self-start"><?=count($registrationRows)?> shown</span></div></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Submitted</th><th>BDC ID</th><th>Participant</th><th>Gender</th><th>Dance Style</th><th>Entry Type</th><th>Level</th><th>Partner / Team</th><th>Registration</th></tr></thead><tbody><?php foreach($registrationRows as $row):?><tr><td><small><?=e((string)$row['created_at'])?></small></td><td><?=e($row['bdc_id']?:'Pending assignment')?></td><td><strong><?=e($row['full_name']?:'Name pending')?></strong><small class="d-block text-muted"><?=e($row['instagram']?'@'.$row['instagram']:'—')?></small></td><td><?=e($label($row['competitor_gender']))?></td><td><span class="badge text-bg-primary"><?=e($label($row['dance_style']))?></span></td><td><?=e($label($row['entry_type']))?></td><td><strong><?=e($label($row['competition_level']))?></strong></td><td><?=e($row['partner_or_team_name']?:'—')?><?=$row['team_size']?'<small class="d-block">'.(int)$row['team_size'].' dancers</small>':''?></td><td><span class="badge status-<?=e((string)$row['registration_status'])?>"><?=e($label($row['registration_status']))?></span></td></tr><?php endforeach;?><?php if(!$registrationRows):?><tr><td colspan="9" class="text-center text-muted py-5">No registration categories match these filters.</td></tr><?php endif;?></tbody></table></div></section>

<section class="card dc-section shadow-sm"><div class="card-body"><h2 class="h4 mb-1">Approved Reusable Profiles</h2><p class="text-muted">Created only after an administrator approves the registration request.</p></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Photo</th><th>BDC ID</th><th>Participant</th><th>Country / Gender</th><th>Dance Style</th><th>Entry Type</th><th>Level</th><th>Partner / Team</th></tr></thead><tbody><?php foreach($profileRows as $row):?><tr><td><img class="dc-photo" src="<?=e($row['photo_url']?:url('public/assets/img/default-competitor.svg'))?>" alt=""></td><td><a href="../competitors/edit.php?id=<?=(int)$row['competitor_id']?>"><?=e($row['bdc_id'])?></a></td><td><strong><?=e($row['exact_name'])?></strong><small class="d-block text-muted"><?=e($row['instagram']?'@'.$row['instagram']:'—')?></small></td><td><?=e($row['country']?:'—')?><small class="d-block text-muted"><?=e($label($row['gender']??'unknown'))?></small></td><td><span class="badge text-bg-primary"><?=e($label($row['dance_style']))?></span></td><td><?=e($label($row['entry_type']))?></td><td><strong><?=e($label($row['competition_level']))?></strong></td><td><?=e($row['partner_or_team_name']?:'—')?><?=$row['team_size']?'<small class="d-block">'.(int)$row['team_size'].' dancers</small>':''?></td></tr><?php endforeach;?><?php if(!$profileRows):?><tr><td colspan="8" class="text-center text-muted py-5">No approved reusable profiles yet. Pending categories remain visible above.</td></tr><?php endif;?></tbody></table></div></section></main></body></html>
