<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';

use App\Core\Auth;
use App\Core\Database;

Auth::requirePermission('competitors.view');
$pdo=Database::connection();
$error='';
$tableExists=static function(string $table)use($pdo):bool{try{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table');$q->execute(['table'=>$table]);return (int)$q->fetchColumn()>0;}catch(Throwable){return false;}};
$columnExists=static function(string $table,string $column)use($pdo):bool{try{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table AND COLUMN_NAME=:column');$q->execute(['table'=>$table,'column'=>$column]);return (int)$q->fetchColumn()>0;}catch(Throwable){return false;}};
$requestsReady=$tableExists('bdc_profile_request_dance_cup_categories')&&$tableExists('bdc_profile_requests');
$genderReady=$columnExists('bdc_competitors','gender');
$categoryStatusReady=$columnExists('bdc_profile_request_dance_cup_categories','registration_status');
$q=trim((string)($_GET['q']??''));$style=(string)($_GET['style']??'');$entry=(string)($_GET['entry']??'');$level=(string)($_GET['level']??'');
$registrationRows=[];$counts=['people'=>0,'entries'=>0,'profiles'=>0,'setup'=>0];

try{
    if($requestsReady){
        $where=[$categoryStatusReady?"(d.registration_status IS NULL OR d.registration_status<>'rejected')":'1=1'];$params=[];
        if($q!==''){$where[]='(r.full_name LIKE :q OR r.instagram LIKE :q OR c.bdc_id LIKE :q OR d.partner_or_team_name LIKE :q)';$params['q']='%'.$q.'%';}
        if(in_array($style,['salsa','bachata','cha_cha','other'],true)){$where[]='d.dance_style=:style';$params['style']=$style;}
        if(in_array($entry,['solo','couple','pro_am','team'],true)){$where[]='d.entry_type=:entry';$params['entry']=$entry;}
        if(in_array($level,['open','amateur','intermediate','professional'],true)){$where[]='d.competition_level=:level';$params['level']=$level;}
        $genderSelect=$genderReady?'c.gender':'NULL';
        $sql="SELECT d.id category_request_id,d.request_id,d.dance_style,d.entry_type,d.competition_level,d.partner_or_team_name,d.team_size,COALESCE({$genderSelect},d.competitor_gender) competitor_gender,r.full_name,r.instagram,r.country,r.photo_url request_photo,r.created_at,r.competitor_id,c.bdc_id,c.exact_name,c.photo_url FROM bdc_profile_request_dance_cup_categories d JOIN bdc_profile_requests r ON r.id=d.request_id LEFT JOIN bdc_competitors c ON c.id=r.competitor_id WHERE ".implode(' AND ',$where)." ORDER BY (r.competitor_id IS NOT NULL) DESC,r.created_at DESC,r.id DESC,d.dance_style,d.entry_type,d.competition_level";
        $stmt=$pdo->prepare($sql);$stmt->execute($params);$rawRows=$stmt->fetchAll();$seen=[];
        foreach($rawRows as $row){$identity=strtolower(trim((string)($row['instagram']?:$row['full_name'])));$identity=preg_replace('/[^a-z0-9]+/','',$identity)?:('request'.(int)$row['request_id']);$key=implode('|',[$identity,$row['dance_style'],$row['entry_type'],$row['competition_level'],strtolower(trim((string)$row['partner_or_team_name']))]);if(isset($seen[$key]))continue;$seen[$key]=true;$registrationRows[]=$row;}
        $people=[];$linked=[];$setup=[];foreach($registrationRows as $row){$personKey=(string)($row['competitor_id']?:strtolower(trim((string)($row['instagram']?:$row['full_name']))));$people[$personKey]=true;if((int)$row['competitor_id']>0)$linked[$personKey]=true;else$setup[$personKey]=true;}
        $counts['people']=count($people);$counts['entries']=count($registrationRows);$counts['profiles']=count($linked);$counts['setup']=count($setup);
    }
}catch(Throwable $exception){$error='Some Dance Cup dashboard data could not be loaded: '.$exception->getMessage();}

$label=static fn(?string $value):string=>ucwords(str_replace('_',' ',(string)$value));
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dance Cup Participants | BDC</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="../../public/css/scoring-premium.css?v=487" rel="stylesheet"><script defer src="../../public/assets/js/bdc-theme.js?v=505"></script><style>.summary-card{border:0;border-radius:16px}.summary-card strong{font-size:1.8rem}.dc-photo{width:58px;height:68px;object-fit:cover;border-radius:10px;border:1px solid #dce3ec}.dc-section{border:0;border-radius:18px}.table td,.table th{vertical-align:middle}.dc-actions{display:flex;gap:6px;flex-wrap:wrap}.dc-setup-note{color:#8a640e;font-size:.75rem;font-weight:700}@media(max-width:767px){.dc-actions{display:grid}.dc-actions .btn{width:100%}}</style></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="./">BDC Dance Cup</a><div class="d-flex gap-2"><a class="btn btn-outline-light btn-sm" href="workflow.php?workflow=automatic">Scoring</a><a class="btn btn-light btn-sm" href="../">Dashboard</a></div></div></nav><main class="container-fluid py-4" style="max-width:1650px"><div class="mb-3"><h1 class="h3 mb-1">Dance Cup Participants</h1><p class="text-muted mb-0">Participation details, competitor profiles and photos in one place.</p></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if(!$requestsReady):?><div class="alert alert-warning">Dance Cup participation data is not available yet.</div><?php endif;?><div class="row g-3 mb-4"><?php foreach(['Participants'=>$counts['people'],'Participation Entries'=>$counts['entries'],'Linked Profiles'=>$counts['profiles'],'Profiles To Set Up'=>$counts['setup']] as $title=>$value):?><div class="col-6 col-xl-3"><section class="card summary-card shadow-sm h-100"><div class="card-body"><span class="text-muted small"><?=e($title)?></span><strong class="d-block"><?=$value?></strong></div></section></div><?php endforeach;?></div>

<form class="card dc-section shadow-sm mb-4"><div class="card-body"><div class="row g-2 align-items-end"><div class="col-lg-5"><label class="form-label small">Search participants</label><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Name, BDC ID, Instagram, partner or team"></div><?php foreach(['style'=>['Dance Style',[''=>'All styles','salsa'=>'Salsa','bachata'=>'Bachata','cha_cha'=>'Cha Cha','other'=>'Other']],'entry'=>['Entry Type',[''=>'All entry types','solo'=>'Solo','couple'=>'Couple','pro_am'=>'Pro Am','team'=>'Team']],'level'=>['Level',[''=>'All levels','open'=>'Open','amateur'=>'Amateur','intermediate'=>'Intermediate','professional'=>'Professional']]] as $name=>[$title,$options]):?><div class="col-6 col-lg"><label class="form-label small"><?=e($title)?></label><select class="form-select" name="<?=$name?>"><?php foreach($options as $value=>$text):?><option value="<?=e($value)?>" <?=($$name===$value)?'selected':''?>><?=e($text)?></option><?php endforeach;?></select></div><?php endforeach;?><div class="col-12"><button class="btn btn-dark">Apply Filters</button> <a class="btn btn-outline-secondary" href="participants.php">Reset</a></div></div></div></form>

<section class="card dc-section shadow-sm"><div class="card-body d-flex justify-content-between gap-2 flex-wrap"><div><h2 class="h4 mb-1">Dance Participation</h2><p class="text-muted mb-0">One row for each participant and category. Duplicate submissions are consolidated.</p></div><span class="badge text-bg-primary align-self-start"><?=count($registrationRows)?> shown</span></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Photo</th><th>BDC ID</th><th>Participant</th><th>Country / Gender</th><th>Dance Style</th><th>Entry Type</th><th>Level</th><th>Partner / Team</th><th>Profile Actions</th></tr></thead><tbody><?php foreach($registrationRows as $row):$competitorId=(int)$row['competitor_id'];$return='../dance-cup/participants.php';?><tr><td><img class="dc-photo" src="<?=e($row['photo_url']?:$row['request_photo']?:url('public/assets/img/default-competitor.svg'))?>" alt=""></td><td><?=e($row['bdc_id']?:'Not assigned')?></td><td><strong><?=e($row['exact_name']?:$row['full_name']?:'Name pending')?></strong><small class="d-block text-muted"><?=e($row['instagram']?'@'.$row['instagram']:'—')?></small></td><td><?=e($row['country']?:'—')?><small class="d-block text-muted"><?=e($label($row['competitor_gender']))?></small></td><td><span class="badge text-bg-primary"><?=e($label($row['dance_style']))?></span></td><td><?=e($label($row['entry_type']))?></td><td><strong><?=e($label($row['competition_level']))?></strong></td><td><?=e($row['partner_or_team_name']?:'—')?><?=$row['team_size']?'<small class="d-block">'.(int)$row['team_size'].' dancers</small>':''?></td><td><?php if($competitorId):?><div class="dc-actions"><a class="btn btn-sm btn-dark" href="../competitors/edit.php?id=<?=$competitorId?>&amp;return=<?=e(rawurlencode($return))?>">Edit Profile</a><a class="btn btn-sm btn-outline-primary" href="../competitors/photo-adjust.php?id=<?=$competitorId?>&amp;return=<?=e(rawurlencode($return))?>">Adjust Photo</a></div><?php else:?><span class="dc-setup-note">Profile not linked yet</span><?php endif;?></td></tr><?php endforeach;?><?php if(!$registrationRows):?><tr><td colspan="9" class="text-center text-muted py-5">No Dance Cup participation matches these filters.</td></tr><?php endif;?></tbody></table></div></section></main></body></html>
