<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;
Auth::requirePermission('competitors.edit');$pdo=Database::connection();$id=(int)($_GET['id']??$_POST['id']??0);
$stmt=$pdo->prepare('SELECT id,identity_code,display_name,entry_type,solo_competitor_id,photo_url FROM bdc_wdc_identities WHERE id=:id');$stmt->execute(['id'=>$id]);$row=$stmt->fetch();if(!$row){http_response_code(404);exit('WDC competitor not found.');}$error='';$sharedPhoto='';
if((int)($row['solo_competitor_id']??0)>0){try{$shared=$pdo->prepare('SELECT photo_url FROM bdc_competitors WHERE id=:id');$shared->execute(['id'=>(int)$row['solo_competitor_id']]);$sharedPhoto=trim((string)$shared->fetchColumn());}catch(Throwable $ignored){}}
if($_SERVER['REQUEST_METHOD']==='POST'){try{if(!Csrf::verify($_POST['_csrf']??null))throw new RuntimeException('Invalid security token. Refresh and try again.');$file=$_FILES['photo']??null;if(!$file||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Choose a JPG, PNG or WebP photo.');if((int)($file['size']??0)>8*1024*1024)throw new RuntimeException('Photo must be under 8 MB.');$temporary=(string)($file['tmp_name']??'');$mime='';if(class_exists('finfo'))$mime=(string)(new finfo(FILEINFO_MIME_TYPE))->file($temporary);elseif(function_exists('mime_content_type'))$mime=(string)mime_content_type($temporary);$types=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($types[$mime]))throw new RuntimeException('Photo must be a valid JPG, PNG or WebP image.');$directory=dirname(__DIR__,2).'/uploads/wdc';if(!is_dir($directory)&&!mkdir($directory,0755,true)&&!is_dir($directory))throw new RuntimeException('Photo upload folder is unavailable.');$filename='wdc-'.$id.'-'.bin2hex(random_bytes(6)).'.'.$types[$mime];if(!move_uploaded_file($temporary,$directory.'/'.$filename))throw new RuntimeException('Photo could not be uploaded.');$photo=url('uploads/wdc/'.$filename);$pdo->prepare('UPDATE bdc_wdc_identities SET photo_url=:photo WHERE id=:id')->execute(['photo'=>$photo,'id'=>$id]);Auth::audit((int)(Auth::user()['id']??0),'wdc_photo_replaced',[],'wdc_identity',$id);header('Location: competitors.php#wdc-'.$id,true,303);exit;}catch(Throwable $exception){$error=$exception->getMessage();}}
$photo=trim((string)$row['photo_url']);if($photo==='')$photo=$sharedPhoto;
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Adjust WDC Photo</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="<?=e(url('public/assets/css/app.css'))?>" rel="stylesheet"></head><body class="bg-light"><main class="container py-4" style="max-width:700px"><div class="d-flex justify-content-between align-items-center gap-3 mb-3"><div><h1 class="h3 mb-1">Adjust WDC photo</h1><p class="text-muted mb-0"><?=e($row['identity_code'])?> · <?=e($row['display_name'])?></p></div><a class="btn btn-outline-dark" href="competitors.php#wdc-<?=$id?>">Back</a></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post" enctype="multipart/form-data" class="card border-0 shadow-sm"><div class="card-body"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="id" value="<?=$id?>"><img src="<?=e($photo!==''?$photo:url('public/assets/img/default-competitor.svg'))?>" alt="" style="width:180px;height:220px;object-fit:cover;border-radius:16px" class="mb-3 d-block"><label class="form-label" for="wdcPhoto">Replacement photo</label><input class="form-control" id="wdcPhoto" type="file" name="photo" accept="image/jpeg,image/png,image/webp" required><div class="form-text">Updates this WDC identity only. It never creates or changes a BDC or SDC ID. Maximum 8 MB.</div></div><div class="card-footer bg-white text-end"><button class="btn btn-primary">Upload WDC photo</button></div></form></main></body></html>
