<?php
declare(strict_types=1);
$token=preg_replace('/[^a-f0-9]/','',(string)($_GET['token']??''));
$test=(string)($_GET['data_mode']??'')==='test';
if(strlen($token)!==64){http_response_code(404);exit('Projector link not found.');}
?><!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>BDC Dance Cup Live Display</title>
<style>
:root{--bg:#08111f;--bg2:#5b1833;--text:#fff;--muted:#d9c9d1;--card:rgba(255,255,255,.09);--line:rgba(255,255,255,.2);--accent:#e5bd59;--good:#35c978;--warn:#efbd4d;--danger:#ef596f}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;font-family:Inter,Arial,sans-serif;background:var(--bg);color:var(--text)}
/* Audience presentation owns its background controls. Never inject the admin portal theme switch over the official badge. */
.bdc-theme-control,.bdc-theme-fallback-bar{display:none!important}
body[data-theme=obsidian_gold]{--bg:#050608;--bg2:#44371e;--accent:#d8b761}
body[data-theme=ivory_wine]{--bg:#fffaf0;--bg2:#f1e2e6;--text:#341525;--muted:#735866;--card:rgba(255,255,255,.78);--line:#d7c4ca;--accent:#8b2948}
body[data-theme=pearl_navy]{--bg:#f8fbff;--bg2:#dce8f6;--text:#10213d;--muted:#4c6380;--card:rgba(255,255,255,.82);--line:#b9cbe0;--accent:#215d9c}
body{background:radial-gradient(circle at 50% -15%,var(--bg2),var(--bg) 68%)}
#app{width:100vw;height:100vh;padding:clamp(14px,1.8vw,34px);display:flex;flex-direction:column;gap:clamp(10px,1.2vh,20px)}
.top{display:grid;grid-template-columns:clamp(64px,7vw,118px) 1fr clamp(120px,13vw,220px);align-items:center;gap:2vw;min-height:clamp(70px,9vh,126px)}
.logo{width:clamp(64px,7vw,118px);aspect-ratio:1;background:#fff;border-radius:clamp(12px,1.2vw,22px);padding:8px;box-shadow:0 12px 34px #0003}.logo img{width:100%;height:100%;object-fit:contain}
.event{text-align:center;min-width:0}.event h1{font-size:clamp(24px,3vw,58px);line-height:1.05;margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.event p{font-size:clamp(13px,1.25vw,24px);color:var(--muted);margin:.35em 0 0;text-transform:uppercase;letter-spacing:.08em}
.identity{text-align:right}.official{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:.5em 1em;font-size:clamp(10px,.8vw,15px);font-weight:900;letter-spacing:.1em}.test{background:#b42318;color:#fff}
.stage{flex:1;min-height:0;display:grid;place-items:center;position:relative;overflow:hidden}.view{width:100%;height:100%;display:grid;place-items:center;animation:enter .38s ease both}@keyframes enter{from{opacity:0;transform:translateY(12px) scale(.99)}to{opacity:1;transform:none}}
.holding{text-align:center;max-width:80vw}.holding .eyebrow{color:var(--accent);font-weight:900;letter-spacing:.18em;font-size:clamp(13px,1.1vw,22px)}.holding h2{font-size:clamp(58px,9vw,170px);line-height:.95;margin:.12em 0}.holding p{font-size:clamp(20px,2.4vw,48px);color:var(--muted);margin:.35em 0}
.call{width:min(1500px,96vw);height:100%;display:grid;place-items:center}.call-layout{width:100%;display:grid;grid-template-columns:minmax(0,1fr) clamp(210px,19vw,360px);gap:clamp(24px,4vw,76px);align-items:center}.contestant-hero{text-align:center;min-width:0}.call .label{font-size:clamp(14px,1.3vw,25px);font-weight:900;letter-spacing:.2em;color:var(--muted)}.call .number{font-size:clamp(170px,22vw,430px);font-weight:1000;line-height:.78;color:var(--accent);text-shadow:0 20px 65px #0004}.call h2{font-size:clamp(34px,4.2vw,80px);line-height:1;margin:.22em 0}.trophy-showcase{align-self:center;text-align:center;padding:clamp(14px,1.4vw,24px);border:1px solid rgba(229,189,89,.62);border-radius:clamp(20px,2vw,34px);background:radial-gradient(circle at 50% 38%,#fff 0,#fffdf6 58%,#ead9aa 100%);box-shadow:0 22px 70px #0006,0 0 50px rgba(229,189,89,.16);overflow:hidden}.trophy-showcase img{display:block;width:auto;height:min(51vh,520px);max-width:100%;margin:auto;object-fit:contain}.trophy-showcase strong{display:block;margin-top:.65em;color:#4a3211;font-size:clamp(13px,1vw,19px);letter-spacing:.12em;text-transform:uppercase}
.profile-photo{width:clamp(82px,8vw,154px);height:clamp(82px,8vw,154px);border-radius:50%;object-fit:cover;border:3px solid var(--accent);background:#fff;box-shadow:0 12px 32px #0004}.identity-meta{display:flex;align-items:center;justify-content:center;gap:.45em;margin-top:.45em;color:var(--muted);font-size:clamp(14px,1.25vw,24px);font-weight:800}.identity-meta .flag{font-size:1.45em}.call .profile-photo{width:clamp(180px,16vw,300px);height:clamp(180px,16vw,300px);margin-bottom:1.2vh;border-width:4px}.call .identity-meta{font-size:clamp(30px,2.8vw,52px);gap:.38em;margin-top:.3em;color:var(--text);font-weight:900}.call .identity-meta .flag{font-size:1.7em;line-height:1}.card .profile-photo{margin-bottom:.8em}.rank-photo{width:clamp(42px,4.2vw,74px);height:clamp(42px,4.2vw,74px);border-radius:50%;object-fit:cover;border:2px solid var(--accent);background:#fff}.podium-photo{width:clamp(76px,7vw,132px);height:clamp(76px,7vw,132px);border-radius:50%;object-fit:cover;border:3px solid var(--accent);background:#fff;margin:.5em auto}
.grid{width:100%;height:100%;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));grid-auto-rows:1fr;gap:clamp(10px,1.2vw,22px);align-content:center}.grid.compact{grid-template-columns:repeat(5,minmax(0,1fr))}
.card{min-width:0;background:var(--card);border:1px solid var(--line);border-radius:clamp(14px,1.5vw,28px);padding:clamp(12px,1.5vw,26px);display:grid;place-items:center;text-align:center;box-shadow:0 15px 38px #0002;overflow:hidden}.card .kicker{font-size:clamp(11px,.85vw,16px);font-weight:900;letter-spacing:.12em;color:var(--accent);text-transform:uppercase}.card strong{display:block;font-size:clamp(20px,2vw,40px);line-height:1.08;max-width:100%}.card small{display:block;color:var(--muted);font-size:clamp(12px,1.05vw,20px);margin-top:.45em}.bib{font-size:clamp(48px,6vw,112px)!important;line-height:.9!important;color:var(--accent)}
.judge-card{border-top:5px solid var(--warn)}.judge-card.submitted{border-top-color:var(--good)}.judge-card .status{margin-top:.8em;border-radius:999px;padding:.4em .8em;background:#0002;font-weight:800;text-transform:uppercase}
.progress-wrap{width:100%;height:100%;display:flex;flex-direction:column;gap:2vh}.progress-summary{display:flex;justify-content:center;gap:4vw;font-size:clamp(18px,2vw,36px);font-weight:900}.progress-summary b{color:var(--good)}.progress-summary .waiting{color:var(--warn)}
.board{width:min(1500px,96vw);max-height:100%;overflow:hidden;border:1px solid var(--line);border-radius:24px;background:var(--card);box-shadow:0 18px 55px #0002}.rank-row{display:grid;grid-template-columns:clamp(55px,6vw,105px) clamp(42px,4.2vw,74px) clamp(95px,10vw,175px) 1fr clamp(110px,13vw,220px);gap:18px;align-items:center;padding:clamp(8px,1vh,15px) clamp(15px,1.8vw,30px);border-bottom:1px solid var(--line);font-size:clamp(16px,1.5vw,29px)}.rank-row:last-child{border:0}.rank-row .place{font-weight:1000;color:var(--accent)}.rank-row .number{font-weight:900}.rank-row .name{font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rank-row .score{text-align:right;font-weight:1000}
.podium{width:min(1500px,96vw);height:100%;display:grid;grid-template-columns:1fr 1.15fr 1fr;align-items:end;gap:2vw;padding:3vh 0}.podium-card{background:var(--card);border:1px solid var(--line);border-radius:28px 28px 10px 10px;text-align:center;padding:3vh 1.5vw;box-shadow:0 18px 55px #0003}.podium-card.first{min-height:75%;border:3px solid #f2c94c}.podium-card.second{min-height:62%;border:2px solid #cbd5e1}.podium-card.third{min-height:54%;border:2px solid #cd7f32}.podium-card .medal{font-size:clamp(42px,6vw,110px)}.podium-card .place{font-size:clamp(20px,2vw,40px);font-weight:1000}.podium-card .number{font-size:clamp(30px,4vw,74px);font-weight:1000;color:var(--accent)}.podium-card .name{font-size:clamp(20px,2.2vw,44px);font-weight:800}.podium-card .score{color:var(--muted);font-size:clamp(16px,1.5vw,28px)}
.empty{text-align:center;color:var(--muted)}.empty strong{display:block;color:var(--text);font-size:clamp(38px,5vw,90px)}.empty span{font-size:clamp(18px,2vw,38px)}
.footer{min-height:30px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;color:var(--muted);font-size:clamp(10px,.85vw,16px);letter-spacing:.08em;text-transform:uppercase}.footer .state{text-align:left}.footer .page{text-align:center}.footer .live{text-align:right;color:var(--good);font-weight:900}.dot{display:inline-block;width:.65em;height:.65em;border-radius:50%;background:currentColor;margin-right:.45em}
.connection{position:fixed;right:clamp(14px,1.8vw,34px);bottom:clamp(14px,1.8vw,34px);z-index:9;border-radius:999px;background:#9f1239;color:#fff;padding:.72em 1.05em;font-size:clamp(11px,.8vw,15px);font-weight:800;display:none;max-width:min(440px,70vw);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;box-shadow:0 10px 30px #0005}
@media(max-width:1000px){.grid,.grid.compact{grid-template-columns:repeat(3,minmax(0,1fr))}.top{grid-template-columns:74px 1fr 120px}.rank-row{grid-template-columns:55px 54px 90px 1fr 105px}}
@media(max-aspect-ratio:1/1){.grid,.grid.compact{grid-template-columns:repeat(2,minmax(0,1fr))}.podium{grid-template-columns:1fr;height:auto;align-items:stretch}.podium-card{min-height:0!important}.top{grid-template-columns:64px 1fr}.identity{display:none}.event h1{white-space:normal}.rank-row{grid-template-columns:42px 44px 70px 1fr 76px;gap:8px}.call-layout{grid-template-columns:minmax(0,1fr) clamp(170px,27vw,290px);gap:clamp(14px,3vw,34px)}.trophy-showcase img{height:min(39vh,410px)}}
@media(max-width:640px){.call-layout{grid-template-columns:1fr}.trophy-showcase{display:none}}
</style>
</head>
<body class="dc-projector-presentation">
<main id="app">
 <header class="top"><div class="logo"><img src="../../public/assets/img/bdc-logo.png" alt="BDC"></div><div class="event"><h1 id="eventName">BDC Dance Cup</h1><p id="categoryName">Holding Screen</p></div><div class="identity"><span class="official <?=$test?'test':''?>"><?=$test?'TEST DISPLAY':'BDC · OFFICIAL LIVE DISPLAY'?></span></div></header>
 <section class="stage" id="stage"><div class="view"><div class="holding"><div class="eyebrow">DANCE CUP</div><h2>Holding Screen</h2><p>Waiting for projection control</p></div></div></section>
 <footer class="footer"><span class="state" id="screenState">Holding Screen</span><span class="page" id="pageState"></span><span class="live"><i class="dot"></i>Live</span></footer>
</main>
<div class="connection" id="connection">Live updates temporarily unavailable. Retrying…</div>
<script>
(()=>{'use strict';
const token=<?=json_encode($token)?>,test=<?=$test?'true':'false'?>,stage=document.getElementById('stage'),eventName=document.getElementById('eventName'),categoryName=document.getElementById('categoryName'),screenState=document.getElementById('screenState'),pageState=document.getElementById('pageState'),connection=document.getElementById('connection');
let lastHash='',busy=false,currentPage=1,pageTotal=1,lastType='holding',nextPageAt=0,backoffUntil=0,cycle={index:0,phase:'contestant',next:0},latest=null;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const label=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());
const chunk=(items,size)=>{const pages=[];for(let index=0;index<items.length;index+=size)pages.push(items.slice(index,index+size));return pages.length?pages:[[]]};
const empty=(title,message)=>'<div class="empty"><strong>'+esc(title)+'</strong><span>'+esc(message)+'</span></div>';
function setHeader(data){document.body.dataset.theme=data.state.theme||'midnight_wine';eventName.textContent=data.state.event_name||'BDC Dance Cup';categoryName.textContent=(data.state.category_name||'Category')+' · '+label(data.state.round_name||'');}
const photo=item=>esc(item?.photo_url||'../../public/assets/img/default-competitor.svg');
const identity=item=>'<div class="identity-meta"><span class="flag">'+esc(item?.flag||'')+'</span><span>'+esc(item?.country||'Country not set')+'</span></div>';
function show(html,type,page=0,total=0){pageTotal=Math.max(1,total||1);stage.innerHTML='<div class="view">'+html+'</div>';screenState.textContent=label(type);pageState.textContent=total>1?'Page '+page+' of '+total:'';}
function holding(data){show('<div class="holding"><div class="eyebrow">'+esc(data.state.holding_title||'DANCE CUP')+'</div><h2>'+esc(data.state.event_name||'BDC Dance Cup')+'</h2><p>'+esc(data.state.holding_message||'Next contestant preparing')+'</p></div>','Holding Screen');}
function contestant(entry){const eventLabel=latest?.state?.event_name||'Dance Cup';show(entry?'<div class="call"><div class="call-layout"><div class="contestant-hero"><img class="profile-photo" src="'+photo(entry)+'" alt=""><div class="label">NOW PRESENTING</div><div class="number">'+esc(entry.contestant_number)+'</div><h2>'+esc(entry.display_name)+'</h2>'+identity(entry)+'</div><aside class="trophy-showcase"><img src="../../public/assets/img/sbta-dance-cup-champion-trophy.png" alt="SBTA Dance Cup trophy"><strong>'+esc(eventLabel)+'</strong></aside></div></div>':empty('Contestant pending','Select a contestant from Projection Control.'),'Contestant Call');}
function pagedCards(items,size,type,renderCard,data){const pages=chunk(items,size),total=pages.length;currentPage=Math.max(1,Math.min(total,currentPage));const cards=pages[currentPage-1].map(renderCard).join('');show(cards?'<div class="grid '+(size>=10?'compact':'')+'">'+cards+'</div>':empty(type+' pending','Add records in the Dance Cup category workspace.'),type,currentPage,total);schedulePage(total,data);}
function judges(data,progress=false){const done=data.judges.filter(j=>j.status==='submitted').length;const cards=j=>'<article class="card judge-card '+(j.status==='submitted'?'submitted':'')+'"><div><img class="profile-photo" src="'+photo(j)+'" alt=""><span class="kicker">J'+esc(j.judge_order)+(Number(j.is_chief)?' · Chief Judge':'')+'</span><strong>'+esc(j.judge_name)+'</strong>'+identity(j)+'<small class="status">'+esc(label(j.status))+'</small></div></article>';if(progress){const pages=chunk(data.judges,8),total=pages.length;currentPage=Math.max(1,Math.min(total,currentPage));show('<div class="progress-wrap"><div class="progress-summary"><span><b>'+done+'</b> completed</span><span class="waiting">'+(data.judges.length-done)+' pending</span></div><div class="grid">'+pages[currentPage-1].map(cards).join('')+'</div></div>','Scoring Progress',currentPage,total);schedulePage(total,data);}else pagedCards(data.judges,8,'Judges',cards,data);}
function contestants(data){pagedCards(data.entries,10,'All Contestants',entry=>'<article class="card"><div><img class="profile-photo" src="'+photo(entry)+'" alt=""><span class="kicker">Contestant</span><strong class="bib">'+esc(entry.contestant_number)+'</strong><small>'+esc(entry.display_name)+'</small>'+identity(entry)+'</div></article>',data);}
function results(data){const pages=chunk(data.results,8),total=pages.length;currentPage=Math.max(1,Math.min(total,currentPage));const rows=pages[currentPage-1].map(row=>{const scored=Number(row.has_score)===1;return '<div class="rank-row"><span class="place">'+(scored?esc(row.placement):'—')+'</span><img class="rank-photo" src="'+photo(row)+'" alt=""><span class="number">No. '+esc(row.contestant_number)+'</span><span class="name">'+esc(row.display_name)+' '+esc(row.flag||'')+'</span><span class="score">'+(scored?Number(row.total_score).toLocaleString(undefined,{maximumFractionDigits:2}):'Not scored')+'</span></div>'}).join('');show(rows?'<div class="board">'+rows+'</div>':empty('Scores pending','Scores will appear after judges begin scoring.'),'Live Scoreboard',currentPage,total);schedulePage(total,data);}
function podium(data){const top=data.results.filter(row=>Number(row.has_score)===1&&row.placement!==null).slice(0,3),order=[top[1],top[0],top[2]],classes=['second','first','third'],medals=['🥈','🥇','🥉'];const cards=order.map((row,index)=>row?'<article class="podium-card '+classes[index]+'"><div class="medal">'+medals[index]+'</div><img class="podium-photo" src="'+photo(row)+'" alt=""><div class="place">'+label(row.placement+(Number(row.placement)===1?'st':Number(row.placement)===2?'nd':'rd'))+'</div><div class="number">No. '+esc(row.contestant_number)+'</div><div class="name">'+esc(row.display_name)+'</div>'+identity(row)+'<div class="score">'+Number(row.total_score).toLocaleString(undefined,{maximumFractionDigits:2})+' points</div></article>':'').join('');show(cards?'<div class="podium">'+cards+'</div>':empty('Podium locked','Calculate results before revealing the winners.'),'Winner Podium');}
function schedulePage(total,data){pageTotal=Math.max(1,total||1);if(total<2){nextPageAt=0;return}if(Number(data.state.auto_page)){if(!nextPageAt)nextPageAt=Date.now()+Math.max(5,Number(data.state.page_delay)||10)*1000}else nextPageAt=0;}
function render(data,force=false){latest=data;setHeader(data);const type=data.state.screen_type||'holding';if(type!==lastType){lastType=type;currentPage=Math.max(1,Number(data.state.page_number)||1);nextPageAt=0}else if(force)currentPage=Math.max(1,Number(data.state.page_number)||currentPage);if(type==='holding')holding(data);else if(type==='contestant')contestant(data.active_entry);else if(type==='contestants')contestants(data);else if(type==='judges')judges(data,false);else if(type==='scoring')judges(data,true);else if(type==='results')results(data);else if(type==='podium')podium(data);else holding(data);}
function advanceAutoPage(){if(!latest||!nextPageAt||Date.now()<nextPageAt)return;currentPage=currentPage>=pageTotal?1:currentPage+1;nextPageAt=0;render(latest);}
function advanceRunOfShow(data){if(!Number(data.state.auto_cycle)||!data.entries.length)return;if(!cycle.next){cycle.index=Math.max(0,data.entries.findIndex(entry=>Number(entry.id)===Number(data.state.active_entry_id)));cycle.phase='contestant';cycle.next=Date.now()+Number(data.state.contestant_seconds||12)*1000}if(Date.now()<cycle.next)return;if(cycle.phase==='contestant'){cycle.phase='holding';cycle.next=Date.now()+Number(data.state.holding_seconds||8)*1000;holding(data)}else{cycle.phase='contestant';cycle.index=(cycle.index+1)%data.entries.length;cycle.next=Date.now()+Number(data.state.contestant_seconds||12)*1000;contestant(data.entries[cycle.index])}}
async function poll(){if(document.hidden||busy||Date.now()<backoffUntil)return;busy=true;const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetch('./projection-feed.php?token='+encodeURIComponent(token)+(test?'&data_mode=test':'')+'&_='+Date.now(),{cache:'no-store',credentials:'same-origin',headers:{Accept:'application/json'},signal:controller.signal});if(response.status===429){backoffUntil=Date.now()+15000;throw new Error('Rate limited')}const contentType=response.headers.get('content-type')||'';if(!contentType.includes('application/json'))throw new Error('Invalid feed response');const data=await response.json();if(!response.ok||!data.ok)throw new Error('Feed unavailable');const hash=JSON.stringify([data.state.state_version,data.state.screen_type,data.state.theme,data.state.page_number,data.state.auto_page,data.state.page_delay,data.entries,data.judges,data.results,data.active_entry]);if(hash!==lastHash){const stateChanged=lastHash!==''&&latest&&Number(data.state.state_version)!==Number(latest.state.state_version);lastHash=hash;render(data,stateChanged);cycle.next=0}advanceRunOfShow(data);connection.style.display='none'}catch(error){connection.textContent=error?.name==='AbortError'?'Live update timed out. Retrying…':'Live updates interrupted. Retrying…';connection.style.display='block'}finally{clearTimeout(timeout);busy=false}}
setInterval(advanceAutoPage,500);poll();setInterval(poll,5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});
})();
</script>
</body>
</html>
