<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Database;
use App\Services\DanceCupScoringService;
$token=preg_replace('/[^a-f0-9]/','',(string)($_GET['token']??''));
$test=(string)($_GET['data_mode']??'')==='test';
if(strlen($token)!==64){http_response_code(404);exit('Projector link not found.');}
$initialEventName='Dance Cup';
try{
 $prefix=$test?'bdc_test_dance_cup':'bdc_dance_cup';$tables=DanceCupScoringService::tables($test);
 $initial=Database::connection()->prepare("SELECT e.name FROM {$prefix}_event_projection p JOIN {$tables['events']} e ON e.id=p.event_id WHERE p.access_token=:token LIMIT 1");
 $initial->execute(['token'=>$token]);$initialEventName=(string)($initial->fetchColumn()?:$initialEventName);
}catch(Throwable){}
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Expires: 0');
?><!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>BDC Dance Cup Live Display</title>
<style>
:root{--bg:#08111f;--bg2:#5b1833;--text:#fff;--muted:#d9c9d1;--card:rgba(255,255,255,.09);--line:rgba(255,255,255,.2);--accent:#e5bd59;--good:#35c978;--warn:#efbd4d;--danger:#ef596f}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;font-family:Inter,Arial,sans-serif;background:var(--bg);color:var(--text)}
/* Audience presentation owns its background controls. Never inject the admin portal theme switch over the official badge. */
.bdc-theme-control,.bdc-theme-fallback-bar{display:none!important}
body[data-theme=obsidian_gold]{--bg:#050608;--bg2:#44371e;--accent:#d8b761}
body[data-theme=ivory_wine]{--bg:#fffaf0;--bg2:#f1e2e6;--text:#341525;--muted:#735866;--card:rgba(255,255,255,.78);--line:#d7c4ca;--accent:#8b2948}
body[data-theme=pearl_navy]{--bg:#f8fbff;--bg2:#dce8f6;--text:#10213d;--muted:#4c6380;--card:rgba(255,255,255,.82);--line:#b9cbe0;--accent:#215d9c}
body{background:radial-gradient(circle at 50% -15%,var(--bg2),var(--bg) 68%)}
#app{width:100vw;height:100vh;padding:10vh 5vw;display:flex;flex-direction:column;gap:clamp(8px,1vh,16px)}
.top{width:100%;max-width:100%;margin-inline:auto;display:grid;grid-template-columns:minmax(0,1fr) clamp(120px,13vw,220px);align-items:center;gap:clamp(16px,1.4vw,28px);min-height:clamp(70px,9vh,126px)}
.event-brand{min-width:0;display:flex;align-items:center;justify-content:center;gap:clamp(14px,1.15vw,24px)}
.logo{flex:0 0 auto;width:clamp(64px,7vw,118px);aspect-ratio:1;background:#fff;border-radius:clamp(12px,1.2vw,22px);padding:8px;box-shadow:0 12px 34px #0003;transform:translateY(clamp(3px,.55vh,7px))}.logo img{width:100%;height:100%;object-fit:contain}
.event{flex:0 1 auto;text-align:left;min-width:0}.event h1{font-size:clamp(26px,3.2vw,62px);line-height:1.05;margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.event p:empty{display:none}
.identity{text-align:right}.official{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:.5em 1em;font-size:clamp(10px,.8vw,15px);font-weight:900;letter-spacing:.1em;cursor:pointer;user-select:none;transition:transform .14s ease,border-color .14s ease,background .14s ease}.official:hover,.official:focus-visible{transform:translateY(-1px);border-color:var(--accent);background:color-mix(in srgb,var(--accent) 16%,transparent);outline:none}.test{background:#b42318;color:#fff}
.stage{flex:1;min-height:0;display:grid;place-items:center;position:relative;overflow:hidden}.view{width:100%;height:100%;min-height:0;overflow:hidden;display:grid;grid-template-rows:auto minmax(0,1fr);animation:enter .38s ease both}.screen-category{text-align:center;font-size:clamp(18px,1.7vw,32px);line-height:1.15;font-weight:900;color:var(--muted);text-transform:uppercase;letter-spacing:.08em;padding:clamp(8px,1.1vh,14px) 1vw clamp(7px,.9vh,12px)}.screen-content{width:100%;height:auto;min-height:0;display:grid;place-items:center;overflow:hidden}.screen-content>*{max-width:100%;max-height:100%}@keyframes enter{from{opacity:0;transform:translateY(12px) scale(.99)}to{opacity:1;transform:none}}
.holding{text-align:center;max-width:100%}.holding .eyebrow{color:var(--accent);font-weight:900;letter-spacing:.18em;font-size:clamp(13px,1.1vw,22px)}.holding h2{font-size:clamp(58px,9vw,170px);line-height:.95;margin:.12em 0}.holding p{font-size:clamp(20px,2.4vw,48px);color:var(--muted);margin:.35em 0}
.call{width:min(1680px,100%);height:100%;display:grid;place-items:center}.call-layout{width:100%;height:min(100%,760px);display:grid;grid-template-columns:minmax(190px,.72fr) minmax(390px,1.35fr) minmax(240px,.82fr);gap:clamp(14px,1.8vw,34px);align-items:stretch}.number-panel,.contestant-identity,.trophy-showcase{min-width:0;border-left:1px solid rgba(229,189,89,.36)}.number-panel{border-left:0;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.number-label,.call .label{font-size:clamp(13px,1.05vw,21px);font-weight:900;letter-spacing:.18em;color:var(--muted);text-transform:uppercase}.call .number{font-size:clamp(250px,31vw,580px);font-weight:1000;line-height:.78;color:var(--accent);text-shadow:0 20px 65px #0004}.contestant-identity{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:0 clamp(10px,1.2vw,22px)}.call h2{font-size:clamp(38px,4vw,74px);line-height:1.02;margin:.28em 0 .12em;max-width:100%}.trophy-showcase{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:clamp(14px,1.4vw,24px);border:1px solid rgba(229,189,89,.62);border-radius:clamp(20px,2vw,34px);background:radial-gradient(circle at 50% 38%,#fff 0,#fffdf6 58%,#ead9aa 100%);box-shadow:0 22px 70px #0006,0 0 50px rgba(229,189,89,.16);overflow:hidden}.trophy-showcase img{display:block;width:auto;height:min(100%,520px);max-width:100%;margin:0 auto;object-fit:contain}.trophy-showcase strong{display:block;margin-top:.65em;color:#4a3211;font-size:clamp(13px,1vw,19px);letter-spacing:.12em;text-transform:uppercase}
.profile-photo{width:clamp(66px,6.4vw,123px);height:clamp(82px,8vw,154px);border-radius:clamp(9px,.8vw,15px);object-fit:cover;object-position:center;border:3px solid var(--accent);background:#fff;box-shadow:0 12px 32px #0004}.identity-meta{display:flex;align-items:center;justify-content:center;gap:.45em;margin-top:.45em;color:var(--muted);font-size:clamp(14px,1.25vw,24px);font-weight:800}.identity-meta .flag{font-size:1.45em}.call .profile-photo{width:clamp(184px,15.2vw,288px);height:clamp(230px,19vw,360px);margin-bottom:1.5vh;border-width:4px}.call .identity-meta{font-size:clamp(34px,3vw,56px);gap:.38em;margin-top:.28em;color:var(--text);font-weight:900;text-transform:uppercase}.call .identity-meta .flag{font-size:1.75em;line-height:1}.card .profile-photo{margin-bottom:.8em}.rank-photo{width:clamp(46px,4.4vw,83px);height:clamp(58px,5.5vw,104px);border-radius:clamp(7px,.6vw,12px);object-fit:cover;object-position:center;border:2px solid var(--accent);background:#fff}.podium-photo{width:clamp(70px,6.4vw,125px);height:clamp(88px,8vw,156px);border-radius:clamp(9px,.8vw,15px);object-fit:cover;object-position:center;border:3px solid var(--accent);background:#fff;margin:.5em auto}
.grid{width:100%;height:100%;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));grid-auto-rows:1fr;gap:clamp(8px,1vw,18px);align-content:center}.grid.compact{grid-template-columns:repeat(5,minmax(0,1fr))}
.card{min-width:0;background:var(--card);border:1px solid var(--line);border-radius:clamp(14px,1.5vw,28px);padding:clamp(12px,1.5vw,26px);display:grid;place-items:center;text-align:center;box-shadow:0 15px 38px #0002;overflow:hidden}.card .kicker{font-size:clamp(11px,.85vw,16px);font-weight:900;letter-spacing:.12em;color:var(--accent);text-transform:uppercase}.card strong{display:block;font-size:clamp(23px,2.25vw,44px);line-height:1.08;max-width:100%}.card small{display:block;color:var(--muted);font-size:clamp(15px,1.25vw,24px);margin-top:.45em}.bib{font-size:clamp(56px,6.7vw,126px)!important;line-height:.9!important;color:var(--accent)}.contestant-card .contestant-name{color:var(--text);font-size:clamp(22px,1.7vw,34px);font-weight:900;line-height:1.05}.contestant-card .identity-meta{gap:.5em;margin-top:.55em;color:var(--text);font-size:clamp(20px,1.55vw,31px);font-weight:900}.contestant-card .identity-meta .flag{font-size:1.75em;line-height:1}
.judge-card{border-top:5px solid var(--danger)}.judge-card.contestant-complete{border-top-color:var(--good)}.judge-card.contestant-progress{border-top-color:var(--warn)}.judge-card .judge-status-stack{display:grid;gap:.45em;margin-top:.8em}.judge-card .status{margin:0;border-radius:999px;padding:.38em .75em;background:#0002;font-weight:800;text-transform:uppercase}.judge-card .status.current.complete{background:rgba(53,201,120,.18);color:var(--good)}.judge-card .status.current.in-progress{background:rgba(239,189,77,.18);color:var(--warn)}.judge-card .status.final{font-size:clamp(10px,.72vw,14px);opacity:.86}.judge-card .status.final.submitted{color:var(--good)}
.progress-wrap{width:100%;height:100%;display:flex;flex-direction:column;gap:2vh}.progress-summary{display:flex;justify-content:center;gap:4vw;font-size:clamp(18px,1.65vw,32px);font-weight:900}.progress-summary b{color:var(--good)}.progress-summary .waiting{color:var(--warn)}
.board{width:min(1720px,100%);max-height:100%;overflow:hidden;border:1px solid var(--line);border-radius:24px;background:var(--card);box-shadow:0 18px 55px #0002}.rank-row{display:grid;grid-template-columns:clamp(60px,6vw,112px) clamp(50px,4.8vw,86px) clamp(110px,11vw,190px) 1fr clamp(125px,14vw,240px);gap:clamp(14px,1.25vw,24px);align-items:center;padding:clamp(11px,1.35vh,20px) clamp(18px,2vw,36px);border-bottom:1px solid var(--line);font-size:clamp(19px,1.75vw,34px)}.rank-row:last-child{border:0}.rank-row .place{font-weight:1000;color:var(--accent)}.rank-row .number{font-weight:900}.rank-row .name{font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rank-row .score{text-align:right;font-weight:1000;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.podium{width:min(1500px,100%);height:100%;display:grid;grid-template-columns:1fr 1.15fr 1fr;align-items:end;gap:2vw;padding:2vh 0}.podium-card{height:var(--podium-height);max-height:100%;align-self:end;display:flex;flex-direction:column;align-items:center;justify-content:center;background:linear-gradient(180deg,color-mix(in srgb,var(--card) 92%,#fff 8%),var(--card));border:1px solid var(--line);border-radius:28px 28px 10px 10px;text-align:center;padding:clamp(14px,2.2vh,24px) 1.5vw;box-shadow:0 18px 55px #0005;animation:podiumRise .65s cubic-bezier(.2,.8,.2,1) both;overflow:hidden}.podium-card.first{--podium-height:clamp(500px,69vh,690px);border:3px solid #f2c94c;box-shadow:0 24px 80px rgba(242,201,76,.22),0 18px 55px #0005}.podium-card.second{--podium-height:clamp(430px,59vh,590px);border:2px solid #cbd5e1}.podium-card.third{--podium-height:clamp(390px,51vh,510px);border:2px solid #cd7f32}.podium-card .medal{font-size:clamp(42px,6vw,110px);line-height:1}.podium-card .place{font-size:clamp(20px,2vw,40px);font-weight:1000}.podium-card .number{font-size:clamp(30px,4vw,74px);font-weight:1000;color:var(--accent)}.podium-card .name{font-size:clamp(20px,2.2vw,44px);font-weight:800}.podium-card .score{color:var(--muted);font-size:clamp(16px,1.5vw,28px)}.podium-card.second .medal,.podium-card.third .medal{font-size:clamp(38px,4.7vw,82px)}.podium-card.second .podium-photo,.podium-card.third .podium-photo{width:clamp(72px,6vw,108px);height:clamp(72px,6vw,108px)}.podium-card.second .number,.podium-card.third .number{font-size:clamp(28px,3.2vw,58px)}.podium-card.second .name,.podium-card.third .name{font-size:clamp(20px,1.9vw,38px)}.podium-card.second .identity-meta,.podium-card.third .identity-meta{font-size:clamp(14px,1.05vw,21px)}.podium-card.second .score,.podium-card.third .score{font-size:clamp(15px,1.25vw,23px)}@keyframes podiumRise{from{opacity:0;transform:translateY(90px)}to{opacity:1;transform:none}}
.result-countdown{position:fixed;inset:0;z-index:12;display:grid;place-items:center;background:radial-gradient(circle at 50% 45%,rgba(92,60,18,.48),rgba(4,6,12,.96) 62%);text-align:center}.result-countdown .count-label{font-size:clamp(16px,1.5vw,28px);font-weight:900;letter-spacing:.22em;text-transform:uppercase;color:#f5d77f}.result-countdown .count-number{font-size:clamp(190px,32vw,560px);font-weight:1000;line-height:.82;color:#f2c94c;text-shadow:0 0 32px rgba(242,201,76,.7),0 30px 90px #000;animation:countPulse .82s ease both}.result-countdown .count-place{font-size:clamp(30px,3.6vw,70px);font-weight:1000;color:#fff;margin-top:.35em}@keyframes countPulse{0%{opacity:0;transform:scale(.45)}35%{opacity:1;transform:scale(1.12)}100%{opacity:1;transform:scale(1)}}
.empty{text-align:center;color:var(--muted)}.empty strong{display:block;color:var(--text);font-size:clamp(38px,5vw,90px)}.empty span{font-size:clamp(18px,2vw,38px)}
.footer{min-height:30px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;color:var(--muted);font-size:clamp(10px,.85vw,16px);letter-spacing:.08em;text-transform:uppercase}.footer .state{text-align:left}.footer .page{text-align:center}.footer .live{text-align:right;color:var(--good);font-weight:900}.dot{display:inline-block;width:.65em;height:.65em;border-radius:50%;background:currentColor;margin-right:.45em}
.connection{position:fixed;right:clamp(14px,1.8vw,34px);bottom:clamp(14px,1.8vw,34px);z-index:9;border-radius:999px;background:#9f1239;color:#fff;padding:.72em 1.05em;font-size:clamp(11px,.8vw,15px);font-weight:800;display:none;max-width:min(440px,70vw);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;box-shadow:0 10px 30px #0005}
.fx-layer{position:fixed;inset:0;z-index:8;pointer-events:none;overflow:hidden}.fx-cinematic{position:absolute;inset:0;background:radial-gradient(circle at 50% 42%,rgba(245,200,75,.16),transparent 56%),linear-gradient(180deg,rgba(0,0,0,.08),rgba(0,0,0,.34));animation:cinematicWash 10s ease-in-out forwards}.fx-particle{position:absolute;top:-12vh;font-size:clamp(28px,4vw,72px);animation:fxFall var(--duration,8s) cubic-bezier(.18,.45,.28,.98) forwards;filter:drop-shadow(0 8px 18px #0008);will-change:transform,opacity}.fx-impact{position:absolute;inset:0;display:grid;place-items:center;font-size:clamp(130px,25vw,480px);animation:fxImpact 7s cubic-bezier(.16,.8,.22,1) forwards;text-shadow:0 0 70px #f5c84b,0 0 160px rgba(245,200,75,.7)}.firework-burst{position:absolute;width:8px;height:8px}.firework-spark{position:absolute;inset:0;margin:auto;width:clamp(4px,.48vw,9px);height:clamp(15px,1.5vw,29px);border-radius:999px;background:var(--spark);box-shadow:0 0 18px var(--spark),0 0 36px var(--spark);transform-origin:50% 100%;animation:fireworkSpark 2.2s cubic-bezier(.08,.72,.16,1) forwards}@keyframes cinematicWash{0%{opacity:0}14%{opacity:1}78%{opacity:.9}100%{opacity:0}}@keyframes fireworkSpark{0%{opacity:0;transform:rotate(var(--angle)) translateY(0) scaleY(.18)}12%{opacity:1}72%{opacity:1}100%{opacity:0;transform:rotate(var(--angle)) translateY(calc(-1 * var(--distance))) scaleY(.55)}}@keyframes fxFall{0%{opacity:0;transform:translate3d(0,-8vh,0) rotate(0)}12%{opacity:1}82%{opacity:1}100%{transform:translate3d(var(--drift,0),120vh,0) rotate(720deg);opacity:0}}@keyframes fxImpact{0%{opacity:0;transform:scale(.18) translateY(50px)}16%{opacity:1;transform:scale(1.16) translateY(0)}32%{transform:scale(.98)}72%{opacity:1;transform:scale(1)}100%{opacity:0;transform:scale(1.28)}}.podium-card.hidden-slot{visibility:hidden}
@media(max-width:1000px){.grid,.grid.compact{grid-template-columns:repeat(3,minmax(0,1fr))}.top{grid-template-columns:minmax(0,1fr) 120px}.event-brand{justify-content:flex-start}.rank-row{grid-template-columns:55px 54px 90px 1fr 105px}}
@media(max-aspect-ratio:1/1){.grid,.grid.compact{grid-template-columns:repeat(2,minmax(0,1fr))}.podium{grid-template-columns:1fr;height:auto;align-items:stretch;overflow:auto}.podium-card{height:auto;min-height:0}.top{grid-template-columns:1fr}.identity{display:none}.event-brand{justify-content:flex-start}.event h1{white-space:normal}.rank-row{grid-template-columns:42px 44px 70px 1fr 76px;gap:8px}.call-layout{grid-template-columns:minmax(130px,.58fr) minmax(300px,1.3fr) minmax(170px,.72fr);gap:10px}.call .number{font-size:clamp(190px,28vw,360px)}.call .profile-photo{width:clamp(190px,24vw,280px);height:clamp(190px,24vw,280px)}.trophy-showcase img{height:min(39vh,410px)}}
@media(max-width:640px){.call-layout{height:auto;grid-template-columns:minmax(105px,.55fr) minmax(0,1.45fr)}.trophy-showcase{display:none}.call .number{font-size:clamp(150px,34vw,240px)}.call .profile-photo{width:clamp(150px,38vw,220px);height:clamp(150px,38vw,220px)}.call h2{font-size:clamp(25px,7vw,40px)}.call .identity-meta{font-size:clamp(22px,6vw,34px)}}
.identity-meta.multi-country{flex-wrap:wrap;align-content:center;justify-content:center}.identity-country{display:inline-flex;flex-direction:row;align-items:center;justify-content:center;gap:clamp(5px,.42vw,9px);min-width:0;max-width:100%;line-height:1.05;text-align:center;white-space:nowrap;overflow-wrap:normal;word-break:normal}.identity-country .flag-image{display:block;width:clamp(30px,2.15vw,46px);height:auto;aspect-ratio:3/2;object-fit:cover;border:1px solid rgba(255,255,255,.72);border-radius:3px;box-shadow:0 2px 5px #0005}.identity-country>.flag:empty{display:none}

/* dev678 exact Dance Cup audience boards */
.contestant-grid{
  min-height:0!important;
  overflow:hidden!important;
  grid-template-columns:repeat(5,minmax(0,1fr))!important;
  grid-auto-rows:minmax(0,1fr)!important;
  gap:clamp(8px,.65vw,14px)!important;
  align-content:stretch!important;
}
.contestant-grid.rows-1{grid-template-rows:minmax(0,1fr)!important}
.contestant-grid.rows-2{grid-template-rows:repeat(2,minmax(0,1fr))!important}
.contestant-grid>.contestant-card{min-height:0!important;padding:clamp(7px,.72vw,13px)!important}
.contestant-grid>.contestant-card>div{height:100%;min-height:0;display:flex;flex-direction:column;align-items:center;justify-content:center}
.contestant-photo-frame{flex:0 0 auto;display:block;width:clamp(99px,min(7.2vw,14.4vh),141px);height:clamp(124px,min(9vw,18vh),176px);margin-bottom:clamp(2px,.32vh,5px);overflow:hidden;border-radius:clamp(10px,.8vw,15px);border:3px solid var(--accent);background:#fff;box-shadow:0 12px 32px #0004}
.contestant-photo-frame .profile-photo{display:block;width:100%!important;height:100%!important;margin:0!important;border:0!important;border-radius:0!important;box-shadow:none!important;object-fit:cover;object-position:center;transform:none}
.contestant-grid.rows-2 .contestant-photo-frame{width:clamp(66px,min(5.76vw,8.4vh),94px);height:clamp(82px,min(7.2vw,10.5vh),118px)}
.grid:has(>.contestant-card) .kicker{font-size:clamp(9px,.58vw,13px)!important;line-height:1!important}
.grid:has(>.contestant-card) .bib{font-size:clamp(40px,4.1vw,78px)!important;line-height:.9!important}
.grid:has(>.contestant-card) .contestant-name{font-size:clamp(16px,1.2vw,25px)!important;line-height:1!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
.grid:has(>.contestant-card) .identity-meta{font-size:clamp(11px,.78vw,16px)!important;margin-top:clamp(3px,.42vh,6px)!important;gap:clamp(4px,.35vw,8px)!important;white-space:nowrap!important;overflow:hidden!important}
.grid:has(>.contestant-card) .identity-country{max-width:100%!important;flex:0 1 auto!important;overflow:hidden!important;text-overflow:ellipsis!important}
.grid:has(>.contestant-card) .identity-country>span:last-child{min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}

.grid:has(>.judge-card){
  grid-template-columns:minmax(0,1fr)!important;
  grid-auto-rows:minmax(0,1fr)!important;
  gap:clamp(9px,.7vw,15px)!important;
  align-content:stretch!important;
}
.grid:has(>.judge-card:nth-child(2)){grid-template-columns:repeat(2,minmax(0,1fr))!important}
.grid:has(>.judge-card:nth-child(3)){grid-template-columns:repeat(3,minmax(0,1fr))!important}
.grid:has(>.judge-card:nth-child(4)){grid-template-columns:repeat(4,minmax(0,1fr))!important}
.grid:has(>.judge-card:nth-child(5)){grid-template-columns:repeat(5,minmax(0,1fr))!important}
.grid:has(>.judge-card:nth-child(6)){grid-template-columns:repeat(6,minmax(0,1fr))!important}
.grid:has(>.judge-card:nth-child(7)){grid-template-columns:repeat(4,minmax(0,1fr))!important}
.grid:has(>.judge-card:nth-child(9)){grid-template-columns:repeat(5,minmax(0,1fr))!important}
.grid:has(>.judge-card:nth-child(11)){grid-template-columns:repeat(6,minmax(0,1fr))!important}
.grid:has(>.judge-card)>.judge-card{min-height:0!important;padding:clamp(8px,.75vw,14px)!important}
.grid:has(>.judge-card) .profile-photo{width:clamp(61px,min(8.8vw,9.6vh),106px)!important;height:clamp(76px,min(11vw,12vh),132px)!important;margin-bottom:clamp(4px,.55vh,8px)!important}
.grid:has(>.judge-card) .kicker{font-size:clamp(10px,.68vw,14px)!important;line-height:1!important}
.grid:has(>.judge-card) strong{font-size:clamp(18px,1.45vw,29px)!important;line-height:1!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
.grid:has(>.judge-card) .identity-meta{font-size:clamp(11px,.76vw,16px)!important;white-space:nowrap!important;overflow:hidden!important;gap:clamp(4px,.32vw,7px)!important}
.grid:has(>.judge-card) .identity-country{max-width:100%!important;flex:0 1 auto!important;overflow:hidden!important}
.grid:has(>.judge-card) .identity-country>span:last-child{min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}
.grid:has(>.judge-card) .judge-status-stack{gap:clamp(2px,.28vh,4px)!important;margin-top:clamp(4px,.55vh,8px)!important}
.grid:has(>.judge-card) .judge-status-stack .status{font-size:clamp(9px,.58vw,12px)!important;padding:.3em .5em!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}

/* Canonical 4:5 profile preview: projector shows the saved crop without an
   additional circle mask or hidden zoom. */
.podium-card.second .podium-photo,.podium-card.third .podium-photo{width:clamp(58px,4.8vw,86px);height:clamp(72px,6vw,108px)}
@media(max-aspect-ratio:1/1){.call .profile-photo{width:clamp(152px,19.2vw,224px);height:clamp(190px,24vw,280px)}}
@media(max-width:640px){.call .profile-photo{width:clamp(120px,30.4vw,176px);height:clamp(150px,38vw,220px)}}

/* Dance Cup one-by-one judge introduction. The all-judges and scoring grids
   keep their existing count-adaptive sizing. */
.judge-call{width:100%;height:100%;display:grid;place-items:center}
.judge-call-card{width:min(980px,72vw);height:min(100%,650px);padding:clamp(22px,2.4vw,46px)!important;border-top:clamp(6px,.55vw,10px) solid var(--accent);background:radial-gradient(circle at 50% 30%,color-mix(in srgb,var(--card) 72%,var(--accent) 10%),var(--card));overflow:hidden}
.judge-call-card>div{height:100%;min-height:0;display:flex;flex-direction:column;align-items:center;justify-content:center}
.judge-call-card .profile-photo{width:clamp(210px,min(20vw,34vh),350px)!important;height:clamp(262px,min(25vw,42.5vh),438px)!important;margin:0 0 clamp(10px,1.5vh,20px)!important;border-width:clamp(3px,.3vw,5px)!important}
.judge-call-card .kicker{font-size:clamp(16px,1.25vw,24px)!important;line-height:1.1!important}
.judge-call-card strong{font-size:clamp(40px,4vw,76px)!important;line-height:1.02!important;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.judge-call-card .identity-meta{margin-top:clamp(8px,1.15vh,16px);font-size:clamp(19px,1.65vw,31px);font-weight:900;color:var(--text);gap:clamp(10px,1vw,18px)}
.judge-call-card .identity-country{overflow:visible}.judge-call-card .identity-country .flag-image{width:clamp(42px,3.4vw,66px)}
@media(max-aspect-ratio:1/1){.judge-call-card{width:min(88vw,760px)}.judge-call-card .profile-photo{width:clamp(190px,38vw,320px)!important;height:clamp(237px,47.5vw,400px)!important}}

</style>
</head>
<body class="dc-projector-presentation">
<main id="app">
 <header class="top"><div class="event-brand"><div class="logo"><img src="../../public/assets/img/bdc-logo.png" alt="BDC"></div><div class="event"><h1 id="eventName"><?=htmlspecialchars($initialEventName,ENT_QUOTES,'UTF-8')?></h1><p id="categoryName"></p></div></div><div class="identity"><span class="official <?=$test?'test':''?>" data-dc-fullscreen-ready="1" role="button" tabindex="0" title="Enter full screen" aria-label="Enter full screen"><?=$test?'TEST DISPLAY':'BDC · OFFICIAL LIVE DISPLAY'?></span></div></header>
 <section class="stage" id="stage"><div class="view"><div class="holding"><h2><?=htmlspecialchars($initialEventName,ENT_QUOTES,'UTF-8')?></h2></div></div></section>
 <footer class="footer"><span class="state" id="screenState">Holding Screen</span><span class="page" id="pageState"></span><span class="live"><i class="dot"></i>Live</span></footer>
</main>
<div class="connection" id="connection">Live updates temporarily unavailable. Retrying…</div>
<div class="fx-layer" id="fxLayer" aria-hidden="true"></div>
<script>
(()=>{'use strict';
const token=<?=json_encode($token)?>,test=<?=$test?'true':'false'?>,stage=document.getElementById('stage'),eventName=document.getElementById('eventName'),categoryName=document.getElementById('categoryName'),screenState=document.getElementById('screenState'),pageState=document.getElementById('pageState'),connection=document.getElementById('connection'),fxLayer=document.getElementById('fxLayer');
let lastHash='',lastRevision='',busy=false,pollTimer=null,currentPage=1,pageTotal=1,lastType='holding',nextPageAt=0,backoffUntil=0,lastEffectVersion=0,effectRun=0,revealCountdownTimer=null,cycle={index:0,phase:'contestant',next:0},latest=null;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const label=value=>String(value||'').replace(/\brising\b/gi,'Intermediate').replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());
const chunk=(items,size)=>{const pages=[];for(let index=0;index<items.length;index+=size)pages.push(items.slice(index,index+size));return pages.length?pages:[[]]};
const empty=(title,message)=>'<div class="empty"><strong>'+esc(title)+'</strong><span>'+esc(message)+'</span></div>';
function setHeader(data){document.body.dataset.theme=data.state.theme||'midnight_wine';eventName.textContent=data.state.event_name||'BDC Dance Cup';categoryName.textContent='';}
const photo=item=>esc(item?.photo_url||'../../public/assets/img/default-competitor.svg');
const identity=item=>{const countries=Array.isArray(item?.countries)&&item.countries.length?item.countries:[item?.country].filter(Boolean),flags=Array.isArray(item?.flags)?item.flags:[],codes=Array.isArray(item?.country_codes)?item.country_codes:[];if(!countries.length)return '<div class="identity-meta"><span>Country not set</span></div>';return '<div class="identity-meta multi-country">'+countries.slice(0,5).map((country,index)=>{const code=String(codes[index]||'').toLowerCase().replace(/[^a-z]/g,'');const flag=code?'<img class="flag-image" src="../../public/assets/flags/'+esc(code)+'.svg" alt="'+esc(country)+' flag">':'<span class="flag">'+esc(flags[index]||'')+'</span>';return '<span class="identity-country">'+flag+'<span>'+esc(country)+'</span></span>'}).join('')+'</div>'};
function show(html,type,page=0,total=0){pageTotal=Math.max(1,total||1);const category=label(latest?.state?.category_name||'Dance Cup Category')+' · '+label(latest?.state?.round_name||'');stage.innerHTML='<div class="view"><div class="screen-category">'+esc(category)+'</div><div class="screen-content">'+html+'</div></div>';screenState.textContent=label(type);pageState.textContent=total>1?'Page '+page+' of '+total:'';}
function holding(data){stage.innerHTML='<div class="view" style="grid-template-rows:1fr"><div class="screen-content"><div class="holding"><h2>'+esc(data.state.event_name||'Dance Cup')+'</h2></div></div></div>';screenState.textContent='Holding Screen';pageState.textContent='';}
function contestant(entry){const eventLabel=latest?.state?.event_name||'Dance Cup';show(entry?'<div class="call"><div class="call-layout"><section class="number-panel"><div class="number-label">Contestant Number</div><div class="number">'+esc(entry.contestant_number)+'</div></section><section class="contestant-identity"><img class="profile-photo" src="'+photo(entry)+'" alt=""><div class="label">NOW PRESENTING</div><h2>'+esc(entry.display_name)+'</h2>'+identity(entry)+'</section><aside class="trophy-showcase"><img src="../../public/assets/img/sbta-dance-cup-champion-trophy.png" alt="SBTA Dance Cup trophy"><strong>'+esc(eventLabel)+'</strong></aside></div></div>':empty('Contestant pending','Select a contestant from Projection Control.'),'Contestant Call');}
function pagedCards(items,size,type,renderCard,data){const pages=chunk(items,size),total=pages.length;currentPage=Math.max(1,Math.min(total,currentPage));const cards=pages[currentPage-1].map(renderCard).join('');show(cards?'<div class="grid '+(size>=10?'compact':'')+'">'+cards+'</div>':empty(type+' pending','Add records in the Dance Cup category workspace.'),type,currentPage,total);schedulePage(total,data);}
function judgeCall(data){const total=data.judges.length;currentPage=Math.max(1,Math.min(Math.max(1,total),currentPage));const judge=data.judges[currentPage-1];const card=judge?'<div class="judge-call"><article class="card judge-card judge-call-card"><div><img class="profile-photo" src="'+photo(judge)+'" alt=""><span class="kicker">J'+esc(judge.judge_order)+(Number(judge.is_chief)?' · Chief Judge':' · Judge')+'</span><strong>'+esc(judge.judge_name)+'</strong>'+identity(judge)+'</div></article></div>':empty('Judge Call pending','Assign judges in the Dance Cup category workspace.');show(card,'Calling Judges',currentPage,Math.max(1,total));schedulePage(total,data);}
function judges(data,progress=false){const contestantDone=data.judges.filter(j=>j.contestant_status==='complete').length,finalDone=data.judges.filter(j=>Number(j.final_submitted)===1).length,bib=(data.progress_entry||data.active_entry)?.contestant_number;const cards=j=>{const current=j.contestant_status||'pending',currentText=current==='complete'?'Completed · No. '+(bib||'—'):current==='in_progress'?'Scoring · No. '+(bib||'—'):'Pending · No. '+(bib||'—');return '<article class="card judge-card contestant-'+esc(current.replace('_','-'))+'"><div><img class="profile-photo" src="'+photo(j)+'" alt=""><span class="kicker">J'+esc(j.judge_order)+(Number(j.is_chief)?' · Chief Judge':'')+'</span><strong>'+esc(j.judge_name)+'</strong>'+identity(j)+'<div class="judge-status-stack"><small class="status current '+esc(current.replace('_','-'))+'">'+esc(currentText)+'</small><small class="status final '+(Number(j.final_submitted)===1?'submitted':'pending')+'">'+(Number(j.final_submitted)===1?'Final submitted':'Final pending')+'</small></div></div></article>'};if(progress){const pages=chunk(data.judges,8),total=pages.length;currentPage=Math.max(1,Math.min(total,currentPage));show('<div class="progress-wrap"><div class="progress-summary"><span>Contestant No. '+esc(bib||'—')+': <b>'+contestantDone+' / '+data.judges.length+'</b> judges complete</span><span class="waiting">Final submission: '+finalDone+' / '+data.judges.length+'</span></div><div class="grid">'+pages[currentPage-1].map(cards).join('')+'</div></div>','Scoring Progress',currentPage,total);schedulePage(total,data);}else pagedCards(data.judges,Math.max(1,data.judges.length),'Judges',cards,data);}
function contestants(data){const pages=chunk(data.entries,10),total=pages.length;currentPage=Math.max(1,Math.min(total,currentPage));const page=pages[currentPage-1],rows=Math.max(1,Math.ceil(page.length/5)),cards=page.map(entry=>'<article class="card contestant-card"><div><span class="contestant-photo-frame"><img class="profile-photo" src="'+photo(entry)+'" alt=""></span><span class="kicker">Contestant</span><strong class="bib">'+esc(entry.contestant_number)+'</strong><small class="contestant-name">'+esc(entry.display_name)+'</small>'+identity(entry)+'</div></article>').join('');show(cards?'<div class="grid compact contestant-grid rows-'+rows+'">'+cards+'</div>':empty('All Contestants pending','Add records in the Dance Cup category workspace.'),'All Contestants',currentPage,total);schedulePage(total,data);}
function results(data){const pages=chunk(data.results,8),total=pages.length;currentPage=Math.max(1,Math.min(total,currentPage));const rows=pages[currentPage-1].map(row=>{const scored=Number(row.has_score)===1;return '<div class="rank-row"><span class="place">'+(scored?esc(row.placement):'—')+'</span><img class="rank-photo" src="'+photo(row)+'" alt=""><span class="number">No. '+esc(row.contestant_number)+'</span><span class="name">'+esc(row.display_name)+' '+esc(row.flag||'')+'</span><span class="score">'+(scored?Number(row.total_score).toLocaleString(undefined,{maximumFractionDigits:2}):'Not scored')+'</span></div>'}).join('');show(rows?'<div class="board">'+rows+'</div>':empty('Scores pending','Scores will appear after judges begin scoring.'),'Live Scoreboard',currentPage,total);schedulePage(total,data);}
function podium(data){const top=data.results.filter(row=>Number(row.has_score)===1&&row.placement!==null).slice(0,3),order=[top[1],top[0],top[2]],classes=['second','first','third'],medals=['🥈','🥇','🥉'],reveal=String(data.state.reveal_place||'3');const cards=order.map((row,index)=>{if(!row)return '';const visible=reveal==='all'||Number(row.placement)>=Number(reveal);return '<article class="podium-card '+classes[index]+(visible?'':' hidden-slot')+'"><div class="medal">'+medals[index]+'</div><img class="podium-photo" src="'+photo(row)+'" alt=""><div class="place">'+label(row.placement+(Number(row.placement)===1?'st':Number(row.placement)===2?'nd':'rd'))+'</div><div class="number">No. '+esc(row.contestant_number)+'</div><div class="name">'+esc(row.display_name)+'</div>'+identity(row)+'<div class="score">'+Number(row.total_score).toLocaleString(undefined,{maximumFractionDigits:2})+' points</div></article>'}).join('');show(cards?'<div class="podium">'+cards+'</div>':empty('Podium locked','Calculate results before revealing the winners.'),'Winner Podium');}
function countdownToPodium(data){if(revealCountdownTimer)clearInterval(revealCountdownTimer);let seconds=5;const place=String(data.state.reveal_place||'3'),placeText=place==='1'?'Champion':place==='2'?'2nd Place':'3rd Place';const paint=()=>{stage.innerHTML='<div class="result-countdown"><div><div class="count-label">Result Reveal</div><div class="count-number">'+seconds+'</div><div class="count-place">'+placeText+'</div></div></div>';screenState.textContent='Result Countdown';pageState.textContent='';};paint();revealCountdownTimer=setInterval(()=>{seconds-=1;if(seconds>0){paint();return}clearInterval(revealCountdownTimer);revealCountdownTimer=null;podium(data);playEffect(data.state);},1000);}
function schedulePage(total,data){pageTotal=Math.max(1,total||1);if(total<2){nextPageAt=0;return}if(Number(data.state.auto_page)){if(!nextPageAt)nextPageAt=Date.now()+Math.max(5,Number(data.state.page_delay)||10)*1000}else nextPageAt=0;}
function clearEffectAfter(run,milliseconds){setTimeout(()=>{if(run===effectRun)fxLayer.innerHTML=''},milliseconds)}
function launchFireworks(count=26,run=effectRun){const colours=['#f6c945','#ff4d6d','#6ee7ff','#9b7bff','#fff4bd','#65f29a'];for(let burstIndex=0;burstIndex<count;burstIndex++){setTimeout(()=>{if(run!==effectRun)return;const burst=document.createElement('div');burst.className='firework-burst';burst.style.left=(10+Math.random()*80)+'vw';burst.style.top=(10+Math.random()*62)+'vh';const colour=colours[burstIndex%colours.length];for(let sparkIndex=0;sparkIndex<24;sparkIndex++){const spark=document.createElement('i');spark.className='firework-spark';spark.style.setProperty('--spark',colour);spark.style.setProperty('--angle',(sparkIndex*15)+'deg');spark.style.setProperty('--distance',(95+Math.random()*150)+'px');burst.appendChild(spark)}fxLayer.appendChild(burst);setTimeout(()=>burst.remove(),2400)},350+burstIndex*340)}}
function playEffect(state){const version=Number(state.effect_version||0);if(!version||version===lastEffectVersion)return;lastEffectVersion=version;const run=++effectRun;fxLayer.innerHTML='';const type=state.effect_type||'none';if(type==='none')return;fxLayer.innerHTML='<div class="fx-cinematic"></div>';if(type==='fireworks'){launchFireworks(26,run);clearEffectAfter(run,12000);return}if(type==='champion_impact'){fxLayer.insertAdjacentHTML('beforeend','<div class="fx-impact">🏆</div>');clearEffectAfter(run,7600);return}const symbols={hearts:['💖','💗','❤️'],balloons:['🎈','🎈','🎈'],heart_smiles:['🥰','😍','💖'],finger_hearts:['🫰','🫰🏻','🫰🏽'],gold_rain:['✨','⭐','🌟']}[type]||['✨'];for(let i=0;i<84;i++){const particle=document.createElement('span');particle.className='fx-particle';particle.textContent=symbols[i%symbols.length];particle.style.left=(Math.random()*100)+'vw';particle.style.setProperty('--duration',(6.5+Math.random()*3.5)+'s');particle.style.setProperty('--drift',((Math.random()-.5)*34)+'vw');particle.style.animationDelay=(Math.random()*2.4)+'s';fxLayer.appendChild(particle)}clearEffectAfter(run,11200);}
function render(data,force=false){const previous=latest;latest=data;setHeader(data);let type=data.state.screen_type||'holding';if((type==='results'||type==='podium')&&!Number(data.state.results_unlocked))type='holding';const revealChanged=type==='podium'&&force&&(!previous||previous.state.screen_type!=='podium'||String(previous.state.reveal_place)!==String(data.state.reveal_place));if(type!==lastType){lastType=type;currentPage=Math.max(1,Number(data.state.page_number)||1);nextPageAt=0}else if(force)currentPage=Math.max(1,Number(data.state.page_number)||currentPage);if(revealChanged){countdownToPodium(data);return}if(type==='holding')holding(data);else if(type==='contestant')contestant(data.active_entry);else if(type==='contestants')contestants(data);else if(type==='judge_call')judgeCall(data);else if(type==='judges')judges(data,false);else if(type==='scoring')judges(data,true);else if(type==='results')results(data);else if(type==='podium')podium(data);else holding(data);playEffect(data.state);}
function advanceAutoPage(){if(!latest||!nextPageAt||Date.now()<nextPageAt)return;currentPage=currentPage>=pageTotal?1:currentPage+1;nextPageAt=0;render(latest);}
function advanceRunOfShow(data){if(!Number(data.state.auto_cycle)||!data.entries.length)return;if(!cycle.next){cycle.index=Math.max(0,data.entries.findIndex(entry=>Number(entry.id)===Number(data.state.active_entry_id)));cycle.phase='contestant';cycle.next=Date.now()+Number(data.state.contestant_seconds||12)*1000}if(Date.now()<cycle.next)return;if(cycle.phase==='contestant'){cycle.phase='holding';cycle.next=Date.now()+Number(data.state.holding_seconds||8)*1000;holding(data)}else{cycle.phase='contestant';cycle.index=(cycle.index+1)%data.entries.length;cycle.next=Date.now()+Number(data.state.contestant_seconds||12)*1000;contestant(data.entries[cycle.index])}}
function schedulePoll(delay=1000){clearTimeout(pollTimer);pollTimer=setTimeout(poll,delay)}
async function poll(){if(document.hidden||busy){schedulePoll(1000);return}if(Date.now()<backoffUntil){schedulePoll(Math.max(1000,backoffUntil-Date.now()));return}busy=true;const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),7000);let nextDelay=1000;try{const since=lastRevision?'&since='+encodeURIComponent(lastRevision):'';const response=await fetch('./projection-feed.php?token='+encodeURIComponent(token)+(test?'&data_mode=test':'')+since+'&_='+Date.now(),{cache:'no-store',credentials:'same-origin',headers:{Accept:'application/json'},signal:controller.signal});if(response.status===429){backoffUntil=Date.now()+10000;nextDelay=10000;throw new Error('Rate limited')}const contentType=response.headers.get('content-type')||'';if(!contentType.includes('application/json'))throw new Error('Invalid feed response');const data=await response.json();if(!response.ok||!data.ok)throw new Error('Feed unavailable');if(data.revision)lastRevision=String(data.revision);if(data.unchanged){if(latest)advanceRunOfShow(latest);connection.style.display='none';return}const hash=JSON.stringify([data.state.state_version,data.state.screen_type,data.state.theme,data.state.page_number,data.state.auto_page,data.state.page_delay,data.entries,data.judges,data.results,data.active_entry,data.progress_entry]);if(hash!==lastHash){const stateChanged=lastHash!==''&&latest&&Number(data.state.state_version)!==Number(latest.state.state_version);lastHash=hash;render(data,stateChanged);cycle.next=0}advanceRunOfShow(data);connection.style.display='none'}catch(error){nextDelay=Math.max(nextDelay,2500);connection.textContent=error?.name==='AbortError'?'Live update timed out. Retrying…':'Live updates interrupted. Retrying…';connection.style.display='block'}finally{clearTimeout(timeout);busy=false;schedulePoll(nextDelay)}}
setInterval(advanceAutoPage,500);poll();document.addEventListener('visibilitychange',()=>{if(!document.hidden){clearTimeout(pollTimer);poll()}});
})();
</script>
<script>
(function(){
 const badge=document.querySelector('[data-dc-fullscreen-ready="1"]');
 if(!badge)return;
 const enter=()=>{if(document.fullscreenElement)return;const root=document.documentElement,request=root.requestFullscreen||root.webkitRequestFullscreen;if(request){const result=request.call(root);if(result&&typeof result.catch==='function')result.catch(()=>{});}};
 badge.addEventListener('click',enter);
 badge.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();enter();}});
})();
</script>
</body>
</html>
