<?php
declare(strict_types=1);
require dirname(__DIR__,3).'/bootstrap.php';
use App\Core\Database;use App\Services\JudgeDirectoryService;use App\Services\ProfileIntegrationAuth;use App\Services\JackJillCompetitorEligibilityService;
header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');
function eventDirectoryResponse(int $status,array $body):never{http_response_code($status);echo json_encode($body,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if($_SERVER['REQUEST_METHOD']!=='GET')eventDirectoryResponse(405,['ok'=>false,'error'=>'GET required.']);$type=strtolower(trim((string)($_GET['type']??'')));$query=trim((string)($_GET['q']??''));$mode=strtolower(trim((string)($_GET['data_mode']??'live')));$dance=strtolower(trim((string)($_GET['dance_style']??'')));$queryLength=function_exists('mb_strlen')?mb_strlen($query,'UTF-8'):strlen($query);if(!in_array($type,['competitor','judge'],true)||$queryLength<2)eventDirectoryResponse(400,['ok'=>false,'error'=>'type and a search query of at least 2 characters are required.']);if(!in_array($mode,['test','live'],true))eventDirectoryResponse(400,['ok'=>false,'error'=>'data_mode must be test or live.']);if($type==='competitor'&&!in_array($dance,['bachata','salsa'],true))eventDirectoryResponse(400,['ok'=>false,'error'=>'dance_style must be bachata or salsa for Jack & Jill competitor search.']);$context='events:directory:'.$type.':'.$mode.':'.$query;if(!ProfileIntegrationAuth::verify('',$context)||!ProfileIntegrationAuth::allowedScope('events:read'))eventDirectoryResponse(401,['ok'=>false,'error'=>'Invalid signature or missing events:read scope.']);$pdo=Database::connection();$like='%'.$query.'%';
if($type==='competitor'){$lower=static fn(string $value):string=>function_exists('mb_strtolower')?mb_strtolower($value,'UTF-8'):strtolower($value);$needle=$lower($query);$rows=array_values(array_filter(JackJillCompetitorEligibilityService::directory($pdo,$dance,null,1500),static fn(array $row):bool=>strcasecmp((string)$row['identity_code'],$query)===0||str_contains($lower((string)$row['exact_name']),$needle)));$rows=array_slice($rows,0,25);}
else{JudgeDirectoryService::ensure($pdo);$q=$pdo->prepare("SELECT judge_code,full_name,display_name,country,dance_styles,judge_role,qualified_divisions,qualified_rounds,status FROM bdc_judges WHERE status='active' AND (judge_code=:exact OR full_name LIKE :term OR display_name LIKE :term2) ORDER BY judge_code=:order_exact DESC,COALESCE(NULLIF(display_name,''),full_name),id LIMIT 25");$q->execute(['exact'=>strtoupper($query),'term'=>$like,'term2'=>$like,'order_exact'=>strtoupper($query)]);$rows=$q->fetchAll();}
eventDirectoryResponse(200,['ok'=>true,'type'=>$type,'data_mode'=>$mode,'results'=>$rows]);
