<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use App\Core\Database;
use App\Services\LiveDisplaySessionService;
use App\Services\CountryFlagService;
use App\Services\JudgeDirectoryService;
use App\Services\ProjectionNameService;
$pdo=Database::connection();$token=trim((string)($_GET['token']??''));$session=LiveDisplaySessionService::byToken($pdo,$token);
if(!$session||(string)$session['screen_type']!=='final_results'||empty($session['results_unlocked'])){http_response_code(403);exit('Final results are not available.');}
$projectorTheme=(string)($session['screen_theme']??'midnight_burgundy');
$test=$session['data_mode']==='test';$roundId=(int)$session['current_round_id'];$rt=$test?'bdc_test_scoring_rounds':'bdc_scoring_rounds';$et=$test?'bdc_test_events':'bdc_events';$jt=$test?'bdc_test_scoring_judges':'bdc_scoring_judges';$ent=$test?'bdc_test_scoring_entries':'bdc_scoring_entries';$pt=$test?'bdc_test_scoring_final_pairs':'bdc_scoring_final_pairs';$frt=$test?'bdc_test_scoring_final_results':'bdc_scoring_final_results';$mt=$test?'bdc_test_scoring_final_marks':'bdc_scoring_final_marks';
$q=$pdo->prepare("SELECT r.division,r.round_type,e.name event_name FROM {$rt} r JOIN {$et} e ON e.id=r.event_id WHERE r.id=:r AND e.id=:e");$q->execute(['r'=>$roundId,'e'=>(int)($session['active_event_id']??$session['event_id'])]);$round=$q->fetch();if(!$round){http_response_code(404);exit('Round not found.');}
try{JudgeDirectoryService::ensure($pdo);JudgeDirectoryService::backfillAssignments($pdo);}catch(Throwable){}
$q=$pdo->prepare("SELECT sj.id,sj.judge_order,sj.judge_name,sj.is_chief,j.full_name,j.country,j.country_code FROM {$jt} sj LEFT JOIN bdc_judges j ON j.id=sj.judge_id WHERE sj.round_id=:r ORDER BY sj.judge_order,sj.id");$q->execute(['r'=>$roundId]);$judges=$q->fetchAll();
$competitorTable=$test?'bdc_test_competitors':'bdc_competitors';
$q=$pdo->prepare("SELECT fp.id,fp.pair_number,le.display_name leader_name,fe.display_name follower_name,lc.country leader_country,fc.country follower_country,fr.final_rank FROM {$pt} fp JOIN {$ent} le ON le.id=fp.leader_entry_id LEFT JOIN {$ent} fe ON fe.id=fp.follower_entry_id LEFT JOIN {$competitorTable} lc ON lc.id=le.competitor_id LEFT JOIN {$competitorTable} fc ON fc.id=fe.competitor_id LEFT JOIN {$frt} fr ON fr.pair_id=fp.id AND fr.round_id=fp.round_id WHERE fp.round_id=:r AND fp.pairing_status='confirmed' ORDER BY COALESCE(fr.final_rank,999999),fp.pair_number");$q->execute(['r'=>$roundId]);$pairs=$q->fetchAll();
$pairs=ProjectionNameService::abbreviateRows($pairs,['leader_name','follower_name']);
$judgeProjectionNames=[];foreach($judges as $judgeIndex=>$judge)$judgeProjectionNames[(string)$judgeIndex]=trim((string)($judge['full_name']?:$judge['judge_name']));$judgeProjectionNames=ProjectionNameService::abbreviateNames($judgeProjectionNames);foreach($judges as $judgeIndex=>&$judge){$judge['full_name']=$judgeProjectionNames[(string)$judgeIndex]??'';$judge['judge_name']=$judge['full_name'];}unset($judge);
$q=$pdo->prepare("SELECT pair_id,judge_id,rank_value FROM {$mt} WHERE round_id=:r");$q->execute(['r'=>$roundId]);$marks=[];foreach($q->fetchAll() as $m)$marks[(int)$m['pair_id']][(int)$m['judge_id']]=$m['rank_value'];
ob_start(static fn(string $html):string=>str_replace(['</title>','<body>'],['</title><link rel="stylesheet" href="../public/css/projector-responsive-v344.css?v=344"><link rel="stylesheet" href="../public/css/projector-themes-v350.css?v=350">','<body data-projector-theme="'.e($projectorTheme).'">'],$html));
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Final Relative Placement</title><style>*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;background:#030509;color:#fff;font-family:Arial,sans-serif;overflow:hidden}.stage{width:100vw;height:100vh;padding:1.4vw 1.7vw;background:radial-gradient(circle at top,#4a101e,#111827 52%,#030509);display:flex;flex-direction:column}.event{text-align:center;font-size:clamp(17px,1.55vw,38px);font-weight:900}.meta{text-align:center;color:#ffb7c3;font-size:clamp(10px,.8vw,20px)}h1{text-align:center;font-size:clamp(20px,1.8vw,44px);margin:.45em 0}.wrap{flex:1;min-height:0;display:flex;align-items:flex-start;justify-content:center}table{width:100%;border-collapse:collapse;table-layout:fixed;background:rgba(17,24,39,.88);font-size:clamp(8px,.78vw,18px)}th,td{border:1px solid rgba(255,255,255,.28);padding:.42em .25em;text-align:center}th{background:#7d2638}th:nth-child(2),td:nth-child(2){width:24%;text-align:left;padding-left:.7em}.key{display:flex;flex-wrap:wrap;gap:.25em 1.1em;padding-top:.7em;font-size:clamp(7px,.62vw,14px)}.test{position:absolute;top:.7em;left:.7em;background:#ffc107;color:#111;padding:.35em .7em;border-radius:6px;font-weight:900}</style></head><body><div class="stage"><?php if($test):?><div class="test">TEST MODE</div><?php endif;?><div class="event"><?=e($round['event_name'])?></div><div class="meta"><?=e(strtoupper(str_replace('_',' ',$round['division'])))?> · FINAL</div><h1>FINAL RELATIVE PLACEMENT</h1><div class="wrap"><table><thead><tr><th>Final</th><th>Couple</th><?php foreach($judges as $j):?><th>J<?=(int)$j['judge_order']?><?=(int)$j['is_chief']?'★':''?></th><?php endforeach;?></tr></thead><tbody>
<?php foreach($pairs as $p):$leaderFlag=CountryFlagService::emoji($p['leader_country']??null);$followerFlag=CountryFlagService::emoji($p['follower_country']??null);?><tr><td><?=isset($p['final_rank'])?'#'.(int)$p['final_rank']:'—'?></td><td><strong>Couple <?=(int)$p['pair_number']?></strong> · <?=$leaderFlag!==''?e($leaderFlag).' ':''?><?=e($p['leader_name'])?> &amp; <?=$followerFlag!==''?e($followerFlag).' ':''?><?=e($p['follower_name'])?></td>
<?php foreach($judges as $j):?><td><?=e((string)($marks[(int)$p['id']][(int)$j['id']]??''))?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><div class="key">
<?php foreach($judges as $j):$judgeFlag=CountryFlagService::emoji($j['country_code']?:($j['country']??null));?><span><strong>J<?=(int)$j['judge_order']?></strong> · <?=$judgeFlag!==''?e($judgeFlag).' ':''?><?=e($j['full_name']?:$j['judge_name'])?><?=(int)$j['is_chief']?' ★ Chief Judge':''?></span><?php endforeach;?></div></div></body></html>
