<?php
declare(strict_types=1);

require dirname(__DIR__).'/bootstrap.php';

use App\Core\Database;
use App\Services\AutomaticJudgeBrowserService;
use App\Services\JudgingCriteriaService;

$pdo=Database::connection();
$token=trim((string)($_GET['token']??$_POST['token']??''));
$session=AutomaticJudgeBrowserService::byToken($pdo,$token);
if(!$session||($session['scoring_mode']??'')!=='automated'){http_response_code(404);exit('Judge scoring link not found or expired.');}
$sessionId=(int)$session['id'];$roundId=(int)$session['round_id'];$judgeId=(int)$session['judge_id'];
if(isset($_GET['status'])){judgeJson(['status'=>$session['status'],'criteria_required'=>JudgingCriteriaService::requiresAcceptance($session)]);}
AutomaticJudgeBrowserService::markOpened($pdo,$sessionId);
$locked=(string)$session['status']==='submitted';$isFinal=(string)$session['round_type']==='final';$error='';$notice='';

$roundStmt=$pdo->prepare('SELECT yes_count,callback_count,yes_weight,alt1_weight,alt2_weight,alt3_weight FROM bdc_scoring_rounds WHERE id=:round');
$roundStmt->execute(['round'=>$roundId]);$weights=$roundStmt->fetch()?:['yes_count'=>10,'yes_weight'=>10,'alt1_weight'=>4.5,'alt2_weight'=>4.3,'alt3_weight'=>4.2];
$yesLimit=max(1,(int)($weights['yes_count']??10));
$configuredFinalRankLimit=max(1,(int)($weights['callback_count']??10));

function judgeJson(array $data,int $status=200):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}

function heatsSelectionState(PDO $pdo,int $roundId,int $judgeId,string $role):array
{
    $stmt=$pdo->prepare("SELECT
        SUM(CASE WHEN m.mark_type='yes' THEN 1 ELSE 0 END) yes_count,
        SUM(CASE WHEN m.mark_type='alt' AND m.alt_rank=1 THEN 1 ELSE 0 END) alt1_count,
        SUM(CASE WHEN m.mark_type='alt' AND m.alt_rank=2 THEN 1 ELSE 0 END) alt2_count,
        SUM(CASE WHEN m.mark_type='alt' AND m.alt_rank=3 THEN 1 ELSE 0 END) alt3_count
        FROM bdc_scoring_marks m
        JOIN bdc_scoring_entries e ON e.id=m.entry_id
        WHERE m.round_id=:round AND m.judge_id=:judge AND e.dance_role=:role AND e.entry_status='active'");
    $stmt->execute(['round'=>$roundId,'judge'=>$judgeId,'role'=>$role]);
    $row=$stmt->fetch()?:[];
    return ['yes'=>(int)($row['yes_count']??0),'A1'=>(int)($row['alt1_count']??0),'A2'=>(int)($row['alt2_count']??0),'A3'=>(int)($row['alt3_count']??0)];
}

function saveHeatsJudgeMark(PDO $pdo,int $roundId,int $judgeId,int $entryId,string $raw,array $weights):array
{
    $raw=strtoupper(trim($raw));
    $entry=$pdo->prepare("SELECT e.id,e.dance_role,j.scoring_scope FROM bdc_scoring_entries e JOIN bdc_scoring_judges j ON j.id=:judge WHERE e.id=:entry AND e.round_id=:round AND e.entry_status='active'");
    $entry->execute(['judge'=>$judgeId,'entry'=>$entryId,'round'=>$roundId]);$row=$entry->fetch();
    if(!$row)throw new RuntimeException('Competitor is not available for this round.');
    $role=(string)$row['dance_role'];
    if(!in_array((string)$row['scoring_scope'],['all',$role],true))throw new RuntimeException('This competitor is outside your assigned judging panel.');
    if($raw===''||$raw==='NO'){$pdo->prepare('DELETE FROM bdc_scoring_marks WHERE round_id=:round AND entry_id=:entry AND judge_id=:judge')->execute(['round'=>$roundId,'entry'=>$entryId,'judge'=>$judgeId]);return heatsSelectionState($pdo,$roundId,$judgeId,$role);}
    $type='';$alt=null;$weight=0.0;
    if(in_array($raw,['1','Y','YES'],true)){$type='yes';$weight=(float)$weights['yes_weight'];}
    elseif(in_array($raw,['A1','2'],true)){$type='alt';$alt=1;$weight=(float)$weights['alt1_weight'];}
    elseif(in_array($raw,['A2','3'],true)){$type='alt';$alt=2;$weight=(float)$weights['alt2_weight'];}
    elseif(in_array($raw,['A3','4'],true)){$type='alt';$alt=3;$weight=(float)$weights['alt3_weight'];}
    elseif($raw==='LATER'){$type='blank';$alt=9;$weight=0.0;}
    else throw new RuntimeException('Choose YES, A1, A2, A3, LATER or NO.');

    if($type==='yes'){
        $limit=max(1,(int)($weights['yes_count']??10));
        $count=$pdo->prepare("SELECT COUNT(*) FROM bdc_scoring_marks m JOIN bdc_scoring_entries e ON e.id=m.entry_id WHERE m.round_id=:round AND m.judge_id=:judge AND e.dance_role=:role AND e.entry_status='active' AND m.mark_type='yes' AND m.entry_id<>:entry");
        $count->execute(['round'=>$roundId,'judge'=>$judgeId,'role'=>$role,'entry'=>$entryId]);
        if((int)$count->fetchColumn()>=$limit)throw new RuntimeException('Maximum '.$limit.' YES selections allowed for '.ucfirst($role).'s in this round. Clear or change another YES first.');
    }
    if($type==='alt'&&$alt!==null){
        $duplicate=$pdo->prepare("SELECT e.display_name FROM bdc_scoring_marks m JOIN bdc_scoring_entries e ON e.id=m.entry_id WHERE m.round_id=:round AND m.judge_id=:judge AND e.dance_role=:role AND e.entry_status='active' AND m.mark_type='alt' AND m.alt_rank=:alt AND m.entry_id<>:entry LIMIT 1");
        $duplicate->execute(['round'=>$roundId,'judge'=>$judgeId,'role'=>$role,'alt'=>$alt,'entry'=>$entryId]);
        if($name=$duplicate->fetchColumn())throw new RuntimeException('A'.$alt.' is already assigned to '.$name.' for '.ucfirst($role).'s. Each alternate rank can be used only once.');
    }

    $pdo->prepare("INSERT INTO bdc_scoring_marks(round_id,entry_id,judge_id,mark_type,alt_rank,weighted_score,updated_by) VALUES(:round,:entry,:judge,:type,:alt,:weight,NULL) ON DUPLICATE KEY UPDATE mark_type=VALUES(mark_type),alt_rank=VALUES(alt_rank),weighted_score=VALUES(weighted_score),updated_by=NULL,updated_at=NOW()")
        ->execute(['round'=>$roundId,'entry'=>$entryId,'judge'=>$judgeId,'type'=>$type,'alt'=>$alt,'weight'=>$weight]);
    return heatsSelectionState($pdo,$roundId,$judgeId,$role);
}

function saveFinalJudgeRank(PDO $pdo,int $roundId,int $judgeId,int $pairId,string $raw,int $rankLimit):void
{
    if($raw===''){$pdo->prepare('DELETE FROM bdc_scoring_final_marks WHERE round_id=:round AND pair_id=:pair AND judge_id=:judge')->execute(['round'=>$roundId,'pair'=>$pairId,'judge'=>$judgeId]);return;}
    if(!ctype_digit($raw))throw new RuntimeException('Enter a whole-number rank.');
    $countStmt=$pdo->prepare("SELECT COUNT(*) FROM bdc_scoring_final_pairs WHERE round_id=:round AND pairing_status='confirmed'");$countStmt->execute(['round'=>$roundId]);$count=(int)$countStmt->fetchColumn();
    $rank=(int)$raw;if($rank<1||$rank>$rankLimit)throw new RuntimeException('Ranks must be between 1 and '.$rankLimit.'.');
    $pair=$pdo->prepare("SELECT id FROM bdc_scoring_final_pairs WHERE id=:pair AND round_id=:round AND pairing_status='confirmed'");$pair->execute(['pair'=>$pairId,'round'=>$roundId]);if(!(int)$pair->fetchColumn())throw new RuntimeException('Final pair not found.');
    $duplicate=$pdo->prepare("SELECT pair_id FROM bdc_scoring_final_marks WHERE round_id=:round AND judge_id=:judge AND rank_value=:rank AND pair_id<>:pair LIMIT 1");$duplicate->execute(['round'=>$roundId,'judge'=>$judgeId,'rank'=>$rank,'pair'=>$pairId]);if($duplicate->fetchColumn())throw new RuntimeException('Rank '.$rank.' is already assigned to another couple.');
    $pdo->prepare("INSERT INTO bdc_scoring_final_marks(round_id,pair_id,judge_id,rank_value,updated_by) VALUES(:round,:pair,:judge,:rank,NULL) ON DUPLICATE KEY UPDATE rank_value=VALUES(rank_value),updated_by=NULL,updated_at=NOW()")
        ->execute(['round'=>$roundId,'pair'=>$pairId,'judge'=>$judgeId,'rank'=>$rank]);
}

function validateJudgeComplete(PDO $pdo,array $session,int $yesLimit,int $rankLimit):void
{
    $roundId=(int)$session['round_id'];$judgeId=(int)$session['judge_id'];
    if((string)$session['round_type']==='final'){
        $total=$pdo->prepare("SELECT COUNT(*) FROM bdc_scoring_final_pairs WHERE round_id=:round AND pairing_status='confirmed'");$total->execute(['round'=>$roundId]);$total=(int)$total->fetchColumn();
        if($total<1)throw new RuntimeException('Final pairing has not been confirmed yet.');
        $ranks=$pdo->prepare("SELECT rank_value FROM bdc_scoring_final_marks WHERE round_id=:round AND judge_id=:judge ORDER BY rank_value");$ranks->execute(['round'=>$roundId,'judge'=>$judgeId]);$values=array_map('intval',$ranks->fetchAll(PDO::FETCH_COLUMN));
        if(count($values)!==$rankLimit||$values!==range(1,$rankLimit))throw new RuntimeException('Assign each Top '.$rankLimit.' rank exactly once before submitting.');
        return;
    }
    $later=$pdo->prepare("SELECT COUNT(*) FROM bdc_scoring_marks WHERE round_id=:round AND judge_id=:judge AND mark_type='blank' AND alt_rank=9");$later->execute(['round'=>$roundId,'judge'=>$judgeId]);
    if((int)$later->fetchColumn()>0)throw new RuntimeException('Resolve every LATER selection before submitting.');
    $scope=(string)$session['scoring_scope'];
    foreach(['leader','follower'] as $role){
        if(!in_array($scope,['all',$role],true))continue;
        $totalStmt=$pdo->prepare("SELECT COUNT(*) FROM bdc_scoring_entries WHERE round_id=:round AND dance_role=:role AND entry_status='active'");$totalStmt->execute(['round'=>$roundId,'role'=>$role]);$total=(int)$totalStmt->fetchColumn();
        if($total<1)continue;
        $state=heatsSelectionState($pdo,$roundId,$judgeId,$role);
        $requiredYes=min($yesLimit,$total);
        if($state['yes']!==$requiredYes)throw new RuntimeException('Select exactly '.$requiredYes.' YES for '.ucfirst($role).'s before submitting. Currently selected: '.$state['yes'].'.');
        $requiredAlternates=min(3,max(0,$total-$requiredYes));
        foreach(['A1','A2','A3'] as $index=>$alt){$required=$index<$requiredAlternates?1:0;if($state[$alt]!==$required)throw new RuntimeException(($required?'Select exactly one ':'Do not select ').$alt.' for '.ucfirst($role).'s before submitting.');}
    }
}

if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        $fresh=AutomaticJudgeBrowserService::byToken($pdo,$token);if(!$fresh)throw new RuntimeException('Judge scoring link expired.');
        $action=(string)($_POST['action']??'save');
        if($action==='accept_criteria'){
            if(($_POST['criteria_confirm']??'')!=='1')throw new RuntimeException('Confirm that you have read and accept the judging criteria.');
            AutomaticJudgeBrowserService::acceptCriteria($pdo,$sessionId);$session=AutomaticJudgeBrowserService::byToken($pdo,$token);$notice='Criteria accepted. You may begin scoring.';
        }elseif((string)$fresh['status']==='submitted')throw new RuntimeException('Your scores have already been submitted and locked.');
        elseif(JudgingCriteriaService::requiresAcceptance($fresh))throw new RuntimeException('Read and accept the judging criteria before scoring.');
        elseif($action==='save_score'){
            if($isFinal){saveFinalJudgeRank($pdo,$roundId,$judgeId,(int)($_POST['pair_id']??0),trim((string)($_POST['value']??'')),max(1,(int)($weights['callback_count']??1)));$state=null;}
            else $state=saveHeatsJudgeMark($pdo,$roundId,$judgeId,(int)($_POST['entry_id']??0),trim((string)($_POST['value']??'')),$weights);
            AutomaticJudgeBrowserService::markSaved($pdo,$sessionId);
            if(isset($_POST['ajax']))judgeJson(['ok'=>true,'saved_at'=>date('H:i:s'),'selection_state'=>$state]);
            $notice='Draft saved.';
        }elseif($action==='submit'){
            validateJudgeComplete($pdo,$fresh,$yesLimit,max(1,(int)($weights['callback_count']??1)));AutomaticJudgeBrowserService::submit($pdo,$sessionId);$locked=true;$notice='Scores submitted and locked. Thank you.';
        }
    }catch(Throwable $e){if(isset($_POST['ajax']))judgeJson(['ok'=>false,'error'=>$e->getMessage()],422);$error=$e->getMessage();}
}

$criteriaRequired=JudgingCriteriaService::requiresAcceptance($session);
if($criteriaRequired){
    $category=ucwords(str_replace('_',' ',(string)$session['division']));
    ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Judging Criteria | BDC</title><style>*{box-sizing:border-box}body{margin:0;background:#f4f6f9;color:#172033;font-family:Arial,sans-serif}.top{background:linear-gradient(110deg,#111,#42101c);color:#fff;padding:22px 18px;border-bottom:5px solid #d10f32}.wrap{max-width:760px;margin:auto;padding:18px}.card{background:#fff;border:1px solid #dfe3e8;border-radius:14px;padding:20px;box-shadow:0 3px 12px rgba(15,23,42,.06)}.weights{display:grid;grid-template-columns:1fr 1fr;gap:8px}.weight{border:1px solid #dfe3e8;border-radius:9px;padding:10px;display:flex;justify-content:space-between}.rule{background:#eaf3ff;border-left:4px solid #0D6EFD;padding:12px;margin:16px 0}.confirm{display:flex;gap:10px;align-items:flex-start;margin:18px 0}.start{width:100%;border:0;border-radius:10px;padding:14px;background:#146C43;color:#fff;font-size:17px;font-weight:800}.start:disabled{opacity:.4}.error{background:#ffe6e6;color:#8a1010;padding:12px;border-radius:9px;margin-bottom:12px}@media(max-width:520px){.weights{grid-template-columns:1fr}}</style></head><body><header class="top"><div class="wrap" style="padding:0"><strong>BDC AUTOMATIC SCORING</strong><h1><?=e($session['event_name'])?></h1><div><?=e($category)?> · <?=e(strtoupper((string)$session['round_type']))?> · <?=e($session['judge_name'])?></div></div></header><main class="wrap"><div class="card"><h2>Judging Criteria</h2><?php if($error):?><div class="error"><?=e($error)?></div><?php endif;?><div class="weights"><?php foreach(JudgingCriteriaService::weights() as [$name,$weight]):?><div class="weight"><strong><?=e($name)?></strong><span><?=e($weight)?></span></div><?php endforeach;?></div><div class="rule"><?php if($isFinal):?><strong>Final, Relative Placement:</strong> Rank your <strong>TOP <?=$configuredFinalRankLimit?></strong> best couples from 1 to <?=$configuredFinalRankLimit?>. Use each rank once. Leave all other couples as <strong>NO RANK</strong>.<?php else:?><strong>Heats:</strong> select exactly <?=$yesLimit?> YES per assigned role. A1, A2 and A3 may each be used once per role. Resolve all LATER selections before submitting.<?php endif;?></div><p>Judge independently and confidentially. Do not discuss or compare selections with another judge before submitting.</p><form method="post"><input type="hidden" name="token" value="<?=e($token)?>"><input type="hidden" name="action" value="accept_criteria"><label class="confirm"><input id="criteriaConfirm" type="checkbox" name="criteria_confirm" value="1"><span>I have read and accept the judging criteria.</span></label><button id="startScoring" class="start" disabled>Start Scoring</button></form></div></main><script>const c=document.getElementById('criteriaConfirm'),b=document.getElementById('startScoring');c.onchange=()=>b.disabled=!c.checked;</script></body></html><?php
    exit;
}

$initialState=['leader'=>['yes'=>0,'A1'=>0,'A2'=>0,'A3'=>0],'follower'=>['yes'=>0,'A1'=>0,'A2'=>0,'A3'=>0]];
if($isFinal){
    $stmt=$pdo->prepare("SELECT fp.id pair_id,fp.pair_number,le.display_name leader_name,le.bib_number leader_bib,fe.display_name follower_name,fe.bib_number follower_bib,fm.rank_value FROM bdc_scoring_final_pairs fp JOIN bdc_scoring_entries le ON le.id=fp.leader_entry_id JOIN bdc_scoring_entries fe ON fe.id=fp.follower_entry_id LEFT JOIN bdc_scoring_final_marks fm ON fm.round_id=fp.round_id AND fm.pair_id=fp.id AND fm.judge_id=:judge WHERE fp.round_id=:round AND fp.pairing_status='confirmed' ORDER BY fp.pair_number");
    $stmt->execute(['judge'=>$judgeId,'round'=>$roundId]);$pairs=$stmt->fetchAll();$finalRankLimit=min(count($pairs),max(1,(int)($weights['callback_count']??count($pairs))));
}else{
    $scope=(string)$session['scoring_scope'];
    $stmt=$pdo->prepare("SELECT e.id,e.dance_role,e.bib_number,e.display_name,m.mark_type,m.alt_rank FROM bdc_scoring_entries e LEFT JOIN bdc_scoring_marks m ON m.round_id=e.round_id AND m.entry_id=e.id AND m.judge_id=:judge WHERE e.round_id=:round AND e.entry_status='active' AND (:scope='all' OR e.dance_role=:scope2) ORDER BY e.dance_role,e.bib_number");
    $stmt->execute(['judge'=>$judgeId,'round'=>$roundId,'scope'=>$scope,'scope2'=>$scope]);$allEntries=$stmt->fetchAll();$entries=['leader'=>[],'follower'=>[]];foreach($allEntries as $entry){$entry['current_mark']=$entry['mark_type']==='yes'?'YES':($entry['mark_type']==='alt'?'A'.(int)$entry['alt_rank']:(($entry['mark_type']==='blank'&&(int)$entry['alt_rank']===9)?'LATER':''));$entries[$entry['dance_role']][]=$entry;}
    foreach(['leader','follower'] as $role)if($entries[$role])$initialState[$role]=heatsSelectionState($pdo,$roundId,$judgeId,$role);
}
$category=ucwords(str_replace('_',' ',(string)$session['division']));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Judge Scoring | BDC</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f6f9;color:#172033;font-family:Arial,sans-serif}.top{background:linear-gradient(110deg,#111,#42101c);color:#fff;padding:22px 18px;border-bottom:5px solid #d10f32}.wrap{max-width:760px;margin:auto;padding:18px}.eyebrow{font-size:12px;font-weight:800;letter-spacing:.12em;color:#ffb7c3}.top h1{margin:6px 0 4px;font-size:26px}.meta{opacity:.9;line-height:1.5}.chief{display:inline-block;background:#ffd966;color:#111;padding:4px 9px;border-radius:999px;font-size:12px;font-weight:800;margin-top:8px}.alert{padding:12px 14px;border-radius:10px;margin:0 0 14px}.error{background:#ffe6e6;color:#8a1010}.success{background:#e4f6ea;color:#176b36}.warning{background:#fff3cd;color:#664d03}.tabs{display:flex;gap:8px;position:sticky;top:0;background:#f4f6f9;padding:8px 0;z-index:3}.tab{border:1px solid #ccd2da;background:#fff;padding:10px 14px;border-radius:9px;font-weight:700;cursor:pointer}.tab.active{background:#172033;color:#fff}.panel{display:none}.panel.active{display:block}.counter{position:sticky;top:58px;z-index:2;background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:10px 12px;margin-bottom:10px;font-weight:700}.counter.over{background:#ffe6e6;color:#8a1010}.card{background:#fff;border:1px solid #dfe3e8;border-radius:14px;padding:15px;margin-bottom:10px;box-shadow:0 3px 10px rgba(15,23,42,.04)}.bib{font-size:12px;font-weight:800;color:#667085}.name{font-size:18px;font-weight:800;margin:3px 0 12px}.choices{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.choice{border:1px solid #b8c0cc;background:#fff;border-radius:9px;padding:13px 6px;min-height:48px;font-weight:800;cursor:pointer}.choice[data-value="YES"]{border:2px solid #198754}.choice[data-value="LATER"]{border:2px solid #d6a500;background:#fff7cc}.choice.no{border:2px solid #dc3545;color:#8a1010}.choice.active{background:#172033;color:#fff;border-color:#172033}.choice[data-value="LATER"].active{background:#ffc107;color:#111;border-color:#d6a500}.saved{font-size:12px;color:#18864b;margin-top:7px;min-height:15px}.saved.fail{color:#b42318;font-weight:700}.review-list{background:#fff7cc;border:2px solid #d6a500}.review-list button{margin:4px}.score{width:120px;font-size:22px;font-weight:800;text-align:center;padding:10px;border:2px solid #cdd3dc;border-radius:10px}.submitbar{position:sticky;bottom:0;background:rgba(244,246,249,.96);padding:14px 0}.submit{width:100%;border:0;background:#d10f32;color:#fff;padding:15px;border-radius:11px;font-size:17px;font-weight:800}.locked{background:#e8f6ed;border:1px solid #a9d8b9;border-radius:14px;padding:24px;text-align:center;font-weight:800}.small{font-size:12px;color:#667085;margin-top:8px}@media(max-width:620px){.choices{grid-template-columns:repeat(3,1fr);gap:9px}}
</style></head><body><header class="top"><div class="wrap" style="padding:0"><div class="eyebrow">BDC AUTOMATIC SCORING</div><h1><?=e((string)$session['event_name'])?></h1><div class="meta"><?=e($category)?> · <?=e(strtoupper((string)$session['round_type']))?><br>Judge: <strong><?=e((string)$session['judge_name'])?></strong></div><?php if((int)$session['is_chief']===1):?><span class="chief">★ CHIEF JUDGE</span><?php endif;?></div></header><main class="wrap">
<style>.choice[data-value="YES"]{border-color:#198754;color:#198754}.choice[data-value="A1"]{border:2px solid #D4A017;color:#8a6800}.choice[data-value="A2"]{border:2px solid #708090;color:#536273}.choice[data-value="A3"]{border:2px solid #B86B3D;color:#8c4d28}.choice[data-value="LATER"]{border-color:#F4B400;color:#8a6500;background:#fff}.choice.no{border-color:#DC3545;color:#DC3545}.choice[data-value="YES"].active{background:#198754;color:#fff;border-color:#198754}.choice[data-value="A1"].active{background:#D4A017;color:#000;border-color:#D4A017}.choice[data-value="A2"].active{background:#708090;color:#fff;border-color:#708090}.choice[data-value="A3"].active{background:#B86B3D;color:#fff;border-color:#B86B3D}.choice[data-value="LATER"].active{background:#F4B400;color:#000;border-color:#F4B400}.choice.no.active{background:#DC3545;color:#fff;border-color:#DC3545}.submit{background:#146C43}.criteria-btn{border:1px solid #0D6EFD;background:#fff;color:#0D6EFD;border-radius:8px;padding:8px 12px;font-weight:800;margin-bottom:14px}.criteria-dialog{max-width:650px;border:0;border-radius:14px;padding:20px}.criteria-dialog::backdrop{background:rgba(0,0,0,.55)}.criteria-dialog li{margin:7px 0}</style>
<style>.bib{font-size:28px;line-height:1;font-weight:900;color:#172033;letter-spacing:.02em;margin-bottom:6px}.name{font-size:14px;font-weight:700;color:#667085;margin:0 0 12px}.counter{padding:9px;display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.counter-item{border-radius:8px;padding:9px 5px;text-align:center;color:#fff;font-size:13px;font-weight:900}.counter-yes{background:#146C43}.counter-a1{background:#A77900}.counter-a2{background:#52677E}.counter-a3{background:#A84F20}.counter.over{outline:3px solid #DC3545}@media(max-width:620px){.counter-item{font-size:12px;padding:8px 3px}.bib{font-size:26px}}</style>
<style>.submit:disabled{background:#8A94A3;color:#F8F9FA;cursor:not-allowed;opacity:1}.submit:not(:disabled){background:#146C43;color:#fff;box-shadow:0 0 0 3px rgba(20,108,67,.16)}.final-rank-card{padding:16px}.final-rank-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px}.final-rank-card .bib{margin:2px 0 5px}.rank-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;position:sticky;top:0;z-index:4;background:rgba(244,246,249,.97);padding:8px 0;margin-bottom:8px}.rank-filter-button{border:2px solid #667085;background:#fff;color:#344054;border-radius:9px;padding:9px 12px;font-weight:800}.rank-filter-button.active{background:#344054;color:#fff}.rank-available{font-size:12px;color:#667085;font-weight:700}.rank-grid{display:grid;grid-template-columns:repeat(5,minmax(48px,1fr));gap:8px}.rank-button{min-height:48px;border:2px solid #c8d0dc;border-radius:10px;background:#fff;color:#172033;font-size:18px;font-weight:900;cursor:pointer}.rank-button:hover{border-color:#146C43}.rank-button.selected{background:#146C43;border-color:#146C43;color:#fff}.rank-filter-on .rank-button.used:not(.selected){background:#e4e7ec;border-color:#d0d5dd;color:#98a2b3}.rank-clear{grid-column:span 5;min-height:40px;border:1px solid #c8d0dc;border-radius:9px;background:#f8f9fa;color:#667085;font-weight:800}.rank-clear.selected{background:#667085;border-color:#667085;color:#fff}.final-rank-status{font-size:12px;color:#18864b;min-height:16px;margin-top:8px}.competitor-comment{margin-top:10px}.competitor-comment label{display:block;font-size:12px;font-weight:800;color:#667085;margin-bottom:4px}.comment-rank-hint{font-weight:600;color:#475467}.competitor-comment input{width:100%;min-height:38px;border:1px solid #cdd3dc;border-radius:8px;padding:8px 10px;font-size:16px;background:#fff}.competitor-comment input:focus{outline:3px solid rgba(13,110,253,.15);border-color:#0d6efd}@media(max-width:620px){.wrap{padding:12px}.top{padding:16px 12px}.top h1{font-size:22px}.final-rank-card{padding:13px;margin-bottom:8px}.final-rank-card .bib{font-size:25px}.final-rank-head{margin-bottom:9px}.rank-toolbar{align-items:stretch;flex-direction:column}.rank-filter-button{width:100%}.rank-grid{gap:7px}.rank-button{min-height:46px;font-size:18px}.competitor-comment{margin-top:8px}.comment-rank-hint{display:block;margin-top:2px}}
</style>
<?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><?php if($notice):?><div class="alert success"><?=e($notice)?></div><?php endif;?>
<button type="button" class="criteria-btn" onclick="document.getElementById('criteriaDialog').showModal()">View Criteria</button><dialog id="criteriaDialog" class="criteria-dialog"><h2>Judging Criteria</h2><ul><?php foreach(JudgingCriteriaService::weights() as [$name,$weight]):?><li><strong><?=e($name)?></strong>, <?=e($weight)?></li><?php endforeach;?></ul><p><?php if($isFinal):?>Rank your <strong>TOP <?=$finalRankLimit?></strong> best couples from 1 to <?=$finalRankLimit?>. Use each rank once. Leave all other couples as <strong>NO RANK</strong>.<?php else:?>Select exactly <?=$yesLimit?> YES per assigned role. A1, A2 and A3 may each be used once per role.<?php endif;?></p><p>Judge independently and keep all scoring confidential.</p><button type="button" class="criteria-btn" onclick="document.getElementById('criteriaDialog').close()">Close</button></dialog>
<?php if($locked):?><div class="locked">✓ SCORES SUBMITTED<br><div class="small">Your scoring is locked. This screen will reopen automatically if an authorised admin requests a rescore.</div></div><script>(function poll(){if(document.hidden){setTimeout(poll,10000);return}fetch(location.pathname+'?token='+encodeURIComponent(<?=json_encode($token)?>)+'&status=1&_='+Date.now(),{cache:'no-store'}).then(r=>r.status===429?null:r.json()).then(j=>{if(j&&j.status!=='submitted')location.reload()}).catch(()=>{}).finally(()=>setTimeout(poll,10000))})();</script>
<?php elseif($isFinal):?>
<div id="ruleMessage" class="alert warning" style="display:none"></div>
<p>Rank your <strong>TOP <?=$finalRankLimit?></strong> best couples from 1 to <?=$finalRankLimit?>. Use each rank once. Leave all other couples as <strong>NO RANK</strong>.</p>
<div class="rank-toolbar"><button type="button" id="rankFilterToggle" class="rank-filter-button">Grey Out Used Ranks</button><div id="rankAvailableSummary" class="rank-available"></div></div>
<?php foreach($pairs as $pair):?><div class="card final-rank-card" data-final-card="<?=(int)$pair['pair_id']?>"><div class="final-rank-head"><div><div class="small" style="font-weight:900">PAIR #<?=(int)$pair['pair_number']?></div><div class="bib">BIB <?=(int)$pair['leader_bib']?> + BIB <?=(int)$pair['follower_bib']?></div><div class="name"><?=e($pair['leader_name'])?> &amp; <?=e($pair['follower_name'])?></div></div></div><input class="judge-input" type="hidden" data-pair="<?=(int)$pair['pair_id']?>" data-label="Pair <?=(int)$pair['pair_number']?>" value="<?=e((string)($pair['rank_value']??''))?>"><div class="rank-grid" aria-label="Select rank for Pair <?=(int)$pair['pair_number']?>"><?php for($rankOption=1;$rankOption<=$finalRankLimit;$rankOption++):?><button type="button" class="rank-button" data-rank="<?=$rankOption?>" aria-label="Rank <?=$rankOption?>"><?=$rankOption?></button><?php endfor;?><button type="button" class="rank-clear">NO RANK</button></div><div class="competitor-comment"><label for="comment-<?=(int)$pair['pair_id']?>">Comment <span style="font-weight:400">· private draft</span> <span class="comment-rank-hint">· TOP <?=$finalRankLimit?>: use ranks 1–<?=$finalRankLimit?> once; others NO RANK</span></label><input id="comment-<?=(int)$pair['pair_id']?>" class="competitor-comment-input" data-pair="<?=(int)$pair['pair_id']?>" maxlength="160" placeholder="Tentative rank or quick note"></div><div class="saved final-rank-status"></div></div><?php endforeach;?>
<form method="post" class="submitbar" onsubmit="return confirm('Submit and lock your Final rankings? You will not be able to change them after submission.')"><input type="hidden" name="token" value="<?=e($token)?>"><input type="hidden" name="action" value="submit"><button class="submit" id="submitScores" disabled>COMPLETE ALL RANKS</button></form>
<?php else:?>
<div class="alert success"><strong>Selection rules:</strong> maximum <?=e((string)$yesLimit)?> YES per role. A1, A2 and A3 can each be used only once per role. LATER must be resolved before submission. Everyone else may be marked NO.</div>
<div id="ruleMessage" class="alert warning" style="display:none"></div>
<div id="reviewLaterList" class="card review-list" style="display:none"><strong>Review Later</strong><div class="small">Tap a name to return to that competitor.</div><div id="reviewLaterNames"></div></div>
<div class="tabs"><?php foreach(['leader'=>'LEADERS','follower'=>'FOLLOWERS'] as $role=>$label):if(!$entries[$role])continue;?><button class="tab <?=$role==='leader'?'active':''?>" data-tab="<?=$role?>"><?=$label?></button><?php endforeach;?></div>
<?php $first=true;foreach(['leader','follower'] as $role):if(!$entries[$role])continue;?><section class="panel <?=$first?'active':''?>" data-panel="<?=$role?>"><div class="counter" data-counter="<?=$role?>"></div><?php $first=false;foreach($entries[$role] as $entry):?><div class="card" data-entry-card="<?=(int)$entry['id']?>" data-role="<?=$role?>" data-name="<?=e($entry['display_name'])?>"><div class="bib"><?=strtoupper($role)==='LEADER'?'LEAD':'FOLLOW'?> #<?=(int)$entry['bib_number']?></div><div class="name"><?=e($entry['display_name'])?></div><div class="choices"><?php foreach(['YES','A1','A2','A3','LATER'] as $choice):?><button type="button" class="choice <?=$entry['current_mark']===$choice?'active':''?>" data-value="<?=$choice?>" data-entry="<?=(int)$entry['id']?>"><?=$choice?></button><?php endforeach;?><button type="button" class="choice no <?=$entry['current_mark']===''?'active':''?>" data-value="NO" data-entry="<?=(int)$entry['id']?>">NO</button></div><div class="saved"></div></div><?php endforeach;?></section><?php endforeach;?>
<form method="post" class="submitbar" onsubmit="return confirm('Submit and lock all your marks? You will not be able to change them after submission.')"><input type="hidden" name="token" value="<?=e($token)?>"><input type="hidden" name="action" value="submit"><button class="submit" id="submitScores" disabled>COMPLETE REQUIRED SELECTIONS</button></form>
<?php endif;?></main>
<?php if(!$locked):?><script>
const token=<?=json_encode($token)?>,yesLimit=<?=$yesLimit?>,finalRankLimit=<?=isset($finalRankLimit)?$finalRankLimit:0?>,selectionState=<?=json_encode($initialState,JSON_UNESCAPED_SLASHES)?>;
function showRuleMessage(message){const box=document.getElementById('ruleMessage');if(!box)return;box.textContent=message;box.style.display='block';clearTimeout(showRuleMessage.timer);showRuleMessage.timer=setTimeout(()=>box.style.display='none',4500)}
function roleReady(role){const total=document.querySelectorAll('[data-entry-card][data-role="'+role+'"]').length;if(!total)return true;const state=selectionState[role]||{yes:0,A1:0,A2:0,A3:0},requiredYes=Math.min(yesLimit,total),requiredAlts=Math.min(3,Math.max(0,total-requiredYes));return !document.querySelector('[data-entry-card][data-role="'+role+'"][data-saving="1"]')&&state.yes===requiredYes&&['A1','A2','A3'].every((alt,index)=>state[alt]===(index<requiredAlts?1:0))&&!document.querySelector('[data-entry-card][data-role="'+role+'"] .choice[data-value="LATER"].active')}
function updateSubmitReadiness(){const button=document.getElementById('submitScores');if(!button)return;if(<?=json_encode($isFinal)?>){const ranks=[...document.querySelectorAll('.judge-input')].map(input=>parseInt(input.value||'0',10)).filter(Boolean),ready=ranks.length===finalRankLimit&&new Set(ranks).size===finalRankLimit&&ranks.every(rank=>rank>=1&&rank<=finalRankLimit);button.disabled=!ready;button.textContent=ready?'READY TO SUBMIT FINAL':'COMPLETE TOP '+finalRankLimit;return}const ready=['leader','follower'].every(role=>roleReady(role));button.disabled=!ready;button.textContent=ready?'READY TO SUBMIT':'COMPLETE REQUIRED SELECTIONS'}
function updateCounter(role){const state=selectionState[role]||{yes:0,A1:0,A2:0,A3:0},el=document.querySelector('[data-counter="'+role+'"]');if(!el)return;el.innerHTML='<span class="counter-item counter-yes">YES '+state.yes+' / '+yesLimit+'</span><span class="counter-item counter-a1">A1 '+state.A1+' / 1</span><span class="counter-item counter-a2">A2 '+state.A2+' / 1</span><span class="counter-item counter-a3">A3 '+state.A3+' / 1</span>';el.classList.toggle('over',state.yes>yesLimit||state.A1>1||state.A2>1||state.A3>1);el.style.borderColor=roleReady(role)?'#198754':'';updateAvailability(role);updateSubmitReadiness()}
function updateAvailability(role){const state=selectionState[role]||{yes:0,A1:0,A2:0,A3:0};document.querySelectorAll('[data-entry-card][data-role="'+role+'"]').forEach(card=>{const current=card.querySelector('.choice.active')?.dataset.value||'';card.querySelectorAll('.choice').forEach(button=>{const value=button.dataset.value,full=value==='YES'?state.yes>=yesLimit:(['A1','A2','A3'].includes(value)&&state[value]>=1);button.style.opacity=full&&current!==value?'.42':'1';button.setAttribute('aria-disabled',full&&current!==value?'true':'false')})})}
function localRuleCheck(button){const card=button.closest('[data-entry-card]');if(!card)return true;const role=card.dataset.role,state=selectionState[role]||{yes:0,A1:0,A2:0,A3:0},current=card.querySelector('.choice.active')?.dataset.value||'',next=button.dataset.value;if(next==='YES'&&current!=='YES'&&state.yes>=yesLimit){showRuleMessage('Maximum '+yesLimit+' YES selections allowed for '+(role==='leader'?'Leaders':'Followers')+'. Clear or change another YES first.');return false;}if(['A1','A2','A3'].includes(next)&&current!==next&&state[next]>=1){showRuleMessage(next+' is already used for '+(role==='leader'?'Leaders':'Followers')+'. Each alternate rank can be used only once.');return false;}return true}
function adjustLocalState(card,newValue){if(!card)return;const role=card.dataset.role,state=selectionState[role],old=card.querySelector('.choice.active')?.dataset.value||'';if(old==='YES')state.yes=Math.max(0,state.yes-1);else if(['A1','A2','A3'].includes(old))state[old]=Math.max(0,state[old]-1);if(newValue==='YES')state.yes++;else if(['A1','A2','A3'].includes(newValue))state[newValue]++;updateCounter(role)}
function htmlEscape(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderReviewLater(){const cards=[...document.querySelectorAll('[data-entry-card]')].filter(card=>card.querySelector('.choice.active')?.dataset.value==='LATER'),box=document.getElementById('reviewLaterList'),names=document.getElementById('reviewLaterNames');box.style.display=cards.length?'block':'none';names.innerHTML=cards.map(card=>'<button type="button" class="choice" data-review-entry="'+card.dataset.entryCard+'">'+htmlEscape(card.dataset.name)+'</button>').join('');names.querySelectorAll('button').forEach(button=>button.onclick=()=>{const card=document.querySelector('[data-entry-card="'+button.dataset.reviewEntry+'"]'),role=card.dataset.role;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===role));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===role));card.scrollIntoView({behavior:'smooth',block:'center'})})}
async function saveChoice(button){
 const card=button.closest?button.closest('[data-entry-card]'):null;if(card&&card.dataset.saving==='1')return;if(card&&!localRuleCheck(button))return;
 const saved=card?card.querySelector('.saved'):button.parentElement.querySelector('.saved'),oldButton=card?card.querySelector('.choice.active'):null,oldValue=oldButton?.dataset.value||'';
 if(card){card.dataset.saving='1';adjustLocalState(card,button.dataset.value);card.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));button.classList.add('active');updateAvailability(card.dataset.role);renderReviewLater()}
 if(saved){saved.textContent='Saving…';saved.classList.remove('fail')}
 const body=new URLSearchParams({token:token,action:'save_score',ajax:'1',value:button.dataset.value});if(button.dataset.entry)body.set('entry_id',button.dataset.entry);if(button.dataset.pair)body.set('pair_id',button.dataset.pair);
 try{const r=await fetch(location.href,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()}),data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||'Save failed');if(card){const role=card.dataset.role;if(data.selection_state){selectionState[role]=data.selection_state;updateCounter(role)}renderReviewLater()}if(saved)saved.textContent='Saved '+data.saved_at;updateSubmitReadiness();}
 catch(e){if(card){adjustLocalState(card,oldValue);card.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));oldButton?.classList.add('active');updateAvailability(card.dataset.role);renderReviewLater()}if(saved){saved.textContent=e.message;saved.classList.add('fail')}showRuleMessage(e.message)}
 finally{if(card)delete card.dataset.saving;updateSubmitReadiness()}
}
document.querySelectorAll('.choice').forEach(button=>button.addEventListener('click',()=>saveChoice(button)));
function updateFinalRankButtons(){const inputs=[...document.querySelectorAll('.judge-input')],used=new Set(inputs.map(input=>input.value).filter(Boolean));document.querySelectorAll('[data-final-card]').forEach(card=>{const input=card.querySelector('.judge-input'),current=input.value;card.querySelectorAll('.rank-button').forEach(button=>{const selected=current===button.dataset.rank;button.classList.toggle('selected',selected);button.classList.toggle('used',used.has(button.dataset.rank)&&!selected);button.disabled=false;button.setAttribute('aria-pressed',selected?'true':'false')});const noRank=card.querySelector('.rank-clear');noRank.classList.toggle('selected',current==='');noRank.setAttribute('aria-pressed',current===''?'true':'false');});const available=[];for(let rank=1;rank<=finalRankLimit;rank++)if(!used.has(String(rank)))available.push(rank);const summary=document.getElementById('rankAvailableSummary');if(summary)summary.textContent=available.length?'Available: '+available.join(', '):'All required ranks assigned';}
async function persistFinalRank(input){updateFinalRankButtons();const fake={dataset:{value:input.value,pair:input.dataset.pair},parentElement:input.closest('[data-final-card]'),closest:()=>null};await saveChoice(fake);input.dataset.previous=input.value;updateFinalRankButtons();updateSubmitReadiness();}
document.querySelectorAll('.judge-input').forEach(input=>{input.dataset.previous=input.value;input.addEventListener('change',async()=>{const duplicate=[...document.querySelectorAll('.judge-input')].find(other=>other!==input&&input.value!==''&&other.value===input.value);if(duplicate){const rank=input.value,move=confirm('Rank '+rank+' is already assigned to '+duplicate.dataset.label+'. Move Rank '+rank+' to '+input.dataset.label+'?');if(!move){input.value=input.dataset.previous;updateFinalRankButtons();return;}duplicate.value='';await persistFinalRank(duplicate);showRuleMessage('Rank '+rank+' moved from '+duplicate.dataset.label+' to '+input.dataset.label+'.');}await persistFinalRank(input)})});
document.querySelectorAll('[data-final-card]').forEach(card=>{const input=card.querySelector('.judge-input');card.querySelectorAll('.rank-button').forEach(button=>button.addEventListener('click',()=>{input.value=button.dataset.rank;input.dispatchEvent(new Event('change'))}));card.querySelector('.rank-clear').addEventListener('click',()=>{input.value='';input.dispatchEvent(new Event('change'))});});
document.querySelectorAll('.competitor-comment-input').forEach(input=>{const commentKey='bdc-final-comment-<?=$roundId?>-<?=$judgeId?>-'+input.dataset.pair;input.value=localStorage.getItem(commentKey)||'';input.addEventListener('input',()=>localStorage.setItem(commentKey,input.value));});
const rankFilterToggle=document.getElementById('rankFilterToggle');if(rankFilterToggle){const filterKey='bdc-final-rank-filter-<?=$roundId?>-<?=$judgeId?>';const applyRankFilter=enabled=>{document.body.classList.toggle('rank-filter-on',enabled);rankFilterToggle.classList.toggle('active',enabled);rankFilterToggle.textContent=enabled?'Show All Ranks':'Grey Out Used Ranks';rankFilterToggle.setAttribute('aria-pressed',enabled?'true':'false');localStorage.setItem(filterKey,enabled?'1':'0')};applyRankFilter(localStorage.getItem(filterKey)==='1');rankFilterToggle.addEventListener('click',()=>applyRankFilter(!document.body.classList.contains('rank-filter-on')));}
document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.panel').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===button.dataset.tab));}));
updateFinalRankButtons();updateCounter('leader');updateCounter('follower');renderReviewLater();updateSubmitReadiness();
</script><?php endif;?></body></html>
