<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\ApiChangeProposalService;
Auth::requireSuperAdmin();$pdo=Database::connection();$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!Csrf::verify($_POST['_csrf']??null))$error='Invalid security token. Refresh and try again.';
    else try{$decision=(string)($_POST['decision']??'');$result=ApiChangeProposalService::review($pdo,(array)($_POST['proposal_ids']??[]),$decision,(int)(Auth::user()['id']??0));$notice=ucfirst($decision).' complete: '.$result['approved'].' approved, '.$result['rejected'].' rejected, '.$result['failed'].' failed.';if($result['errors'])$error=implode(' ',$result['errors']);}catch(Throwable $e){$error=$e->getMessage();}
}
$status=in_array((string)($_GET['status']??'pending'),['pending','approved','rejected','failed'],true)?(string)$_GET['status']:'pending';$q=$pdo->prepare('SELECT p.*,u.full_name reviewer_name FROM bdc_api_change_proposals p LEFT JOIN bdc_users u ON u.id=p.reviewed_by WHERE p.status=:status ORDER BY p.submitted_at DESC,p.id DESC LIMIT 500');$q->execute(['status'=>$status]);$proposals=$q->fetchAll();$counts=[];foreach($pdo->query('SELECT status,COUNT(*) total FROM bdc_api_change_proposals GROUP BY status')->fetchAll() as $row)$counts[$row['status']]=(int)$row['total'];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>API Changes | BDC</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="<?=e(url('public/css/scoring-premium.css?v=428'))?>"><script defer src="<?=e(url('public/assets/js/bdc-theme.js?v=505'))?>"></script><style>pre{white-space:pre-wrap;word-break:break-word;max-height:280px}.proposal-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1rem}</style></head><body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="../">BDC Admin</a><a class="btn btn-outline-light btn-sm" href="index.php">Integration Review</a></div></nav><main class="container-fluid py-4" style="max-width:1500px">
<div class="d-flex flex-wrap justify-content-between gap-3 align-items-start mb-4"><div><div class="text-uppercase text-primary fw-bold small">Super Admin only</div><h1 class="h2 mb-1">API Changes</h1><p class="text-muted mb-0">API proposals never change live data until approved here. Approval rechecks the live record and applies one audited transaction.</p></div><div class="btn-group"><?php foreach(['pending'=>'Pending','approved'=>'Approved','rejected'=>'Rejected','failed'=>'Failed'] as $key=>$label):?><a class="btn <?=$status===$key?'btn-primary':'btn-outline-primary'?>" href="?status=<?=$key?>"><?=e($label)?> <span class="badge text-bg-light"><?=($counts[$key]??0)?></span></a><?php endforeach;?></div></div>
<?php if($notice):?><div class="alert alert-success"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<form method="post"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><?php if($status==='pending'):?><div class="d-flex gap-2 mb-3"><button type="button" class="btn btn-outline-secondary btn-sm" id="selectAll">Select all shown</button><button class="btn btn-success" name="decision" value="approve" onclick="return confirm('Apply every selected proposal to live data?')">Approve Selected</button><button class="btn btn-outline-danger" name="decision" value="reject" onclick="return confirm('Reject every selected proposal?')">Reject Selected</button></div><?php endif;?>
<?php foreach($proposals as $p):$payload=json_decode((string)$p['payload_json'],true)?:[];$before=json_decode((string)$p['before_json'],true)?:[];?><section class="card border-0 shadow-sm mb-3"><div class="card-header bg-white d-flex flex-wrap justify-content-between gap-2"><label class="d-flex gap-2 align-items-center"><?php if($status==='pending'):?><input class="form-check-input proposal-check" type="checkbox" name="proposal_ids[]" value="<?=(int)$p['id']?>"><?php endif;?><strong><?=e((string)$p['action_type'])?></strong> <span class="badge text-bg-secondary">target #<?=(int)$p['target_id']?></span></label><span class="small text-muted"><?=e((string)$p['source_system'])?> · <?=e((string)$p['proposal_key'])?> · <?=e((string)$p['submitted_at'])?></span></div><div class="card-body proposal-grid"><div><div class="fw-bold mb-2">Current state at submission</div><pre class="bg-light border rounded p-3 mb-0"><?=e((string)json_encode($before,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></pre></div><div><div class="fw-bold mb-2">Proposed change</div><pre class="bg-primary-subtle border rounded p-3 mb-0"><?=e((string)json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></pre></div></div><?php if($p['reviewed_at']):?><div class="card-footer small text-muted">Reviewed <?=e((string)$p['reviewed_at'])?> by <?=e((string)($p['reviewer_name']?:('user #'.$p['reviewed_by'])))?></div><?php endif;?></section><?php endforeach;?><?php if(!$proposals):?><div class="card border-0 shadow-sm"><div class="card-body py-5 text-center text-muted">No <?=e($status)?> API changes.</div></div><?php endif;?></form></main><script>document.getElementById('selectAll')?.addEventListener('click',()=>document.querySelectorAll('.proposal-check').forEach(box=>box.checked=true));</script></body></html>
