<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\EventIntegrationService;
Auth::requireSuperAdmin();$pdo=Database::connection();$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Csrf::verify($_POST['_csrf']??null))$error='Invalid security token. Refresh and try again.';
 else try{$action=(string)($_POST['action']??'');if(!in_array($action,['approve','reject'],true))throw new RuntimeException('Invalid review action.');$selected=array_values(array_filter(array_map('intval',(array)($_POST['update_ids']??[]))));$result=EventIntegrationService::review($pdo,$selected,$action,(int)(Auth::user()['id']??0));$notice=ucfirst($action).' complete: '.$result['approved'].' approved, '.$result['rejected'].' rejected, '.$result['failed'].' failed.';if($result['errors'])$error=implode(' ',$result['errors']);}catch(Throwable $e){$error=$e->getMessage();}
}
$system=in_array((string)($_GET['system']??''),['all','jack_jill','dance_cup'],true)?(string)$_GET['system']:'all';$mode=in_array((string)($_GET['mode']??''),['all','live','test'],true)?(string)$_GET['mode']:'all';$sql="SELECT u.*,b.batch_key,b.source_system FROM bdc_event_integration_updates u JOIN bdc_event_integration_batches b ON b.id=u.batch_id WHERE u.status='pending'";$params=[];if($system!=='all'){$sql.=' AND u.event_system=:system';$params['system']=$system;}if($mode!=='all'){$sql.=' AND u.data_mode=:mode';$params['mode']=$mode;}$sql.=' ORDER BY u.created_at,u.id LIMIT 200';$q=$pdo->prepare($sql);$q->execute($params);$updates=$q->fetchAll();$count=(int)$pdo->query("SELECT COUNT(*) FROM bdc_event_integration_updates WHERE status='pending'")->fetchColumn();
function eventReviewCount(array $payload,string $system,string $key):int{$groups=$system==='jack_jill'?($payload['rounds']??[]):($payload['categories']??[]);$total=0;foreach($groups as $group)$total+=count((array)($group[$key]??[]));return$total;}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Event Integration Review | BDC</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="<?=e(url('public/css/scoring-premium.css?v=428'))?>"><script defer src="<?=e(url('public/assets/js/bdc-theme.js?v=505'))?>"></script><style>.setup-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.6rem}.setup-cell{background:#f8f9fa;border-radius:10px;padding:.65rem}.setup-cell small{display:block;color:#6c757d}.package-list{max-height:260px;overflow:auto}</style></head><body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="../">BDC Admin</a><a class="btn btn-outline-light btn-sm" href="../scoring/">Jack &amp; Jill Scoring</a></div></nav><main class="container-fluid py-4" style="max-width:1500px">
<div class="d-flex flex-wrap justify-content-between gap-3 align-items-start mb-4"><div><div class="text-uppercase text-primary fw-bold small">Event Setup API</div><h1 class="h2 mb-1">Bulk Event Review</h1><p class="text-muted mb-0">Each card is one atomic draft event package. Scores, points, results and publishing are outside this API.</p></div><div class="btn-group"><a class="btn btn-outline-primary" href="index.php?entity=competitor">Competitors</a><a class="btn btn-outline-primary" href="index.php?entity=judge">Judges</a><a class="btn btn-primary" href="events.php">Events <span class="badge text-bg-light"><?=$count?></span></a></div></div>
<?php if($notice):?><div class="alert alert-success"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<div class="d-flex gap-2 flex-wrap mb-3"><?php foreach(['all'=>'All events','jack_jill'=>'Jack & Jill','dance_cup'=>'Dance Cup'] as $key=>$label):?><a class="btn btn-sm <?=$system===$key?'btn-dark':'btn-outline-dark'?>" href="?system=<?=$key?>&amp;mode=<?=e($mode)?>"><?=e($label)?></a><?php endforeach;?><span class="vr"></span><?php foreach(['all'=>'All modes','live'=>'Live','test'=>'Test'] as $key=>$label):?><a class="btn btn-sm <?=$mode===$key?'btn-secondary':'btn-outline-secondary'?>" href="?system=<?=e($system)?>&amp;mode=<?=$key?>"><?=e($label)?></a><?php endforeach;?></div>
<form method="post" id="eventReview"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><div class="d-flex gap-2 flex-wrap mb-3"><button type="button" class="btn btn-outline-secondary btn-sm" id="selectAll">Select all shown</button><button class="btn btn-success" name="action" value="approve" onclick="return confirm('Create every selected draft event package?')">Approve Selected Packages</button><button class="btn btn-outline-danger" name="action" value="reject" onclick="return confirm('Reject every selected event package?')">Reject Selected Packages</button></div>
<?php foreach($updates as $u):$payload=json_decode((string)$u['payload_json'],true)?:[];$event=$payload['event']??[];$groups=$u['event_system']==='jack_jill'?($payload['rounds']??[]):($payload['categories']??[]);$groupLabel=$u['event_system']==='jack_jill'?'rounds':'categories';?>
<section class="card border-0 shadow-sm mb-3"><div class="card-header bg-white d-flex flex-wrap justify-content-between gap-3"><label class="d-flex gap-2 align-items-center"><input class="form-check-input event-check" type="checkbox" name="update_ids[]" value="<?=(int)$u['id']?>"><strong><?=e((string)($event['name']??'Unnamed event'))?></strong></label><div><span class="badge text-bg-<?=$u['data_mode']==='test'?'warning':'success'?>"><?=strtoupper(e((string)$u['data_mode']))?></span> <span class="badge text-bg-primary"><?=e($u['event_system']==='jack_jill'?'Jack & Jill':'Dance Cup')?></span> <span class="small text-muted"><?=e($u['batch_key'].' · '.$u['source_key'])?></span></div></div>
<div class="card-body"><div class="setup-grid mb-3"><div class="setup-cell"><small>Event date</small><strong><?=e((string)($event['event_date']?:'Not set'))?></strong></div><div class="setup-cell"><small>Venue / country</small><strong><?=e(trim((string)($event['venue']??'').' · '.(string)($event['country']??''),' ·')?:'Not set')?></strong></div><div class="setup-cell"><small>Package</small><strong><?=count($groups)?> <?=e($groupLabel)?> · <?=eventReviewCount($payload,$u['event_system'],'competitors')?> competitors · <?=eventReviewCount($payload,$u['event_system'],'judges')?> judge assignments</strong></div><div class="setup-cell"><small>Approval result</small><strong>One draft event, atomically</strong></div></div><div class="package-list list-group list-group-flush"><?php foreach($groups as $group):?><div class="list-group-item px-0 d-flex justify-content-between gap-3"><span><strong><?=e((string)($group['name']??$group['round_key']??'Category'))?></strong><br><small class="text-muted"><?=e((string)($group['dance_style']??''))?> · <?=e((string)($group['division']??$group['competition_level']??''))?> · <?=e((string)($group['round_type']??$group['round_name']??''))?></small></span><span class="text-end small"><?=count((array)($group['competitors']??[]))?> competitors<br><?=count((array)($group['judges']??[]))?> judges</span></div><?php endforeach;?></div></div></section>
<?php endforeach;?><?php if(!$updates):?><div class="card border-0 shadow-sm"><div class="card-body py-5 text-center text-muted">No pending event setup packages in this filter.</div></div><?php endif;?></form></main><script>document.getElementById('selectAll')?.addEventListener('click',()=>document.querySelectorAll('.event-check').forEach(box=>box.checked=true));</script></body></html>
