<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/bootstrap.php';
use App\Core\Auth;use App\Core\Csrf;use App\Core\Database;use App\Services\ProfileIntegrationAuth;use App\Services\ProfileIntegrationService;
Auth::requireAdmin();$pdo=Database::connection();$canCompetitors=Auth::can('competitors.edit');$canJudges=Auth::can('judges.edit');if(!$canCompetitors&&!$canJudges){http_response_code(403);exit('You do not have permission to review profile updates.');}$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Csrf::verify($_POST['_csrf']??null))$error='Invalid security token. Refresh and try again.';
 else try{$action=(string)($_POST['action']??'');
  if($action==='assign_target'){$entity=(string)($_POST['entity_type']??'');if(($entity==='judge'&&!$canJudges)||(in_array($entity,['competitor','wdc_identity'],true)&&!$canCompetitors))throw new RuntimeException('You cannot review this profile type.');ProfileIntegrationService::assignTarget($pdo,(int)($_POST['update_id']??0),(int)($_POST['target_id']??0),$entity);$notice='Identity match saved.';}
  elseif(in_array($action,['approve','reject'],true)){$selected=array_values(array_filter(array_map('intval',(array)($_POST['update_ids']??[]))));if(!$selected)throw new RuntimeException('Select at least one update.');$marks=implode(',',array_fill(0,count($selected),'?'));$q=$pdo->prepare("SELECT id,entity_type FROM bdc_profile_integration_updates WHERE id IN($marks) AND status='pending'");$q->execute($selected);$allowed=[];foreach($q->fetchAll() as $row)if(($row['entity_type']==='judge'&&$canJudges)||(in_array($row['entity_type'],['competitor','wdc_identity'],true)&&$canCompetitors))$allowed[]=(int)$row['id'];$result=ProfileIntegrationService::review($pdo,$allowed,$action,(int)(Auth::user()['id']??0));$notice=ucfirst($action).' complete: '.$result['approved'].' approved, '.$result['rejected'].' rejected, '.$result['failed'].' failed.';if($result['errors'])$error=implode(' ',$result['errors']);}
  else throw new RuntimeException('Invalid review action.');
 }catch(Throwable $e){$error=$e->getMessage();}
}
$entity=in_array((string)($_GET['entity']??''),['competitor','judge','wdc_identity'],true)?(string)$_GET['entity']:($canCompetitors?'competitor':'judge');if(in_array($entity,['competitor','wdc_identity'],true)&&!$canCompetitors)$entity='judge';if($entity==='judge'&&!$canJudges)$entity='competitor';$match=in_array((string)($_GET['match']??''),['all','new','matched','ambiguous','invalid'],true)?(string)$_GET['match']:'all';$sql="SELECT u.*,b.batch_key,b.source_system FROM bdc_profile_integration_updates u JOIN bdc_profile_integration_batches b ON b.id=u.batch_id WHERE u.status='pending' AND u.entity_type=:entity";$params=['entity'=>$entity];if($match!=='all'){$sql.=' AND u.match_status=:match';$params['match']=$match;}$sql.=' ORDER BY u.created_at,u.id LIMIT 500';$q=$pdo->prepare($sql);$q->execute($params);$updates=$q->fetchAll();$counts=[];foreach($pdo->query("SELECT entity_type,COUNT(*) count FROM bdc_profile_integration_updates WHERE status='pending' GROUP BY entity_type")->fetchAll() as $row)$counts[$row['entity_type']]=(int)$row['count'];$pendingApiChanges=Auth::isSuperAdmin()?(int)$pdo->query("SELECT COUNT(*) FROM bdc_api_change_proposals WHERE status='pending'")->fetchColumn():0;$credentialStatus=Auth::isSuperAdmin()?ProfileIntegrationAuth::credentialStatus():null;
function reviewCurrent(PDO $pdo,string $entity,int $id):array{if(!$id)return[];$table=$entity==='judge'?'bdc_judges':($entity==='wdc_identity'?'bdc_wdc_identities':'bdc_competitors');$q=$pdo->prepare("SELECT * FROM {$table} WHERE id=:id");$q->execute(['id'=>$id]);return$q->fetch()?:[];}
function reviewCurrentField(string $entity,array $current,string $key):string{$map=$entity==='competitor'?['full_name'=>'exact_name','role'=>'dance_role']:($entity==='wdc_identity'?['wdc_id'=>'identity_code','person_id'=>'solo_competitor_id']:[]);$field=$map[$key]??$key;$value=$current[$field]??'';if($key==='registrations')return'Existing category registrations are preserved';return is_array($value)?implode(', ',$value):(string)$value;}
function reviewCandidates(PDO $pdo,string $entity,?string $json):array{$ids=array_values(array_filter(array_map('intval',(array)json_decode((string)$json,true))));if(!$ids)return[];$table=$entity==='judge'?'bdc_judges':($entity==='wdc_identity'?'bdc_wdc_identities':'bdc_competitors');$name=$entity==='judge'?'full_name':($entity==='wdc_identity'?'display_name':'exact_name');$marks=implode(',',array_fill(0,count($ids),'?'));$q=$pdo->prepare("SELECT id,{$name} profile_name FROM {$table} WHERE id IN($marks) ORDER BY {$name}");$q->execute($ids);return$q->fetchAll();}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Integration Review | BDC</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="<?=e(url('public/css/scoring-premium.css?v=428'))?>"><script defer src="<?=e(url('public/assets/js/bdc-theme.js?v=505'))?>"></script><style>.review-photo{width:90px;height:110px;object-fit:contain;background:#eef1f5;border-radius:10px}.payload-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.45rem}.payload-field{background:#f8f9fa;border-radius:8px;padding:.5rem}.payload-field small{display:block;color:#6c757d}</style></head><body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="../">BDC Admin</a><a class="btn btn-outline-light btn-sm" href="../form-sync/">Form Sync History</a></div></nav><main class="container-fluid py-4" style="max-width:1500px">
<div class="d-flex flex-wrap justify-content-between gap-3 align-items-start mb-4"><div><div class="text-uppercase text-primary fw-bold small">Profile Integration API</div><h1 class="h2 mb-1">Bulk Review</h1><p class="text-muted mb-0">Nothing changes in live profiles until selected updates are approved.</p></div><div class="btn-group"><?php if($canCompetitors):?><a class="btn <?=$entity==='competitor'?'btn-primary':'btn-outline-primary'?>" href="?entity=competitor">Competitors <span class="badge text-bg-light"><?=($counts['competitor']??0)?></span></a><a class="btn <?=$entity==='wdc_identity'?'btn-primary':'btn-outline-primary'?>" href="?entity=wdc_identity">WDC <span class="badge text-bg-light"><?=($counts['wdc_identity']??0)?></span></a><?php endif;?><?php if($canJudges):?><a class="btn <?=$entity==='judge'?'btn-primary':'btn-outline-primary'?>" href="?entity=judge">Judges <span class="badge text-bg-light"><?=($counts['judge']??0)?></span></a><?php endif;?><?php if(Auth::isSuperAdmin()):?><a class="btn btn-outline-primary" href="events.php">Events</a><a class="btn <?=$pendingApiChanges?'btn-warning':'btn-outline-primary'?>" href="actions.php">API Changes <span class="badge text-bg-light"><?=$pendingApiChanges?></span></a><?php endif;?></div></div>
<?php if(Auth::isSuperAdmin()&&$pendingApiChanges):?><div class="alert alert-warning d-flex flex-wrap justify-content-between align-items-center gap-2"><div><strong><?=$pendingApiChanges?> API change<?= $pendingApiChanges===1?'':'s' ?> awaiting approval.</strong> WDC removals appear in API Changes, not the WDC profile tab.</div><a class="btn btn-warning" href="actions.php">Review removals and changes</a></div><?php endif;?>
<?php if($notice):?><div class="alert alert-success"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="btn-group mb-3"><?php foreach(['all'=>'All','new'=>'New','matched'=>'Matched','ambiguous'=>'Conflicts','invalid'=>'Invalid ID'] as $key=>$label):?><a class="btn btn-sm <?=$match===$key?'btn-dark':'btn-outline-dark'?>" href="?entity=<?=e($entity)?>&match=<?=$key?>"><?=e($label)?></a><?php endforeach;?></div>
<?php if($credentialStatus):?><section class="card border-0 shadow-sm mb-3"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3"><div><div class="fw-bold">Integration Credential</div><div class="small text-muted"><?=$credentialStatus['configured']?'Connected · fingerprint '.e($credentialStatus['fingerprint']):'Not configured'?> · <?=e($credentialStatus['source'])?></div><div class="small text-muted">Creating a new credential immediately revokes the previous file-managed credential.</div></div><?php if($credentialStatus['rotatable']):?><form method="post" action="credential.php"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><button class="btn btn-outline-primary" onclick="return confirm('Create a new persistent API credential? Any previous file-managed integration credential will stop working immediately.')"><?=$credentialStatus['configured']?'Rotate & Download Credential':'Create & Download Credential'?></button></form><?php else:?><span class="badge text-bg-secondary">Managed by server environment</span><?php endif;?></div></section><?php endif;?>
<form method="post" id="bulkReview"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><div class="d-flex gap-2 flex-wrap mb-3"><button type="button" class="btn btn-outline-secondary btn-sm" id="selectAll">Select all shown</button><button class="btn btn-success" name="action" value="approve" onclick="return confirm('Approve every selected profile update?')">Approve Selected</button><button class="btn btn-outline-danger" name="action" value="reject" onclick="return confirm('Reject every selected profile update?')">Reject Selected</button></div>
<?php foreach($updates as $u):$payload=json_decode((string)$u['payload_json'],true)?:[];$current=reviewCurrent($pdo,$entity,(int)$u['target_id']);$candidates=reviewCandidates($pdo,$entity,$u['candidate_ids_json']);?>
<section class="card border-0 shadow-sm mb-3"><div class="card-header bg-white d-flex justify-content-between gap-3"><label class="d-flex gap-2 align-items-center"><input class="form-check-input review-check" type="checkbox" name="update_ids[]" value="<?=(int)$u['id']?>"><strong><?=e((string)($payload['full_name']??$payload['display_name']??'Unnamed'))?></strong></label><div><span class="badge text-bg-<?=$u['match_status']==='ambiguous'?'warning':($u['match_status']==='invalid'?'danger':'secondary')?>"><?=e($u['match_status'])?></span> <span class="small text-muted"><?=e($u['batch_key'].' · '.$u['source_key'])?></span></div></div>
<div class="card-body"><div class="d-flex flex-column flex-lg-row gap-3"><?php if($u['staged_photo_name']):?><img class="review-photo" src="photo.php?id=<?=(int)$u['id']?>" alt="Staged profile photo"><?php endif;?><div class="flex-grow-1"><div class="payload-grid"><?php foreach($payload as $key=>$value):if($key==='replace_fields'||$value===''||$value===[])continue;$proposed=is_array($value)?($key==='registrations'?implode(' · ',array_map(static fn(array $r):string=>(string)($r['category_name']??'').' ['.(string)($r['dance_style']??'').']',$value)):implode(', ',$value)):(string)$value;$before=$current?reviewCurrentField($entity,$current,$key):'';?><div class="payload-field"><small><?=e(ucwords(str_replace('_',' ',$key)))?></small><strong><?=e($proposed)?></strong><?php if($current):?><small>Current: <?=e($before!==''?$before:'—')?></small><?php endif;?></div><?php endforeach;?></div><?php if($current):$nameField=$entity==='judge'?'full_name':($entity==='wdc_identity'?'display_name':'exact_name');$codeField=$entity==='judge'?'judge_code':($entity==='wdc_identity'?'identity_code':'bdc_id');?><div class="alert alert-info py-2 mt-3 mb-0"><strong>Matched live profile:</strong> <?=e((string)($current[$nameField]??''))?> · <?=e((string)($current[$codeField]??''))?></div><?php endif;?></div></div></div>
<?php if($candidates):?><div class="card-footer bg-warning-subtle"><div class="d-flex gap-2 align-items-end"><div class="flex-grow-1"><label class="form-label small">Resolve identity before approval</label><select class="form-select" id="target-<?=(int)$u['id']?>"><?php foreach($candidates as $candidate):?><option value="<?=(int)$candidate['id']?>"><?=e($candidate['profile_name'])?> · #<?=(int)$candidate['id']?></option><?php endforeach;?></select></div><button type="button" class="btn btn-warning assign-target" data-update="<?=(int)$u['id']?>" data-entity="<?=e($entity)?>">Use selected profile</button></div></div><?php endif;?></section>
<?php endforeach;?><?php if(!$updates):?><div class="card border-0 shadow-sm"><div class="card-body py-5 text-center text-muted">No pending <?=e($entity)?> updates in this filter.</div></div><?php endif;?></form>
<form method="post" id="assignForm"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="action" value="assign_target"><input type="hidden" name="update_id"><input type="hidden" name="target_id"><input type="hidden" name="entity_type"></form></main>
<script>document.getElementById('selectAll')?.addEventListener('click',()=>document.querySelectorAll('.review-check').forEach(box=>box.checked=true));document.querySelectorAll('.assign-target').forEach(button=>button.addEventListener('click',()=>{const form=document.getElementById('assignForm'),id=button.dataset.update;form.querySelector('[name=update_id]').value=id;form.querySelector('[name=target_id]').value=document.getElementById('target-'+id).value;form.querySelector('[name=entity_type]').value=button.dataset.entity;form.submit()}));</script></body></html>
